import type { ArticleBlock } from '@nagarikwatch/db'
import type { StoredArticle } from './json-store'

function p(text: string): ArticleBlock {
  return { type: 'paragraph', text }
}

function isoDaysAgo(days: number, hour = 8): string {
  const d = new Date()
  d.setUTCDate(d.getUTCDate() - days)
  d.setUTCHours(hour, 15, 0, 0)
  return d.toISOString()
}

/**
 * Original Nagarik Watch edition — 5 stories per category.
 * Editable via /admin/articles. No third-party outlet copy.
 */
export function buildOriginalStarterArticles(createdBy = 'newsroom-boot'): StoredArticle[] {
  const base = (
    partial: Pick<
      StoredArticle,
      'id' | 'slug' | 'categorySlug' | 'titleNe' | 'bodyNe' | 'publishedAt' | 'updatedAt'
    > &
      Partial<StoredArticle>,
  ): StoredArticle => {
    const bodyNe = partial.bodyNe
    const words = bodyNe
      .map((b) => ('text' in b ? b.text : ''))
      .join(' ')
      .split(/\s+/)
      .filter(Boolean).length
    return {
      authorIds: ['aut-newsroom-desk'],
      tagSlugs: [],
      isBreaking: false,
      isFeatured: 'none',
      workflowStage: 'published',
      sourceType: 'original',
      premium: false,
      commentsEnabled: true,
      locale: 'ne',
      noIndex: false,
      includeInNewsSitemap: true,
      ...partial,
      hasEnglish: Boolean(partial.titleEn && partial.bodyEn?.length),
      readingMinutes: Math.max(1, Math.round(words / 200)),
      createdBy,
      updatedBy: createdBy,
    }
  }

  return [
    base({
      id: "art-nw-politics-1",
      slug: "parliament-monsoon-session-agenda",
      categorySlug: "politics",
      titleNe: "मनसुन अधिवेशन: बजेट कार्यान्वयन र बिल प्राथमिकतामा",
      titleEn: "Monsoon session: budget delivery and bill priorities",
      deckNe: "सङ्घीय संसदको अधिवेशनमा सरकारको प्राथमिकतासूची स्पष्ट हुँदैछ।",
      deckEn: "Parliamentary priorities for the monsoon session are coming into focus.",
      publishedAt: isoDaysAgo(0, 6),
      updatedAt: isoDaysAgo(0, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("संसद् सचिवालय स्रोतअनुसार मनसुन अधिवेशनमा बजेट कार्यान्वयनसँग जोडिएका विधेयकलाई प्राथमिकता दिने तयारी छ।"),
        p("विपक्षी दलहरूले सार्वजनिक खरिद र पारदर्शितासम्बन्धी छलफल खोज्ने संकेत गरेका छन्।"),
        p("नागरिक वाच संसदीय डेस्कले दलगत धारणा अद्यावधिक गर्दै जानेछ।"),
      ],
      bodyEn: [
        p("Parliamentary priorities for the monsoon session are coming into focus."),
        p("संसद् सचिवालय स्रोतअनुसार मनसुन अधिवेशनमा बजेट कार्यान्वयनसँग जोडिएका विधेयकलाई प्राथमिकता दिने तयारी छ।"),
      ],
      tagSlugs: ["politics"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-politics-2",
      slug: "local-election-finance-disclosure",
      categorySlug: "politics",
      titleNe: "स्थानीय चुनाव खर्च: पारदर्शिताको नयाँ मापदण्ड",
      titleEn: "Local election spending: a new transparency bar",
      deckNe: "चुनाव खर्च विवरण सार्वजनिक गर्न दल र उम्मेदवारलाई दबाब बढेको छ।",
      deckEn: "Parties and candidates face fresh pressure to disclose campaign spending.",
      publishedAt: isoDaysAgo(1, 7),
      updatedAt: isoDaysAgo(1, 7),
      bodyNe: [
        p("निर्वाचन आयोगले खर्च विवरण ढिलो बुझाउने उम्मेदवारलाई कारबाहीको चेतावनी दिएको छ।"),
        p("नागरिक वाचले काठमाडौंका तीन महानगरका उम्मेदवार खर्च सूचीको नमुना तुलना गरेको छ।"),
        p("पाठकलाई आग्रह: आफ्नो वडाका उम्मेदवारको खर्च विवरण माग्नुहोस्।"),
      ],
      bodyEn: [
        p("Parties and candidates face fresh pressure to disclose campaign spending."),
        p("निर्वाचन आयोगले खर्च विवरण ढिलो बुझाउने उम्मेदवारलाई कारबाहीको चेतावनी दिएको छ।"),
      ],
      tagSlugs: ["politics"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-politics-3",
      slug: "federal-civil-service-reform-brief",
      categorySlug: "politics",
      titleNe: "सङ्घीय निजामती सुधार: प्रदेशसँग समन्वयको चुनौती",
      titleEn: "Federal civil service reform: coordinating with provinces",
      deckNe: "कर्मचारी समायोजन र पदपूर्ति प्रक्रियामा प्रदेशको भूमिका विवादित छ।",
      deckEn: "Provincial roles in staffing and transfers remain contested.",
      publishedAt: isoDaysAgo(2, 8),
      updatedAt: isoDaysAgo(2, 8),
      bodyNe: [
        p("सङ्घीय मामिला मन्त्रालयले समायोजन मार्गदर्शन अद्यावधिक गर्ने जनाएको छ।"),
        p("प्रदेश प्रशासनले कार्यान्वयनमा ढिलाइ भएको गुनासो गरेका छन्।"),
        p("नागरिक वाचले दुवै तहका अधिकारीसँग कुरा गरेको छ।"),
      ],
      bodyEn: [
        p("Provincial roles in staffing and transfers remain contested."),
        p("सङ्घीय मामिला मन्त्रालयले समायोजन मार्गदर्शन अद्यावधिक गर्ने जनाएको छ।"),
      ],
      tagSlugs: ["politics"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-politics-4",
      slug: "women-representation-parliament-watch",
      categorySlug: "politics",
      titleNe: "महिला प्रतिनिधित्व: संसदीय समितिमा आवाज",
      titleEn: "Women in parliament: committee voice and agenda",
      deckNe: "समिति बैठकमा महिला सांसदको सहभागिता र एजेन्डा प्रभाव मापन गरिएको छ।",
      deckEn: "A desk count of women MPs’ committee participation and agenda impact.",
      publishedAt: isoDaysAgo(3, 9),
      updatedAt: isoDaysAgo(3, 9),
      bodyNe: [
        p("नागरिक वाचले तीन महिनाका समिति कार्यसूचीको नमुना विश्लेषण गरेको छ।"),
        p("महिला सांसदहरूले बजेट र सामाजिक सुरक्षामाथिको छलफल बढाउन माग गरेका छन्।"),
        p("दलहरूले आन्तरिक कोटा कार्यान्वयनको प्रगति सार्वजनिक गर्नुपर्ने धारणा राखिएको छ।"),
      ],
      bodyEn: [
        p("A desk count of women MPs’ committee participation and agenda impact."),
        p("नागरिक वाचले तीन महिनाका समिति कार्यसूचीको नमुना विश्लेषण गरेको छ।"),
      ],
      tagSlugs: ["politics"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-politics-5",
      slug: "cabinet-decision-transparency-note",
      categorySlug: "politics",
      titleNe: "मन्त्रिपरिषद् निर्णय: सार्वजनिक सूचनाको अन्तराल",
      titleEn: "Cabinet decisions: the public-notice gap",
      deckNe: "केही निर्णय प्रेस विज्ञप्तिमै सीमित रहँदा विवरण अपूर्ण देखिन्छ।",
      deckEn: "Some decisions stay in press notes while detail stays thin.",
      publishedAt: isoDaysAgo(4, 10),
      updatedAt: isoDaysAgo(4, 10),
      bodyNe: [
        p("सरकार प्रवक्ताले नियमित सारांश जारी गर्ने प्रतिबद्धता दोहोर्याएका छन्।"),
        p("नागरिक वाचले गत महिनाका निर्णय सूची र सार्वजनिक सूचनाको मेल नमिलेको उदाहरण नोट गरेको छ।"),
        p("पारदर्शिताका लागि पूर्ण कार्यवृत्त समयमै सार्वजनिक हुनुपर्ने माग उठेको छ।"),
      ],
      bodyEn: [
        p("Some decisions stay in press notes while detail stays thin."),
        p("सरकार प्रवक्ताले नियमित सारांश जारी गर्ने प्रतिबद्धता दोहोर्याएका छन्।"),
      ],
      tagSlugs: ["politics"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-society-1",
      slug: "monsoon-preparedness-kathmandu-valley-2026",
      categorySlug: "society",
      titleNe: "काठमाडौं उपत्यकामा मनसुन पूर्वतयारी: नाली सफाइ र बाढी जोखिम",
      titleEn: "Kathmandu Valley monsoon readiness: drains and flood risk",
      deckNe: "महानगरहरूले नाली सफाइ तीव्र पारेका छन्।",
      deckEn: "Municipalities intensified drain clearing before peak rains.",
      publishedAt: isoDaysAgo(5, 6),
      updatedAt: isoDaysAgo(5, 6),
      isFeatured: "lead",
      isBreaking: true,
      bodyNe: [
        p("काठमाडौं, ललितपुर र भक्तपुरले मनसुनअघि नाली सफाइ अभियान तेज पारेका छन्।"),
        p("बागमती किनारका केही बस्तीमा पूर्व चेतावनी प्रणाली सक्रिय छ।"),
        p("नागरिक वाचले पाठकलाई वडा आपत्कालीन सम्पर्क नोट गर्न आग्रह गर्छ।"),
      ],
      bodyEn: [
        p("Municipalities intensified drain clearing before peak rains."),
        p("काठमाडौं, ललितपुर र भक्तपुरले मनसुनअघि नाली सफाइ अभियान तेज पारेका छन्।"),
      ],
      tagSlugs: ["society"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-society-2",
      slug: "urban-waste-segregation-drive",
      categorySlug: "society",
      titleNe: "सहरी फोहोर व्यवस्थापन: स्रोतमै वर्गीकरण अभियान",
      titleEn: "Urban waste: segregation at source",
      deckNe: "घरघरमा जैविक र अजैविक छुट्याउने अभ्यास विस्तार हुँदैछ।",
      deckEn: "Household segregation of organic and inorganic waste is spreading.",
      publishedAt: isoDaysAgo(6, 7),
      updatedAt: isoDaysAgo(6, 7),
      bodyNe: [
        p("केही वडाले सङ्कलन तालिका अद्यावधिक गरी जरिवानाको व्यवस्था सुनाएका छन्।"),
        p("नागरिक वाच स्थलगत भ्रमणमा सचेतना अभियानको प्रभाव असमान भेट्टायो।"),
        p("स्थानीय समूहले कम्पोस्ट तालिमको माग गरेका छन्।"),
      ],
      bodyEn: [
        p("Household segregation of organic and inorganic waste is spreading."),
        p("केही वडाले सङ्कलन तालिका अद्यावधिक गरी जरिवानाको व्यवस्था सुनाएका छन्।"),
      ],
      tagSlugs: ["society"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-society-3",
      slug: "community-policing-night-patrol",
      categorySlug: "society",
      titleNe: "सामुदायिक प्रहरी: रात्रि गस्ती र विश्वास",
      titleEn: "Community policing: night patrols and trust",
      deckNe: "बस्तीस्तरीय गस्तीले चोरी नियन्त्रणमा सहयोग पुगेको स्थानीयको भनाइ छ।",
      deckEn: "Residents say neighbourhood patrols helped curb petty theft.",
      publishedAt: isoDaysAgo(7, 8),
      updatedAt: isoDaysAgo(7, 8),
      bodyNe: [
        p("प्रहरी र टोल विकास संस्थाले संयुक्त गस्ती तालिका सार्वजनिक गरेका छन्।"),
        p("महिला स्वयंसेविकाको सहभागिता बढाउने योजना छलफलमा छ।"),
        p("नागरिक वाचले गोपनीयता र सुरक्षा सन्तुलनमाथि प्रश्न राखेको छ।"),
      ],
      bodyEn: [
        p("Residents say neighbourhood patrols helped curb petty theft."),
        p("प्रहरी र टोल विकास संस्थाले संयुक्त गस्ती तालिका सार्वजनिक गरेका छन्।"),
      ],
      tagSlugs: ["society"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-society-4",
      slug: "senior-citizen-allowance-delivery",
      categorySlug: "society",
      titleNe: "वृद्धभत्ता वितरण: बैंक पहुँचको अनुभव",
      titleEn: "Senior allowance: banking access on the ground",
      deckNe: "भत्ता लिन बैंक पुग्न नसक्ने वृद्धको गुनासो दोहोरिएको छ।",
      deckEn: "Elders again report trouble reaching banks for allowances.",
      publishedAt: isoDaysAgo(8, 9),
      updatedAt: isoDaysAgo(8, 9),
      bodyNe: [
        p("स्थानीय तहले घुम्ती सेवा र सहयोगी परिचालन गर्ने तयारी जनाएको छ।"),
        p("नागरिक वाचले तीन वडाका वितरण दिन स्थलगत अवलोकन गरेको छ।"),
        p("डिजिटल भुक्तानी विकल्प विस्तार गर्न माग उठेको छ।"),
      ],
      bodyEn: [
        p("Elders again report trouble reaching banks for allowances."),
        p("स्थानीय तहले घुम्ती सेवा र सहयोगी परिचालन गर्ने तयारी जनाएको छ।"),
      ],
      tagSlugs: ["society"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-society-5",
      slug: "road-safety-school-zones",
      categorySlug: "society",
      titleNe: "विद्यालय क्षेत्र सडक सुरक्षा: गति नियन्त्रण",
      titleEn: "School-zone road safety: slowing traffic",
      deckNe: "विद्यालय अगाडि गति कम गर्ने अभियान विस्तार भएको छ।",
      deckEn: "A campaign to slow traffic outside schools is expanding.",
      publishedAt: isoDaysAgo(9, 10),
      updatedAt: isoDaysAgo(9, 10),
      bodyNe: [
        p("यातायात कार्यालयले चिन्ह र जेब्रा क्रसिङ मर्मतको सूची सार्वजनिक गरेको छ।"),
        p("अभिभावक समूहले मोटरसाइकल ओभरटेक नियन्त्रण मागेका छन्।"),
        p("नागरिक वाचले बिहानको भीडमा मापन गरेको औसत गति जोखिमपूर्ण देखियो।"),
      ],
      bodyEn: [
        p("A campaign to slow traffic outside schools is expanding."),
        p("यातायात कार्यालयले चिन्ह र जेब्रा क्रसिङ मर्मतको सूची सार्वजनिक गरेको छ।"),
      ],
      tagSlugs: ["society"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-business-1",
      slug: "nepse-week-ahead-liquidity-watch",
      categorySlug: "business",
      titleNe: "सेयर बजार: तरलता र ब्याजदरको असर",
      titleEn: "Share market: liquidity and rate pressure",
      deckNe: "लगानीकर्ताले बैंक ब्याज र तरलता संकेत नियाल्दै छन्।",
      deckEn: "Investors are watching bank rates and liquidity signals.",
      publishedAt: isoDaysAgo(10, 6),
      updatedAt: isoDaysAgo(10, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("नेप्से परिसूचक संकुचित दायरामा किनबेच भयो।"),
        p("ब्रोकर हाउसहरूले आकार मिलाएर कारोबार गर्ने सल्लाह दिए।"),
        p("नागरिक वाच बजार डेस्कले साप्ताहिक सारांश अद्यावधिक गर्छ।"),
      ],
      bodyEn: [
        p("Investors are watching bank rates and liquidity signals."),
        p("नेप्से परिसूचक संकुचित दायरामा किनबेच भयो।"),
      ],
      tagSlugs: ["business"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-business-2",
      slug: "sme-credit-guarantee-uptake",
      categorySlug: "business",
      titleNe: "साना उद्योग ऋण: जमानत योजनाको उपयोग",
      titleEn: "SME credit: guarantee scheme uptake",
      deckNe: "जमानत सुविधाको उपयोग असमान देखिएको छ।",
      deckEn: "Uptake of the credit guarantee facility looks uneven.",
      publishedAt: isoDaysAgo(11, 7),
      updatedAt: isoDaysAgo(11, 7),
      bodyNe: [
        p("बैंकहरूले कागजात प्रक्रिया सरल बनाउने दाबी गरेका छन्।"),
        p("उद्यमीले धितो र ब्याजदर अझै बाधक भएको बताए।"),
        p("नागरिक वाचले प्रदेशस्तरीय वितरणको नमुना तुलना गरेको छ।"),
      ],
      bodyEn: [
        p("Uptake of the credit guarantee facility looks uneven."),
        p("बैंकहरूले कागजात प्रक्रिया सरल बनाउने दाबी गरेका छन्।"),
      ],
      tagSlugs: ["business"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-business-3",
      slug: "remittance-household-budget-shift",
      categorySlug: "business",
      titleNe: "विप्रेषण र घर खर्च: बचतको प्राथमिकता",
      titleEn: "Remittance and household budgets: saving first",
      deckNe: "केही परिवारले मासिक खर्च कटौती गरी बचत बढाएका छन्।",
      deckEn: "Some households cut monthly spending to raise savings.",
      publishedAt: isoDaysAgo(12, 8),
      updatedAt: isoDaysAgo(12, 8),
      bodyNe: [
        p("बैंकिङ तथ्यांकअनुसार बचत खाता गतिविधि बढेको संकेत छ।"),
        p("बजार मूल्य वृद्धिका कारण खाद्य खर्च अझै दबाबमा छ।"),
        p("नागरिक वाचले काठमाडौं र तराईका परिवारसँग कुरा गरेको छ।"),
      ],
      bodyEn: [
        p("Some households cut monthly spending to raise savings."),
        p("बैंकिङ तथ्यांकअनुसार बचत खाता गतिविधि बढेको संकेत छ।"),
      ],
      tagSlugs: ["business"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-business-4",
      slug: "tourism-homestay-booking-trend",
      categorySlug: "business",
      titleNe: "होमस्टे बुकिङ: आन्तरिक पर्यटनको लहर",
      titleEn: "Homestay bookings: domestic travel wave",
      deckNe: "सप्ताहान्त होमस्टे बुकिङ बढेको सञ्चालकको भनाइ छ।",
      deckEn: "Operators report stronger weekend homestay bookings.",
      publishedAt: isoDaysAgo(13, 9),
      updatedAt: isoDaysAgo(13, 9),
      bodyNe: [
        p("यातायात र मौसम पूर्वानुमानले बुकिङ ढाँचा प्रभावित छ।"),
        p("स्थानीय उत्पादन बिक्रीसँग जोडिएका प्याकेज लोकप्रिय छन्।"),
        p("नागरिक वाच पर्यटन डेस्कले तीन जिल्लाका अनुभव सङ्कलन गरेको छ।"),
      ],
      bodyEn: [
        p("Operators report stronger weekend homestay bookings."),
        p("यातायात र मौसम पूर्वानुमानले बुकिङ ढाँचा प्रभावित छ।"),
      ],
      tagSlugs: ["business"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-business-5",
      slug: "fuel-price-transport-cost-pass",
      categorySlug: "business",
      titleNe: "इन्धन मूल्य: यातायात भाडामा असर",
      titleEn: "Fuel prices: pass-through to transport fares",
      deckNe: "भाडा समायोजनको बहस फेरि खुलेको छ।",
      deckEn: "The fare-adjustment debate has reopened.",
      publishedAt: isoDaysAgo(0, 10),
      updatedAt: isoDaysAgo(0, 10),
      bodyNe: [
        p("यातायात व्यवसायीले लागत वृद्धि देखाएका छन्।"),
        p("यात्री समूहले पारदर्शी गणना मागेका छन्।"),
        p("नागरिक वाचले सार्वजनिक यातायात मार्गको नमुना भाडा तुलना गरेको छ।"),
      ],
      bodyEn: [
        p("The fare-adjustment debate has reopened."),
        p("यातायात व्यवसायीले लागत वृद्धि देखाएका छन्।"),
      ],
      tagSlugs: ["business"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-sports-1",
      slug: "nepal-cricket-domestic-league-preview",
      categorySlug: "sports",
      titleNe: "घरेलु क्रिकेट लिग: युवा खेलाडीको अवसर",
      titleEn: "Domestic cricket league: lane for young players",
      deckNe: "घरेलु सिजनको तालिका अगाडि सारिएको छ।",
      deckEn: "The domestic calendar was brought forward.",
      publishedAt: isoDaysAgo(1, 6),
      updatedAt: isoDaysAgo(1, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("प्रशिक्षकहरूले फिटनेस र फिल्डिङमा जोड दिएका छन्।"),
        p("युवा खेलाडी चयनमा प्रदर्शनलाई प्राथमिकता दिइने जनाइएको छ।"),
        p("नागरिक वाच खेल डेस्क मैदानबाटै अपडेट दिनेछ।"),
      ],
      bodyEn: [
        p("The domestic calendar was brought forward."),
        p("प्रशिक्षकहरूले फिटनेस र फिल्डिङमा जोड दिएका छन्।"),
      ],
      tagSlugs: ["sports"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-sports-2",
      slug: "womens-football-national-camp",
      categorySlug: "sports",
      titleNe: "महिला फुटबल: राष्ट्रिय शिविर तयारी",
      titleEn: "Women’s football: national camp prep",
      deckNe: "राष्ट्रिय शिविरका लागि खेलाडी छनोट प्रक्रिया चलिरहेको छ।",
      deckEn: "Player selection for the national camp is under way.",
      publishedAt: isoDaysAgo(2, 7),
      updatedAt: isoDaysAgo(2, 7),
      bodyNe: [
        p("फिटनेस परीक्षण र रणनीतिक अभ्यास तालिकामा छ।"),
        p("प्रशिक्षकले रक्षात्मक समन्वय सुधारको लक्ष्य राखेका छन्।"),
        p("नागरिक वाचले शिविर स्थलबाट तयारीको अवस्था हेरेको छ।"),
      ],
      bodyEn: [
        p("Player selection for the national camp is under way."),
        p("फिटनेस परीक्षण र रणनीतिक अभ्यास तालिकामा छ।"),
      ],
      tagSlugs: ["sports"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-sports-3",
      slug: "athletics-school-meet-records",
      categorySlug: "sports",
      titleNe: "विद्यालय एथलेटिक्स: नयाँ कीर्तिमान",
      titleEn: "School athletics: fresh meet records",
      deckNe: "केही विधामा नयाँ कीर्तिमान बनेको आयोजकको दाबी छ।",
      deckEn: "Organisers say several events saw new meet records.",
      publishedAt: isoDaysAgo(3, 8),
      updatedAt: isoDaysAgo(3, 8),
      bodyNe: [
        p("ग्रामीण विद्यालयका खेलाडीको सहभागिता उल्लेखनीय रह्यो।"),
        p("कोचिङ अभाव भने अझै चुनौतीका रूपमा देखियो।"),
        p("नागरिक वाचले पदक तालिका र प्रशिक्षण अवस्था नोट गरेको छ।"),
      ],
      bodyEn: [
        p("Organisers say several events saw new meet records."),
        p("ग्रामीण विद्यालयका खेलाडीको सहभागिता उल्लेखनीय रह्यो।"),
      ],
      tagSlugs: ["sports"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-sports-4",
      slug: "volleyball-provincial-finals",
      categorySlug: "sports",
      titleNe: "भलिबल प्रदेश फाइनल: भीड र उत्साह",
      titleEn: "Provincial volleyball finals: packed stands",
      deckNe: "फाइनल खेलमा दर्शक उपस्थिति उच्च रह्यो।",
      deckEn: "Attendance was high for the provincial finals.",
      publishedAt: isoDaysAgo(4, 9),
      updatedAt: isoDaysAgo(4, 9),
      bodyNe: [
        p("घरेलु टोलीको डिफेन्सले खेलको मोड फेरेको थियो।"),
        p("रेफरी निर्णयमाथि छोटो विवादपछि खेल सामान्य भयो।"),
        p("नागरिक वाच खेल रिपोर्ट मैदानबाटै तयार पारिएको हो।"),
      ],
      bodyEn: [
        p("Attendance was high for the provincial finals."),
        p("घरेलु टोलीको डिफेन्सले खेलको मोड फेरेको थियो।"),
      ],
      tagSlugs: ["sports"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-sports-5",
      slug: "para-sports-funding-gap",
      categorySlug: "sports",
      titleNe: "पारा खेलकुद: बजेट र प्रशिक्षण अन्तराल",
      titleEn: "Para sports: funding and training gaps",
      deckNe: "पारा खेलाडीले नियमित प्रशिक्षण पूर्वाधार मागेका छन्।",
      deckEn: "Para athletes are asking for steadier training infrastructure.",
      publishedAt: isoDaysAgo(5, 10),
      updatedAt: isoDaysAgo(5, 10),
      bodyNe: [
        p("केही संघले प्रायोजन खोज्ने योजना सुनाएका छन्।"),
        p("परिवारको आर्थिक भार अझै उच्च रहेको गुनासो छ।"),
        p("नागरिक वाचले खेलाडी र प्रशिक्षकसँग छुट्टाछुट्टै कुरा गरेको छ।"),
      ],
      bodyEn: [
        p("Para athletes are asking for steadier training infrastructure."),
        p("केही संघले प्रायोजन खोज्ने योजना सुनाएका छन्।"),
      ],
      tagSlugs: ["sports"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-entertainment-1",
      slug: "nepali-film-festival-circuit",
      categorySlug: "entertainment",
      titleNe: "नेपाली चलचित्र: महोत्सव सर्किटको तयारी",
      titleEn: "Nepali film: festival circuit prep",
      deckNe: "स्वतन्त्र फिल्म निर्माता महोत्सव सर्किटमा फोकस गर्दैछन्।",
      deckEn: "Independent filmmakers are focusing on the festival circuit.",
      publishedAt: isoDaysAgo(6, 6),
      updatedAt: isoDaysAgo(6, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("पोस्ट-प्रोडक्सन बजेट अभाव मुख्य चुनौती बनेको छ।"),
        p("दर्शकसँगको संवाद सत्रले प्रतिक्रिया सङ्कलन गर्ने योजना छ।"),
        p("नागरिक वाच मनोरञ्जन डेस्कले निर्माता अनुभव नोट गरेको छ।"),
      ],
      bodyEn: [
        p("Independent filmmakers are focusing on the festival circuit."),
        p("पोस्ट-प्रोडक्सन बजेट अभाव मुख्य चुनौती बनेको छ।"),
      ],
      tagSlugs: ["entertainment"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-entertainment-2",
      slug: "theatre-ticket-revival-city",
      categorySlug: "entertainment",
      titleNe: "नाट्य मञ्च: सहरमा टिकट बिक्रीको पुनरजागरण",
      titleEn: "Theatre tickets: a city revival",
      deckNe: "सप्ताहान्त नाटकका टिकट छिटो सकिएको सञ्चालकको भनाइ छ।",
      deckEn: "Weekend theatre tickets are selling out, organisers say.",
      publishedAt: isoDaysAgo(7, 7),
      updatedAt: isoDaysAgo(7, 7),
      bodyNe: [
        p("युवा दर्शक आकर्षित गर्न छोटो नाटक श्रृंखला चलाइएको छ।"),
        p("टिकट मूल्य र पहुँचबीच सन्तुलन खोज्ने बहस चलिरहेको छ।"),
        p("नागरिक वाचले तीन मञ्चका कार्यक्रम तालिका हेरेको छ।"),
      ],
      bodyEn: [
        p("Weekend theatre tickets are selling out, organisers say."),
        p("युवा दर्शक आकर्षित गर्न छोटो नाटक श्रृंखला चलाइएको छ।"),
      ],
      tagSlugs: ["entertainment"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-entertainment-3",
      slug: "music-studio-indie-release",
      categorySlug: "entertainment",
      titleNe: "इन्डी संगीत: स्टुडियो रिलिज अभ्यास",
      titleEn: "Indie music: studio release habits",
      deckNe: "स्वतन्त्र कलाकारले सानो स्टुडियोबाट रिलिज गर्ने क्रम बढाएका छन्।",
      deckEn: "Independent artists are releasing more often from small studios.",
      publishedAt: isoDaysAgo(8, 8),
      updatedAt: isoDaysAgo(8, 8),
      bodyNe: [
        p("डिस्ट्रीब्युसन प्लेटफर्म चयनमा अधिकार सम्झौता ध्यानमा राखिएको छ।"),
        p("लाइभ प्रदर्शनले आम्दानीको मुख्य स्रोत बनेको कलाकार बताउँछन्।"),
        p("नागरिक वाचले काठमाडौंका दुई स्टुडियो भ्रमण गरेको छ।"),
      ],
      bodyEn: [
        p("Independent artists are releasing more often from small studios."),
        p("डिस्ट्रीब्युसन प्लेटफर्म चयनमा अधिकार सम्झौता ध्यानमा राखिएको छ।"),
      ],
      tagSlugs: ["entertainment"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-entertainment-4",
      slug: "comedy-open-mic-scene",
      categorySlug: "entertainment",
      titleNe: "ओपन माइक: युवा हास्य दृश्य",
      titleEn: "Open mic: the young comedy scene",
      deckNe: "साप्ताहिक ओपन माइकमा नयाँ कलाकारको लहर देखिएको छ।",
      deckEn: "Weekly open mics are drawing a wave of new performers.",
      publishedAt: isoDaysAgo(9, 9),
      updatedAt: isoDaysAgo(9, 9),
      bodyNe: [
        p("विषय चयनमा संवेदनशीलता र स्वतन्त्रताबीच बहस छ।"),
        p("आयोजकले सुरक्षित मञ्च नीति सार्वजनिक गरेका छन्।"),
        p("नागरिक वाचले दर्शक र कलाकार दुवैको अनुभव सङ्कलन गरेको छ।"),
      ],
      bodyEn: [
        p("Weekly open mics are drawing a wave of new performers."),
        p("विषय चयनमा संवेदनशीलता र स्वतन्त्रताबीच बहस छ।"),
      ],
      tagSlugs: ["entertainment"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-entertainment-5",
      slug: "documentary-community-screenings",
      categorySlug: "entertainment",
      titleNe: "डकुमेन्ट्री: सामुदायिक स्क्रिनिङ",
      titleEn: "Documentary: community screenings",
      deckNe: "गाउँ र सहरका सामुदायिक हलमा डकुमेन्ट्री देखाइँदैछ।",
      deckEn: "Documentaries are screening in community halls.",
      publishedAt: isoDaysAgo(10, 10),
      updatedAt: isoDaysAgo(10, 10),
      bodyNe: [
        p("छलफल सत्रले स्थानीय मुद्दा जोड्ने अभ्यास बढेको छ।"),
        p("प्रोजेक्टर र अनुमति प्रक्रिया अझै झन्झटिलो भएको गुनासो छ।"),
        p("नागरिक वाचले दुई स्क्रिनिङमा सहभागी प्रतिक्रिया नोट गरेको छ।"),
      ],
      bodyEn: [
        p("Documentaries are screening in community halls."),
        p("छलफल सत्रले स्थानीय मुद्दा जोड्ने अभ्यास बढेको छ।"),
      ],
      tagSlugs: ["entertainment"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-world-1",
      slug: "himalaya-climate-report-briefing",
      categorySlug: "world",
      titleNe: "हिमाली जलवायु: हिउँ पग्लने दर र तराई जोखिम",
      titleEn: "Himalayan climate: melt rates and Tarai risk",
      deckNe: "हिउँ पग्लने गति र तल्लो तटीय जोखिम फेरि चर्चामा छ।",
      deckEn: "Snowmelt pace and downstream risk are again in focus.",
      publishedAt: isoDaysAgo(11, 6),
      updatedAt: isoDaysAgo(11, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("अध्ययन सारांशले हिमालय तापक्रम वृद्धि औंल्याएको छ।"),
        p("नेपालका नदी प्रणालीमा दीर्घकालीन प्रभाव रहने संकेत छ।"),
        p("नागरिक वाचले वैज्ञानिक स्रोतसहित पाठकलाई सारांश दिन्छ।"),
      ],
      bodyEn: [
        p("Snowmelt pace and downstream risk are again in focus."),
        p("अध्ययन सारांशले हिमालय तापक्रम वृद्धि औंल्याएको छ।"),
      ],
      tagSlugs: ["world"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-world-2",
      slug: "south-asia-trade-corridor-talks",
      categorySlug: "world",
      titleNe: "दक्षिण एसिया व्यापार करिडोर वार्ता",
      titleEn: "South Asia trade corridor talks",
      deckNe: "क्षेत्रीय व्यापार सहज बनाउने वार्ता दोहोरिएको छ।",
      deckEn: "Talks to ease regional trade have resumed.",
      publishedAt: isoDaysAgo(12, 7),
      updatedAt: isoDaysAgo(12, 7),
      bodyNe: [
        p("भन्सार प्रक्रिया र यातायात पूर्वाधार एजेन्डामा छन्।"),
        p("साना निर्यातकर्ताले लागत कटौतीको अपेक्षा राखेका छन्।"),
        p("नागरिक वाच अन्तर्राष्ट्रिय डेस्कले वार्ताका मुख्य बिन्दु नोट गरेको छ।"),
      ],
      bodyEn: [
        p("Talks to ease regional trade have resumed."),
        p("भन्सार प्रक्रिया र यातायात पूर्वाधार एजेन्डामा छन्।"),
      ],
      tagSlugs: ["world"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-world-3",
      slug: "migration-labour-policy-update",
      categorySlug: "world",
      titleNe: "वैदेशिक रोजगार नीति: सुरक्षा मापदण्ड",
      titleEn: "Labour migration policy: safety standards",
      deckNe: "श्रमिक सुरक्षा मापदण्ड कडा बनाउने प्रस्ताव छलफलमा छ।",
      deckEn: "Proposals to tighten worker safety standards are under discussion.",
      publishedAt: isoDaysAgo(13, 8),
      updatedAt: isoDaysAgo(13, 8),
      bodyNe: [
        p("पूर्वप्रस्थान तालिम र बीमा कवरेज विस्तारको कुरा उठेको छ।"),
        p("प्रवासी परिवारले गुनासो सुनुवाइ संयन्त्र मागेका छन्।"),
        p("नागरिक वाचले सम्बन्धित निकायसँग स्पष्टीकरण मागेको छ।"),
      ],
      bodyEn: [
        p("Proposals to tighten worker safety standards are under discussion."),
        p("पूर्वप्रस्थान तालिम र बीमा कवरेज विस्तारको कुरा उठेको छ।"),
      ],
      tagSlugs: ["world"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-world-4",
      slug: "regional-disaster-cooperation",
      categorySlug: "world",
      titleNe: "क्षेत्रीय विपद् सहयोग अभ्यास",
      titleEn: "Regional disaster cooperation drill",
      deckNe: "सीमापार उद्धार समन्वय अभ्यास गरिएको छ।",
      deckEn: "A cross-border rescue coordination drill was held.",
      publishedAt: isoDaysAgo(0, 9),
      updatedAt: isoDaysAgo(0, 9),
      bodyNe: [
        p("सञ्चार प्रोटोकल र उपकरण साझेदारी परीक्षण गरियो।"),
        p("स्थानीय प्रशासनले सूचना प्रवाह सुधार आवश्यक ठानेको छ।"),
        p("नागरिक वाचले अभ्यासस्थलबाट अवलोकन रिपोर्ट तयार पारेको छ।"),
      ],
      bodyEn: [
        p("A cross-border rescue coordination drill was held."),
        p("सञ्चार प्रोटोकल र उपकरण साझेदारी परीक्षण गरियो।"),
      ],
      tagSlugs: ["world"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-world-5",
      slug: "global-food-price-nepal-impact",
      categorySlug: "world",
      titleNe: "विश्व खाद्य मूल्य: नेपालको थोक बजार",
      titleEn: "Global food prices: Nepal wholesale impact",
      deckNe: "अन्तर्राष्ट्रिय मूल्य उतारचढावले थोक बजार प्रभावित छ।",
      deckEn: "Global price swings are feeding into wholesale markets.",
      publishedAt: isoDaysAgo(1, 10),
      updatedAt: isoDaysAgo(1, 10),
      bodyNe: [
        p("आयातकर्ताले ढुवानी लागत मुख्य कारक बताएका छन्।"),
        p("उपभोक्ता मूल्यमा असर ढिलो देखिने विश्लेषकको धारणा छ।"),
        p("नागरिक वाचले काठमाडौं थोक बजारको मूल्य सूची तुलना गरेको छ।"),
      ],
      bodyEn: [
        p("Global price swings are feeding into wholesale markets."),
        p("आयातकर्ताले ढुवानी लागत मुख्य कारक बताएका छन्।"),
      ],
      tagSlugs: ["world"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-opinion-1",
      slug: "editorial-local-government-accountability",
      categorySlug: "opinion",
      titleNe: "सम्पादकीय: स्थानीय सरकारको जवाफदेहिता",
      titleEn: "Editorial: local government accountability",
      deckNe: "वडा बजेट पारदर्शितामाथि प्रश्न बढ्दो छ।",
      deckEn: "Questions about ward budget transparency are growing.",
      publishedAt: isoDaysAgo(2, 6),
      updatedAt: isoDaysAgo(2, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("स्थानीय सरकार नजिकको सरकार हो तर सूचना अपर्याप्त हुँदा विश्वास कमजोर हुन्छ।"),
        p("नागरिक वाचको धारणा: प्रत्येक वडाले त्रैमासिक खर्च सार्वजनिक गर्नुपर्छ।"),
        p("यो सम्पादकीय हो, समाचार रिपोर्ट होइन।"),
      ],
      bodyEn: [
        p("Questions about ward budget transparency are growing."),
        p("स्थानीय सरकार नजिकको सरकार हो तर सूचना अपर्याप्त हुँदा विश्वास कमजोर हुन्छ।"),
      ],
      tagSlugs: ["opinion"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-opinion-2",
      slug: "column-public-transport-dignity",
      categorySlug: "opinion",
      titleNe: "स्तम्भ: सार्वजनिक यातायात र मर्यादा",
      titleEn: "Column: dignity on public transport",
      deckNe: "भीडमा यात्रीको मर्यादा कसरी जोगाउने भन्ने प्रश्न गम्भीर छ।",
      deckEn: "How to protect passenger dignity in crowded transit is a serious question.",
      publishedAt: isoDaysAgo(3, 7),
      updatedAt: isoDaysAgo(3, 7),
      bodyNe: [
        p("महिला र वृद्ध यात्रीको अनुभव नीति बनाउने आधार हुनुपर्छ।"),
        p("सञ्चालक र नगरपालिका दुवैको जिम्मेवारी स्पष्ट हुनुपर्छ।"),
        p("यो लेखकको व्यक्तिगत धारणा हो।"),
      ],
      bodyEn: [
        p("How to protect passenger dignity in crowded transit is a serious question."),
        p("महिला र वृद्ध यात्रीको अनुभव नीति बनाउने आधार हुनुपर्छ।"),
      ],
      tagSlugs: ["opinion"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-opinion-3",
      slug: "essay-digital-rumour-literacy",
      categorySlug: "opinion",
      titleNe: "निबन्ध: डिजिटल हल्ला र साक्षरता",
      titleEn: "Essay: digital rumours and literacy",
      deckNe: "हल्ला छिटो फैलिन्छ, जाँच ढिलो हुन्छ।",
      deckEn: "Rumours travel fast; verification travels slowly.",
      publishedAt: isoDaysAgo(4, 8),
      updatedAt: isoDaysAgo(4, 8),
      bodyNe: [
        p("विद्यालय र समुदायमा मिडिया साक्षरता कक्षा आवश्यक छ।"),
        p("साझा गर्नुअघि स्रोत हेर्ने बानी नागरिक कर्तव्य हो।"),
        p("नागरिक वाच विचार पृष्ठको निमन्त्रणामा लेखिएको।"),
      ],
      bodyEn: [
        p("Rumours travel fast; verification travels slowly."),
        p("विद्यालय र समुदायमा मिडिया साक्षरता कक्षा आवश्यक छ।"),
      ],
      tagSlugs: ["opinion"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-opinion-4",
      slug: "comment-health-worker-respect",
      categorySlug: "opinion",
      titleNe: "टिप्पणी: स्वास्थ्यकर्मीप्रति सम्मान",
      titleEn: "Comment: respect for health workers",
      deckNe: "सेवा प्रवाहमा तनाव बढ्दा सम्मानको संस्कृति कमजोर हुन सक्छ।",
      deckEn: "Stress in service delivery can erode a culture of respect.",
      publishedAt: isoDaysAgo(5, 9),
      updatedAt: isoDaysAgo(5, 9),
      bodyNe: [
        p("सुरक्षित कार्यस्थल नीति कार्यान्वयन अनिवार्य हुनुपर्छ।"),
        p("बिरामी अधिकार र कर्मी सुरक्षा सँगै जानुपर्छ।"),
        p("यो टिप्पणी हो।"),
      ],
      bodyEn: [
        p("Stress in service delivery can erode a culture of respect."),
        p("सुरक्षित कार्यस्थल नीति कार्यान्वयन अनिवार्य हुनुपर्छ।"),
      ],
      tagSlugs: ["opinion"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-opinion-5",
      slug: "view-youth-civic-space",
      categorySlug: "opinion",
      titleNe: "दृष्टिकोण: युवा र नागरिक स्थान",
      titleEn: "View: youth and civic space",
      deckNe: "युवा सहभागितालाई औपचारिकतामा सीमित नराखौं।",
      deckEn: "Do not reduce youth participation to formality.",
      publishedAt: isoDaysAgo(6, 10),
      updatedAt: isoDaysAgo(6, 10),
      bodyNe: [
        p("निर्णय प्रक्रियामा युवा आवाज सुनिनु लोकतन्त्रको परीक्षण हो।"),
        p("स्थानीय तहले युवा परिषद्लाई स्रोत दिनुपर्छ।"),
        p("लेखकको दृष्टिकोण।"),
      ],
      bodyEn: [
        p("Do not reduce youth participation to formality."),
        p("निर्णय प्रक्रियामा युवा आवाज सुनिनु लोकतन्त्रको परीक्षण हो।"),
      ],
      tagSlugs: ["opinion"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-literature-1",
      slug: "new-nepali-poetry-collection",
      categorySlug: "literature",
      titleNe: "नयाँ नेपाली कविता संग्रह: शहरको ध्वनि",
      titleEn: "New Nepali poetry: the city’s sound",
      deckNe: "युवा कविहरूको संग्रहमा शहरको दैनिक ध्वनि घुलिएको छ।",
      deckEn: "A young poets’ collection carries the city’s daily sound.",
      publishedAt: isoDaysAgo(7, 6),
      updatedAt: isoDaysAgo(7, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("सम्पादकले भाषा प्रयोगमा सादगी खोजेको बताए।"),
        p("पाठक छलफल कार्यक्रम पुस्तकालयमा हुनेछ।"),
        p("नागरिक वाच साहित्य डेस्कको समीक्षा नोट।"),
      ],
      bodyEn: [
        p("A young poets’ collection carries the city’s daily sound."),
        p("सम्पादकले भाषा प्रयोगमा सादगी खोजेको बताए।"),
      ],
      tagSlugs: ["literature"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-literature-2",
      slug: "short-story-contest-winners",
      categorySlug: "literature",
      titleNe: "कथा प्रतियोगिता: विजेता घोषणा",
      titleEn: "Short-story contest: winners named",
      deckNe: "राष्ट्रिय कथा प्रतियोगिताका विजेता सार्वजनिक भएका छन्।",
      deckEn: "Winners of a national short-story contest were named.",
      publishedAt: isoDaysAgo(8, 7),
      updatedAt: isoDaysAgo(8, 7),
      bodyNe: [
        p("विषयवस्तुमा गाउँ–सहर सम्बन्ध प्रमुख रह्यो।"),
        p("पुरस्कार राशि साहित्यिक पत्रिकाले व्यवस्था गरेको हो।"),
        p("नागरिक वाचले विजेता कृतिको सारांश मात्र प्रस्तुत गर्छ।"),
      ],
      bodyEn: [
        p("Winners of a national short-story contest were named."),
        p("विषयवस्तुमा गाउँ–सहर सम्बन्ध प्रमुख रह्यो।"),
      ],
      tagSlugs: ["literature"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-literature-3",
      slug: "book-fair-reader-turnout",
      categorySlug: "literature",
      titleNe: "पुस्तक मेला: पाठक उपस्थिति",
      titleEn: "Book fair: reader turnout",
      deckNe: "सप्ताहान्त पुस्तक मेलामा पाठक उपस्थिति सन्तोषजनक रह्यो।",
      deckEn: "Weekend book-fair turnout was encouraging.",
      publishedAt: isoDaysAgo(9, 8),
      updatedAt: isoDaysAgo(9, 8),
      bodyNe: [
        p("बाल साहित्य कुनामा भीड देखियो।"),
        p("स्वतन्त्र प्रकाशकले वितरण चुनौती दोहोर्याए।"),
        p("नागरिक वाच स्थलगत रिपोर्ट।"),
      ],
      bodyEn: [
        p("Weekend book-fair turnout was encouraging."),
        p("बाल साहित्य कुनामा भीड देखियो।"),
      ],
      tagSlugs: ["literature"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-literature-4",
      slug: "translation-workshop-report",
      categorySlug: "literature",
      titleNe: "अनुवाद कार्यशाला: भाषा पुल",
      titleEn: "Translation workshop: building language bridges",
      deckNe: "नेपाली–अंग्रेजी अनुवाद कार्यशाला सम्पन्न भएको छ।",
      deckEn: "A Nepali–English translation workshop concluded.",
      publishedAt: isoDaysAgo(10, 9),
      updatedAt: isoDaysAgo(10, 9),
      bodyNe: [
        p("सहभागीले सन्दर्भ र स्वर जोगाउने अभ्यास गरे।"),
        p("प्रकाशकले गुणस्तरीय अनुवादको माग बढेको बताए।"),
        p("नागरिक वाच साहित्य डेस्क।"),
      ],
      bodyEn: [
        p("A Nepali–English translation workshop concluded."),
        p("सहभागीले सन्दर्भ र स्वर जोगाउने अभ्यास गरे।"),
      ],
      tagSlugs: ["literature"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-literature-5",
      slug: "library-membership-drive",
      categorySlug: "literature",
      titleNe: "पुस्तकालय सदस्यता अभियान",
      titleEn: "Library membership drive",
      deckNe: "सामुदायिक पुस्तकालयले सदस्यता अभियान चलाएका छन्।",
      deckEn: "Community libraries launched a membership drive.",
      publishedAt: isoDaysAgo(11, 10),
      updatedAt: isoDaysAgo(11, 10),
      bodyNe: [
        p("विद्यार्थीलाई छुट शुल्कको व्यवस्था छ।"),
        p("डिजिटल क्याटलग विस्तारको योजना सुनाइएको छ।"),
        p("नागरिक वाचले तीन पुस्तकालयका अनुभव नोट गरेको छ।"),
      ],
      bodyEn: [
        p("Community libraries launched a membership drive."),
        p("विद्यार्थीलाई छुट शुल्कको व्यवस्था छ।"),
      ],
      tagSlugs: ["literature"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-technology-1",
      slug: "digital-public-services-access-gap",
      categorySlug: "technology",
      titleNe: "डिजिटल सेवा: पहुँचको खाडल",
      titleEn: "Digital services: the access gap",
      deckNe: "ई-सेवा शहरमुखी रहँदा गाउँको पहुँच अपूर्ण छ।",
      deckEn: "E-services remain city-heavy while rural access lags.",
      publishedAt: isoDaysAgo(12, 6),
      updatedAt: isoDaysAgo(12, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("ब्यान्डविथ र डिजिटल साक्षरता असमान छ।"),
        p("नागरिक वाचले प्रदेश सेवा केन्द्रको अनुभव सङ्कलन गरेको छ।"),
        p("अफलाइन सहयोग डेस्क विस्तार गर्न सुझाव आएका छन्।"),
      ],
      bodyEn: [
        p("E-services remain city-heavy while rural access lags."),
        p("ब्यान्डविथ र डिजिटल साक्षरता असमान छ।"),
      ],
      tagSlugs: ["technology"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-technology-2",
      slug: "cybersecurity-small-business",
      categorySlug: "technology",
      titleNe: "साना व्यवसाय साइबर सुरक्षा",
      titleEn: "Small-business cybersecurity",
      deckNe: "फिसिङ आक्रमण बढेको साना व्यवसायको गुनासो छ।",
      deckEn: "Small firms report a rise in phishing attacks.",
      publishedAt: isoDaysAgo(13, 7),
      updatedAt: isoDaysAgo(13, 7),
      bodyNe: [
        p("बैंकले दुई तहको प्रमाणीकरण जोड दिएका छन्।"),
        p("तालिम अभाव मुख्य कमजोरी बनेको छ।"),
        p("नागरिक वाच प्रविधि डेस्कको व्यावहारिक चेतावनी।"),
      ],
      bodyEn: [
        p("Small firms report a rise in phishing attacks."),
        p("बैंकले दुई तहको प्रमाणीकरण जोड दिएका छन्।"),
      ],
      tagSlugs: ["technology"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-technology-3",
      slug: "open-data-municipality-portals",
      categorySlug: "technology",
      titleNe: "खुला डेटा: नगर पोर्टल",
      titleEn: "Open data: municipal portals",
      deckNe: "केही नगरले बजेट र परियोजना डेटा खुला गरेका छन्।",
      deckEn: "Some municipalities opened budget and project data.",
      publishedAt: isoDaysAgo(0, 8),
      updatedAt: isoDaysAgo(0, 8),
      bodyNe: [
        p("फाइल ढाँचा एकरूप नहुँदा विश्लेषण गाह्रो छ।"),
        p("नागरिक समूहले एपीआई माग गरेका छन्।"),
        p("नागरिक वाचले पोर्टल उपयोगिता परीक्षण गरेको छ।"),
      ],
      bodyEn: [
        p("Some municipalities opened budget and project data."),
        p("फाइल ढाँचा एकरूप नहुँदा विश्लेषण गाह्रो छ।"),
      ],
      tagSlugs: ["technology"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-technology-4",
      slug: "ai-classroom-pilot-ethics",
      categorySlug: "technology",
      titleNe: "कक्षामा एआई प्रयोग: नैतिक मापदण्ड",
      titleEn: "AI in classrooms: ethics first",
      deckNe: "प्रयोगात्मक कक्षामा एआई उपकरण परीक्षण भइरहेको छ।",
      deckEn: "Classrooms are piloting AI tools experimentally.",
      publishedAt: isoDaysAgo(1, 9),
      updatedAt: isoDaysAgo(1, 9),
      bodyNe: [
        p("गोपनीयता र परीक्षा इमान्दारितामाथि बहस छ।"),
        p("शिक्षक तालिम बिना विस्तार जोखिमपूर्ण हुने धारणा छ।"),
        p("नागरिक वाच शिक्षा–प्रविधि डेस्क।"),
      ],
      bodyEn: [
        p("Classrooms are piloting AI tools experimentally."),
        p("गोपनीयता र परीक्षा इमान्दारितामाथि बहस छ।"),
      ],
      tagSlugs: ["technology"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-technology-5",
      slug: "fintech-wallet-dispute-resolution",
      categorySlug: "technology",
      titleNe: "वालेट विवाद समाधान प्रक्रिया",
      titleEn: "Wallet dispute resolution",
      deckNe: "भुक्तानी विवाद सुनुवाइमा ढिलाइको गुनासो आएको छ।",
      deckEn: "Users report delays in payment-dispute hearings.",
      publishedAt: isoDaysAgo(2, 10),
      updatedAt: isoDaysAgo(2, 10),
      bodyNe: [
        p("सेवा प्रदायकले टिकट प्रणाली सुधारको दाबी गरे।"),
        p("उपभोक्ता अधिकार समूहले समयसीमा मागेका छन्।"),
        p("नागरिक वाचले प्रक्रियाका चरण स्पष्ट पारेको छ।"),
      ],
      bodyEn: [
        p("Users report delays in payment-dispute hearings."),
        p("सेवा प्रदायकले टिकट प्रणाली सुधारको दाबी गरे।"),
      ],
      tagSlugs: ["technology"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-health-1",
      slug: "public-hospital-waiting-lists-update",
      categorySlug: "health",
      titleNe: "सार्वजनिक अस्पताल: प्रतीक्षा सूची",
      titleEn: "Public hospitals: waiting lists",
      deckNe: "विशेषज्ञ सेवाको प्रतीक्षा दबाबमा छ।",
      deckEn: "Specialist waiting lists remain under pressure.",
      publishedAt: isoDaysAgo(3, 6),
      updatedAt: isoDaysAgo(3, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("प्रशासनले शिफ्ट थप्ने योजना सुनाएको छ।"),
        p("औषधि आपूर्तिमा कहिलेकाहीँ अभाव दोहोरिन्छ।"),
        p("नागरिक वाचले बिरामी र स्वास्थ्यकर्मीसँग कुरा गरेको छ।"),
      ],
      bodyEn: [
        p("Specialist waiting lists remain under pressure."),
        p("प्रशासनले शिफ्ट थप्ने योजना सुनाएको छ।"),
      ],
      tagSlugs: ["health"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-health-2",
      slug: "mental-health-helpline-awareness",
      categorySlug: "health",
      titleNe: "मानसिक स्वास्थ्य हेल्पलाइन सचेतना",
      titleEn: "Mental-health helpline awareness",
      deckNe: "हेल्पलाइन नम्बर सार्वजनिक सचेतना अभियानमा जोडिएको छ।",
      deckEn: "Helpline numbers are part of a public awareness push.",
      publishedAt: isoDaysAgo(4, 7),
      updatedAt: isoDaysAgo(4, 7),
      bodyNe: [
        p("गोपनीयता सुनिश्चित गर्ने प्रतिबद्धता दोहोर्याइएको छ।"),
        p("ग्रामीण पहुँच अझै कमजोर रहेको स्वयंसेवी बताउँछन्।"),
        p("नागरिक वाच स्वास्थ्य डेस्क।"),
      ],
      bodyEn: [
        p("Helpline numbers are part of a public awareness push."),
        p("गोपनीयता सुनिश्चित गर्ने प्रतिबद्धता दोहोर्याइएको छ।"),
      ],
      tagSlugs: ["health"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-health-3",
      slug: "maternal-care-rural-clinic",
      categorySlug: "health",
      titleNe: "मातृ स्वास्थ्य: ग्रामीण क्लिनिक",
      titleEn: "Maternal care: rural clinics",
      deckNe: "ग्रामीण क्लिनिकमा प्रसवपूर्व जाँच उपस्थिति बढाउने अभियान चलिरहेको छ।",
      deckEn: "Rural clinics are pushing antenatal visit attendance.",
      publishedAt: isoDaysAgo(5, 8),
      updatedAt: isoDaysAgo(5, 8),
      bodyNe: [
        p("यातायात अभाव मुख्य बाधक बनेको छ।"),
        p("स्वास्थ्यकर्मीले घुम्ती सेवा विस्तार प्रस्ताव गरे।"),
        p("नागरिक वाच स्थलगत रिपोर्ट।"),
      ],
      bodyEn: [
        p("Rural clinics are pushing antenatal visit attendance."),
        p("यातायात अभाव मुख्य बाधक बनेको छ।"),
      ],
      tagSlugs: ["health"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-health-4",
      slug: "air-quality-respiratory-clinic",
      categorySlug: "health",
      titleNe: "वायु गुणस्तर: श्वास रोग क्लिनिक",
      titleEn: "Air quality: respiratory clinics",
      deckNe: "प्रदूषण बढ्दा श्वास रोग क्लिनिकमा चाप देखिएको छ।",
      deckEn: "Respiratory clinics report higher load as pollution rises.",
      publishedAt: isoDaysAgo(6, 9),
      updatedAt: isoDaysAgo(6, 9),
      bodyNe: [
        p("मास्क र घरभित्र वायु शुद्धीकरण सल्लाह दोहोर्याइएको छ।"),
        p("नागरिक वाचले वायु गुणस्तर सूचकांकसँग क्लिनिक उपस्थिति जोडेको छ।"),
        p("जोखिम समूहलाई विशेष सतर्कता आवश्यक छ।"),
      ],
      bodyEn: [
        p("Respiratory clinics report higher load as pollution rises."),
        p("मास्क र घरभित्र वायु शुद्धीकरण सल्लाह दोहोर्याइएको छ।"),
      ],
      tagSlugs: ["health"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-health-5",
      slug: "vaccination-catchup-campaign",
      categorySlug: "health",
      titleNe: "खोप कभरेज: कैच-अप अभियान",
      titleEn: "Vaccination coverage: catch-up drive",
      deckNe: "छुटेका खोप पूरा गराउने अभियान चलाइएको छ।",
      deckEn: "A catch-up drive is completing missed vaccinations.",
      publishedAt: isoDaysAgo(7, 10),
      updatedAt: isoDaysAgo(7, 10),
      bodyNe: [
        p("विद्यालय र स्वास्थ्य चौकी समन्वयमा काम गर्दैछन्।"),
        p("अभिभावक सचेतना सामग्री स्थानीय भाषामा तयार पारिएको छ।"),
        p("नागरिक वाच स्वास्थ्य डेस्क अपडेट।"),
      ],
      bodyEn: [
        p("A catch-up drive is completing missed vaccinations."),
        p("विद्यालय र स्वास्थ्य चौकी समन्वयमा काम गर्दैछन्।"),
      ],
      tagSlugs: ["health"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-education-1",
      slug: "public-school-midday-meal-audit",
      categorySlug: "education",
      titleNe: "दिवा खाजा: सार्वजनिक विद्यालय अडिट",
      titleEn: "Midday meals: public school audit",
      deckNe: "दिवा खाजा गुणस्तर र नियमिततामा अडिट चलिरहेको छ।",
      deckEn: "An audit of midday-meal quality and regularity is under way.",
      publishedAt: isoDaysAgo(8, 6),
      updatedAt: isoDaysAgo(8, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("केही विद्यालयले आपूर्तिकर्ता परिवर्तन गरेका छन्।"),
        p("अभिभावक समितिले मेनु पारदर्शिता मागेका छन्।"),
        p("नागरिक वाच शिक्षा डेस्क।"),
      ],
      bodyEn: [
        p("An audit of midday-meal quality and regularity is under way."),
        p("केही विद्यालयले आपूर्तिकर्ता परिवर्तन गरेका छन्।"),
      ],
      tagSlugs: ["education"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-education-2",
      slug: "teacher-training-digital-skills",
      categorySlug: "education",
      titleNe: "शिक्षक तालिम: डिजिटल सीप",
      titleEn: "Teacher training: digital skills",
      deckNe: "शिक्षक डिजिटल सीप तालिमको दोस्रो चरण सुरु भएको छ।",
      deckEn: "A second phase of teacher digital-skills training has begun.",
      publishedAt: isoDaysAgo(9, 7),
      updatedAt: isoDaysAgo(9, 7),
      bodyNe: [
        p("उपकरण अभाव भएका विद्यालयले साझेदारी ल्याब प्रयोग गर्दैछन्।"),
        p("मूल्यांकन विधिमा सुधार आवश्यक रहेको प्रशिक्षक बताउँछन्।"),
        p("नागरिक वाच रिपोर्ट।"),
      ],
      bodyEn: [
        p("A second phase of teacher digital-skills training has begun."),
        p("उपकरण अभाव भएका विद्यालयले साझेदारी ल्याब प्रयोग गर्दैछन्।"),
      ],
      tagSlugs: ["education"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-education-3",
      slug: "scholarship-application-window",
      categorySlug: "education",
      titleNe: "छात्रवृत्ति आवेदन झ्याल",
      titleEn: "Scholarship application window",
      deckNe: "लक्षित छात्रवृत्तिको आवेदन झ्याल खोलिएको छ।",
      deckEn: "The targeted scholarship application window is open.",
      publishedAt: isoDaysAgo(10, 8),
      updatedAt: isoDaysAgo(10, 8),
      bodyNe: [
        p("कागजात चेकलिस्ट अनलाइन उपलब्ध छ।"),
        p("ग्रामीण विद्यार्थीलाई सहयोग डेस्क राखिएको जनाइएको छ।"),
        p("नागरिक वाचले म्याद र सर्त स्पष्ट पारेको छ।"),
      ],
      bodyEn: [
        p("The targeted scholarship application window is open."),
        p("कागजात चेकलिस्ट अनलाइन उपलब्ध छ।"),
      ],
      tagSlugs: ["education"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-education-4",
      slug: "exam-centre-accessibility",
      categorySlug: "education",
      titleNe: "परीक्षा केन्द्र पहुँच",
      titleEn: "Exam-centre accessibility",
      deckNe: "अपाह्गता भएका परीक्षार्थीका लागि पहुँच सुधार अभियान चलिरहेको छ।",
      deckEn: "An accessibility push for exam centres is under way.",
      publishedAt: isoDaysAgo(11, 9),
      updatedAt: isoDaysAgo(11, 9),
      bodyNe: [
        p("रेम्प र सहायक सामग्रीको सूची अद्यावधिक गरिएको छ।"),
        p("अभिभावकले समयमै जानकारी मागेका छन्।"),
        p("नागरिक वाच शिक्षा डेस्क।"),
      ],
      bodyEn: [
        p("An accessibility push for exam centres is under way."),
        p("रेम्प र सहायक सामग्रीको सूची अद्यावधिक गरिएको छ।"),
      ],
      tagSlugs: ["education"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-education-5",
      slug: "community-learning-centres",
      categorySlug: "education",
      titleNe: "सामुदायिक सिकाइ केन्द्र",
      titleEn: "Community learning centres",
      deckNe: "सामुदायिक सिकाइ केन्द्रले वयस्क साक्षरता कक्षा बढाएका छन्।",
      deckEn: "Community learning centres expanded adult literacy classes.",
      publishedAt: isoDaysAgo(12, 10),
      updatedAt: isoDaysAgo(12, 10),
      bodyNe: [
        p("महिला सहभागिता उच्च रहेको सहजकर्ता बताउँछन्।"),
        p("बजेट निरन्तरता मुख्य चिन्ता हो।"),
        p("नागरिक वाच स्थलगत नोट।"),
      ],
      bodyEn: [
        p("Community learning centres expanded adult literacy classes."),
        p("महिला सहभागिता उच्च रहेको सहजकर्ता बताउँछन्।"),
      ],
      tagSlugs: ["education"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-interview-1",
      slug: "interview-city-planner-walkability",
      categorySlug: "interview",
      titleNe: "अन्तर्वार्ता: सहरी योजनाकारसँग पैदल मार्ग",
      titleEn: "Interview: a city planner on walkability",
      deckNe: "पैदल मार्ग सुरक्षा सुधार प्राथमिकतामा रहेको योजनाकार बताउँछन्।",
      deckEn: "Walkability safety is a priority, the planner says.",
      publishedAt: isoDaysAgo(13, 6),
      updatedAt: isoDaysAgo(13, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("साइकल लेन र जेब्रा क्रसिङ समन्वय आवश्यक छ।"),
        p("बजेट बाँडफाँटमा पारदर्शिता महत्वपूर्ण हुने धारणा छ।"),
        p("नागरिक वाचसँगको कुराकानीमा आधारित।"),
      ],
      bodyEn: [
        p("Walkability safety is a priority, the planner says."),
        p("साइकल लेन र जेब्रा क्रसिङ समन्वय आवश्यक छ।"),
      ],
      tagSlugs: ["interview"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-interview-2",
      slug: "interview-nurse-night-shift",
      categorySlug: "interview",
      titleNe: "अन्तर्वार्ता: रात्रि शिफ्ट नर्सासँग",
      titleEn: "Interview: a nurse on night shifts",
      deckNe: "रात्रि शिफ्टमा जनशक्ति व्यवस्थापन चुनौतीपूर्ण रहेको नर्स बताउँछिन्।",
      deckEn: "Night-shift staffing remains tough, the nurse says.",
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      bodyNe: [
        p("बिरामी सुरक्षा प्रोटोकल नियमित अभ्यास गरिन्छ।"),
        p("थकान व्यवस्थापन नीति स्पष्ट हुनुपर्ने माग छ।"),
        p("नागरिक वाच स्वास्थ्य अन्तर्वार्ता।"),
      ],
      bodyEn: [
        p("Night-shift staffing remains tough, the nurse says."),
        p("बिरामी सुरक्षा प्रोटोकल नियमित अभ्यास गरिन्छ।"),
      ],
      tagSlugs: ["interview"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-interview-3",
      slug: "interview-startup-founder-payroll",
      categorySlug: "interview",
      titleNe: "अन्तर्वार्ता: स्टार्टअप संस्थापकसँग पेरोल",
      titleEn: "Interview: a startup founder on payroll",
      deckNe: "पेरोल अनुशासनले विश्वास जोगाउने संस्थापकको भनाइ छ।",
      deckEn: "Payroll discipline protects trust, the founder says.",
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      bodyNe: [
        p("नगद प्रवाह योजना बिना विस्तार जोखिमपूर्ण हुन्छ।"),
        p("लगानीकर्ताले शासन संरचना हेर्ने गरेका छन्।"),
        p("नागरिक वाच बजार अन्तर्वार्ता।"),
      ],
      bodyEn: [
        p("Payroll discipline protects trust, the founder says."),
        p("नगद प्रवाह योजना बिना विस्तार जोखिमपूर्ण हुन्छ।"),
      ],
      tagSlugs: ["interview"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-interview-4",
      slug: "interview-farmer-cooperative",
      categorySlug: "interview",
      titleNe: "अन्तर्वार्ता: किसान सहकारीसँग",
      titleEn: "Interview: a farmers’ cooperative",
      deckNe: "सहकारीले बजार पहुँच सुधारेको किसान प्रतिनिधिको दाबी छ।",
      deckEn: "The cooperative improved market access, a farmer rep says.",
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      bodyNe: [
        p("मूल्य उतारचढाव अझै चुनौती हो।"),
        p("युवा सदस्यता बढाउने अभियान चलिरहेको छ।"),
        p("नागरिक वाच अन्तर्वार्ता।"),
      ],
      bodyEn: [
        p("The cooperative improved market access, a farmer rep says."),
        p("मूल्य उतारचढाव अझै चुनौती हो।"),
      ],
      tagSlugs: ["interview"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-interview-5",
      slug: "interview-youth-climate-volunteer",
      categorySlug: "interview",
      titleNe: "अन्तर्वार्ता: जलवायु स्वयंसेवीसँग",
      titleEn: "Interview: a climate volunteer",
      deckNe: "स्थानीय वृक्षारोपणले मात्र पुग्दैन भन्ने स्वयंसेवीको धारणा छ।",
      deckEn: "Tree planting alone is not enough, the volunteer says.",
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      bodyNe: [
        p("नीति निगरानी र डेटा सार्वजनिक हुनुपर्छ।"),
        p("विद्यालय क्लबले निरन्तरता दिने योजना छ।"),
        p("नागरिक वाच अन्तर्वार्ता।"),
      ],
      bodyEn: [
        p("Tree planting alone is not enough, the volunteer says."),
        p("नीति निगरानी र डेटा सार्वजनिक हुनुपर्छ।"),
      ],
      tagSlugs: ["interview"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-photostory-1",
      slug: "photo-monsoon-workers-drain",
      categorySlug: "photo-story",
      titleNe: "फोटो फिचर: मनसुनअघि नाली मजदुर",
      titleEn: "Photo feature: drain workers before monsoon",
      deckNe: "नाली सफाइ मजदुरको दैनिकी फोटोमा।",
      deckEn: "A photo look at drain workers’ daily labour.",
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("बिहानैदेखि टोलीले ढल र नाली खाली गर्छ।"),
        p("सुरक्षा सामग्री अपर्याप्त हुँदा जोखिम बढ्छ।"),
        p("नागरिक वाच फोटो डेस्क।"),
      ],
      bodyEn: [
        p("A photo look at drain workers’ daily labour."),
        p("बिहानैदेखि टोलीले ढल र नाली खाली गर्छ।"),
      ],
      tagSlugs: ["photo-story"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-photostory-2",
      slug: "photo-harvest-morning-tarai",
      categorySlug: "photo-story",
      titleNe: "फोटो फिचर: तराईको बिहानी फसल",
      titleEn: "Photo feature: Tarai harvest morning",
      deckNe: "फसल भित्र्याउने बिहानको दृश्य।",
      deckEn: "Morning scenes from the harvest.",
      publishedAt: isoDaysAgo(5, 7),
      updatedAt: isoDaysAgo(5, 7),
      bodyNe: [
        p("परिवार मिलेर काम गर्ने दृश्य दोहोरिन्छ।"),
        p("मौसम परिवर्तनले समयतालिका हल्लाएको किसान बताउँछन्।"),
        p("नागरिक वाच फोटो फिचर।"),
      ],
      bodyEn: [
        p("Morning scenes from the harvest."),
        p("परिवार मिलेर काम गर्ने दृश्य दोहोरिन्छ।"),
      ],
      tagSlugs: ["photo-story"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-photostory-3",
      slug: "photo-school-assembly-flag",
      categorySlug: "photo-story",
      titleNe: "फोटो फिचर: विद्यालय प्रार्थना सभा",
      titleEn: "Photo feature: school morning assembly",
      deckNe: "प्रार्थना सभाको अनुशासन र उत्साह।",
      deckEn: "Discipline and energy at morning assembly.",
      publishedAt: isoDaysAgo(6, 8),
      updatedAt: isoDaysAgo(6, 8),
      bodyNe: [
        p("झाण्डा र राष्ट्रगानका दृश्य केन्द्रमा छन्।"),
        p("शिक्षकले सहभागिता समान बनाउने प्रयास गर्छन्।"),
        p("नागरिक वाच शिक्षा फोटो।"),
      ],
      bodyEn: [
        p("Discipline and energy at morning assembly."),
        p("झाण्डा र राष्ट्रगानका दृश्य केन्द्रमा छन्।"),
      ],
      tagSlugs: ["photo-story"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-photostory-4",
      slug: "photo-market-evening-rush",
      categorySlug: "photo-story",
      titleNe: "फोटो फिचर: साँझ बजार भीड",
      titleEn: "Photo feature: evening market rush",
      deckNe: "साँझको तरकारी बजार भीड।",
      deckEn: "The evening vegetable market rush.",
      publishedAt: isoDaysAgo(7, 9),
      updatedAt: isoDaysAgo(7, 9),
      bodyNe: [
        p("मूल्य सोधपुछ र छिटो कारोबार देखिन्छ।"),
        p("साना विक्रेताको स्थान सुरक्षित राख्ने बहस छ।"),
        p("नागरिक वाच फोटो डेस्क।"),
      ],
      bodyEn: [
        p("The evening vegetable market rush."),
        p("मूल्य सोधपुछ र छिटो कारोबार देखिन्छ।"),
      ],
      tagSlugs: ["photo-story"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-photostory-5",
      slug: "photo-bus-park-porters",
      categorySlug: "photo-story",
      titleNe: "फोटो फिचर: बसपार्कका भरिया",
      titleEn: "Photo feature: bus-park porters",
      deckNe: "भरियाको श्रम र प्रतीक्षा।",
      deckEn: "Labour and waiting at the bus park.",
      publishedAt: isoDaysAgo(8, 10),
      updatedAt: isoDaysAgo(8, 10),
      bodyNe: [
        p("भारी बोक्ने क्रममा सुरक्षा जोखिम देखिन्छ।"),
        p("परिचयपत्र र दर सूची माग उठेको छ।"),
        p("नागरिक वाच फोटो फिचर।"),
      ],
      bodyEn: [
        p("Labour and waiting at the bus park."),
        p("भारी बोक्ने क्रममा सुरक्षा जोखिम देखिन्छ।"),
      ],
      tagSlugs: ["photo-story"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-video-1",
      slug: "video-explain-budget-local",
      categorySlug: "video",
      titleNe: "भिडियो: स्थानीय बजेट बुझ्ने",
      titleEn: "Video: understanding a local budget",
      deckNe: "वडा बजेटका मुख्य शीर्षक सरल भाषामा।",
      deckEn: "Ward budget lines explained in plain language.",
      publishedAt: isoDaysAgo(9, 6),
      updatedAt: isoDaysAgo(9, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("राजस्व र खर्चबीचको अन्तराल देखाउँछ।"),
        p("पाठक प्रश्नका लागि फारम लिंक दिइएको छ।"),
        p("नागरिक वाच भिडियो डेस्क।"),
      ],
      bodyEn: [
        p("Ward budget lines explained in plain language."),
        p("राजस्व र खर्चबीचको अन्तराल देखाउँछ।"),
      ],
      tagSlugs: ["video"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-video-2",
      slug: "video-how-to-file-rti",
      categorySlug: "video",
      titleNe: "भिडियो: सूचनाको हक कसरी माग्ने",
      titleEn: "Video: how to file an RTI request",
      deckNe: "सूचना माग प्रक्रिया चरणबद्ध।",
      deckEn: "A step-by-step right-to-information request.",
      publishedAt: isoDaysAgo(10, 7),
      updatedAt: isoDaysAgo(10, 7),
      bodyNe: [
        p("फारम भर्ने र निवेदन दर्ताका उदाहरण।"),
        p("समयसीमा र पुनरावेदन बाटो स्पष्ट पारिएको छ।"),
        p("नागरिक वाच गाइड भिडियो।"),
      ],
      bodyEn: [
        p("A step-by-step right-to-information request."),
        p("फारम भर्ने र निवेदन दर्ताका उदाहरण।"),
      ],
      tagSlugs: ["video"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-video-3",
      slug: "video-first-aid-monsoon",
      categorySlug: "video",
      titleNe: "भिडियो: मनसुन प्राथमिक उपचार",
      titleEn: "Video: monsoon first aid basics",
      deckNe: "बाढी–पहिरो अवस्थामा प्राथमिक उपचार।",
      deckEn: "Basic first aid for flood and landslide contexts.",
      publishedAt: isoDaysAgo(11, 8),
      updatedAt: isoDaysAgo(11, 8),
      bodyNe: [
        p("सुरक्षित स्थान र आपत्कालीन सम्पर्क जोड।"),
        p("स्वास्थ्यकर्मी सल्लाहमा आधारित।"),
        p("नागरिक वाच स्वास्थ्य भिडियो।"),
      ],
      bodyEn: [
        p("Basic first aid for flood and landslide contexts."),
        p("सुरक्षित स्थान र आपत्कालीन सम्पर्क जोड।"),
      ],
      tagSlugs: ["video"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-video-4",
      slug: "video-vote-count-explained",
      categorySlug: "video",
      titleNe: "भिडियो: मतगणना प्रक्रिया",
      titleEn: "Video: how vote counting works",
      deckNe: "मतगणना कक्षका नियम सरल व्याख्या।",
      deckEn: "Counting-room rules explained simply.",
      publishedAt: isoDaysAgo(12, 9),
      updatedAt: isoDaysAgo(12, 9),
      bodyNe: [
        p("अवलोकनकर्ता भूमिका र विवाद समाधान।"),
        p("आधिकारिक प्रक्रियासँग मेल खाने गरी तयार।"),
        p("नागरिक वाच निर्वाचन भिडियो।"),
      ],
      bodyEn: [
        p("Counting-room rules explained simply."),
        p("अवलोकनकर्ता भूमिका र विवाद समाधान।"),
      ],
      tagSlugs: ["video"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-video-5",
      slug: "video-save-water-home",
      categorySlug: "video",
      titleNe: "भिडियो: घरमा पानी बचत",
      titleEn: "Video: saving water at home",
      deckNe: "घरभित्र पानी बचतका व्यावहारिक उपाय।",
      deckEn: "Practical water-saving steps at home.",
      publishedAt: isoDaysAgo(13, 10),
      updatedAt: isoDaysAgo(13, 10),
      bodyNe: [
        p("चुहावट जाँच र पुनःप्रयोग सुझाव।"),
        p("मनसुनअघि तयारीसँग जोडिएको।"),
        p("नागरिक वाच उपयोगी भिडियो।"),
      ],
      bodyEn: [
        p("Practical water-saving steps at home."),
        p("चुहावट जाँच र पुनःप्रयोग सुझाव।"),
      ],
      tagSlugs: ["video"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-diaspora-1",
      slug: "diaspora-remittance-family-plan",
      categorySlug: "diaspora",
      titleNe: "प्रवास: विप्रेषण र पारिवारिक योजना",
      titleEn: "Diaspora: remittance and family planning",
      deckNe: "विप्रेषणलाई शिक्षा र स्वास्थ्यमा प्राथमिकता दिने परिवार बढ्दै।",
      deckEn: "More families prioritise remittances for education and health.",
      publishedAt: isoDaysAgo(0, 6),
      updatedAt: isoDaysAgo(0, 6),
      isFeatured: "secondary",
      bodyNe: [
        p("लगानी जोखिमबारे सल्लाह माग्ने क्रम बढेको छ।"),
        p("प्रवासी संजालले वित्तीय साक्षरता सत्र चलाएका छन्।"),
        p("नागरिक वाच प्रवास डेस्क।"),
      ],
      bodyEn: [
        p("More families prioritise remittances for education and health."),
        p("लगानी जोखिमबारे सल्लाह माग्ने क्रम बढेको छ।"),
      ],
      tagSlugs: ["diaspora"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-diaspora-2",
      slug: "diaspora-festival-community-hall",
      categorySlug: "diaspora",
      titleNe: "प्रवास: सामुदायिक पर्व आयोजना",
      titleEn: "Diaspora: community festival halls",
      deckNe: "प्रवासी समुदायले पर्वलाई एकताको अवसर बनाएका छन्।",
      deckEn: "Diaspora communities treat festivals as unity moments.",
      publishedAt: isoDaysAgo(1, 7),
      updatedAt: isoDaysAgo(1, 7),
      bodyNe: [
        p("नयाँ पुस्तालाई भाषा कक्षा जोड्ने अभ्यास छ।"),
        p("स्थानीय नियम पालनामा आयोजक सतर्क छन्।"),
        p("नागरिक वाच प्रवास रिपोर्ट।"),
      ],
      bodyEn: [
        p("Diaspora communities treat festivals as unity moments."),
        p("नयाँ पुस्तालाई भाषा कक्षा जोड्ने अभ्यास छ।"),
      ],
      tagSlugs: ["diaspora"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-diaspora-3",
      slug: "diaspora-skill-returnee-startup",
      categorySlug: "diaspora",
      titleNe: "प्रवास: फर्केर उद्यम",
      titleEn: "Diaspora: returnee startups",
      deckNe: "सीप लिएर फर्केका उद्यमीले साना व्यवसाय खोलेका छन्।",
      deckEn: "Returnees with skills are opening small businesses.",
      publishedAt: isoDaysAgo(2, 8),
      updatedAt: isoDaysAgo(2, 8),
      bodyNe: [
        p("पुँजी र बजार पहुँच अझै चुनौती हो।"),
        p("स्थानीय तहले सहुलियत कर्जा प्याकेजको चर्चा गरेको छ।"),
        p("नागरिक वाच प्रवास–बजार डेस्क।"),
      ],
      bodyEn: [
        p("Returnees with skills are opening small businesses."),
        p("पुँजी र बजार पहुँच अझै चुनौती हो।"),
      ],
      tagSlugs: ["diaspora"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-diaspora-4",
      slug: "diaspora-voting-registration-help",
      categorySlug: "diaspora",
      titleNe: "प्रवास: मतदाता दर्ता सहयोग",
      titleEn: "Diaspora: voter registration help",
      deckNe: "प्रवासी मतदाता दर्ता सहयोग डेस्क सक्रिय छ।",
      deckEn: "Diaspora voter-registration help desks are active.",
      publishedAt: isoDaysAgo(3, 9),
      updatedAt: isoDaysAgo(3, 9),
      bodyNe: [
        p("कागजात अभाव मुख्य बाधक बनेको छ।"),
        p("अनलाइन मार्गदर्शन सामग्री अद्यावधिक गरिएको जनाइएको छ।"),
        p("नागरिक वाच प्रवास डेस्क।"),
      ],
      bodyEn: [
        p("Diaspora voter-registration help desks are active."),
        p("कागजात अभाव मुख्य बाधक बनेको छ।"),
      ],
      tagSlugs: ["diaspora"],
      reportingLocation: 'काठमाडौं',
    }),
    base({
      id: "art-nw-diaspora-5",
      slug: "diaspora-student-housing-watch",
      categorySlug: "diaspora",
      titleNe: "प्रवास: विद्यार्थी आवास",
      titleEn: "Diaspora: student housing",
      deckNe: "विद्यार्थी आवास भाडा र सुरक्षा चासोमा छ।",
      deckEn: "Student housing rents and safety are in focus.",
      publishedAt: isoDaysAgo(4, 10),
      updatedAt: isoDaysAgo(4, 10),
      bodyNe: [
        p("संघसंस्थाले गुनासो सुनुवाइ संयन्त्र प्रस्ताव गरेका छन्।"),
        p("अभिभावक समूहले पारदर्शी करार मागेका छन्।"),
        p("नागरिक वाच प्रवास रिपोर्ट।"),
      ],
      bodyEn: [
        p("Student housing rents and safety are in focus."),
        p("संघसंस्थाले गुनासो सुनुवाइ संयन्त्र प्रस्ताव गरेका छन्।"),
      ],
      tagSlugs: ["diaspora"],
      reportingLocation: 'काठमाडौं',
    }),
  ]
}
