export const newsroomRoles = [
  'Super Admin',
  'Publisher/Owner',
  'Editor-in-Chief',
  'Managing Editor',
  'Section Editor',
  'Province Editor',
  'Journalist/Reporter',
  'Contributor',
  'Fact Checker',
  'Copy Editor',
  'Photo/Video Editor',
  'Moderator',
  'Ad Manager',
  'SEO Manager',
  'Analyst',
  'Reader/User',
] as const

export const editorialWorkflow = [
  'Idea',
  'Assigned',
  'Draft',
  'Submitted',
  'Fact Check',
  'Copy Edit',
  'SEO Review',
  'Legal/Sensitivity Review',
  'Scheduled',
  'Published',
  'Updated',
  'Archived',
] as const

export const permissions = [
  'create article',
  'edit own article',
  'edit all articles',
  'submit article',
  'approve article',
  'publish',
  'unpublish',
  'schedule',
  'delete',
  'manage users',
  'manage roles',
  'moderate comments',
  'manage ads',
  'manage live widgets',
  'manage SEO',
  'manage settings',
  'view analytics',
  'manage reader submissions',
  'manage polls',
  'manage newsletter',
] as const

export const adminSections = [
  ['Dashboard', '/admin/dashboard'],
  ['Articles', '/admin/articles'],
  ['New Article', '/admin/articles/new'],
  ['Media', '/admin/media'],
  ['Categories', '/admin/categories'],
  ['Tags', '/admin/tags'],
  ['Topics', '/admin/topics'],
  ['Provinces', '/admin/provinces'],
  ['Authors', '/admin/authors'],
  ['Users', '/admin/users'],
  ['Roles', '/admin/roles'],
  ['Comments', '/admin/comments'],
  ['Submissions', '/admin/submissions'],
  ['Polls', '/admin/polls'],
  ['Live Blogs', '/admin/live-blogs'],
  ['Live Widgets', '/admin/live-widgets'],
  ['Ads', '/admin/ads'],
  ['Newsletter', '/admin/newsletter'],
  ['SEO', '/admin/seo'],
  ['Settings', '/admin/settings'],
  ['Audit Log', '/admin/audit-log'],
] as const

export const authEnvironment = [
  'DATABASE_URL',
  'AUTH_SECRET',
  'BETTER_AUTH_SECRET',
  'BETTER_AUTH_URL',
] as const
