import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionDiaspora(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-diaspora-1',
      slug: 'gulf-labour-rights-briefing',
      categorySlug: 'diaspora',
      titleNe: 'खाडी श्रम अधिकार ब्रिफिङ: जान्नुपर्ने आधार',
      titleEn: 'Gulf labour rights briefing: basics to know',
      deckNe: 'करार, पासपोर्ट नियन्त्रण र उजुरी मार्गबारे स्पष्ट जानकारी जीवनरक्षा हो।',
      deckEn: 'Clear knowledge of contracts, passport control and complaint routes is life protection.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["labour-migration"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाच प्रवास डेस्कले कामदार परिवारका लागि आधारभूत अधिकार सार तयार पारेको छ।'),
        p('दलाल प्रलोभनबाट बच्ने उपाय समेटिएको छ।'),
        p('महिला कामदारका लागि थप सावधानी छन्।'),
        p('नेपाल फर्किएपछि सीप उपयोग योजना पनि चाहिन्छ।'),
        h2('जानकारी सूची'),
        list([
          'कानुनी करार',
          'बीमा',
          'हेल्पलाइन',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Clear knowledge of contracts, passport control and complaint routes is life protection.'),
      ],
    }),
    base({
      id: 'art-ed-diaspora-2',
      slug: 'japan-trainee-workers-path',
      categorySlug: 'diaspora',
      titleNe: 'जापान तालिम कामदार मार्ग: अपेक्षा र वास्तविकता',
      titleEn: 'Japan trainee worker path: expectations vs reality',
      deckNe: 'भाषा र सीप तयारीबिना जाने बाटो जोखिमपूर्ण हुन्छ।',
      deckEn: 'Leaving without language and skills prep is risky.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाच डेस्कले तालिम मार्गबारे भ्रम तोड्ने प्रयास गरेको छ।'),
        p('शुल्क पारदर्शिता अनिवार्य छ।'),
        p('कार्यस्थल दुर्घटना बीमा बुझ्नुपर्छ।'),
        p('फिर्तापछि रोजगारी योजना सुरुमै बनाउनुहोस्।'),
        h2('तयारी कदम'),
        list([
          'भाषा कक्षा',
          'करार बुझाइ',
          'पारिवारिक योजना',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Leaving without language and skills prep is risky.'),
      ],
    }),
    base({
      id: 'art-ed-diaspora-3',
      slug: 'remittance-family-budgets',
      categorySlug: 'diaspora',
      titleNe: 'विप्रेषण र पारिवारिक बजेट: दीगो व्यवस्था',
      titleEn: 'Remittance and family budgets for sustainability',
      deckNe: 'आम्दानी अनिश्चित हुँदा खर्च प्राथमिकता र बचत नियम चाहिन्छ।',
      deckEn: 'When income is uncertain, spending priorities and saving rules matter.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["data-story"],
      reportingLocation: 'मोरङ',
      bodyNe: [
        p('विप्रेषणले घर चल्छ तर योजनाबिना सकिन्छ। नागरिक वाच डेस्क व्यवहारिक बजेट कुराकानी गर्छ।'),
        p('देखाउने खर्चले दबाब बढाउँछ।'),
        p('महिला निर्णायक भूमिकामा हुँदा बचत बलियो हुने उदाहरण छन्।'),
        p('वित्तीय साक्षरता कक्षा गाउँमै पुर्‍याउनुपर्छ।'),
        h2('बजेट सुझाव'),
        list([
          'आकस्मिक कोष',
          'ऋण सावधानी',
          'शिक्षा लगानी',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('When income is uncertain, spending priorities and saving rules matter.'),
      ],
    }),
    base({
      id: 'art-ed-diaspora-4',
      slug: 'student-visa-preparation-checklist',
      categorySlug: 'diaspora',
      titleNe: 'विद्यार्थी भिसा तयारी चेकलिस्ट',
      titleEn: 'Student visa preparation checklist',
      deckNe: 'कागजात, खर्च योजना र मानसिक तयारी तीनै चाहिन्छ।',
      deckEn: 'Documents, cost plans and mental preparation all matter.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('विदेश अध्ययन सपना हो। नागरिक वाच डेस्क ठगी जोखिमबारे सतर्क गराउँछ।'),
        p('भाषा तयारीले सफलता बढाउँछ।'),
        p('पारिवारिक ऋणको दबाब खुला छलफल हुनुपर्छ।'),
        p('फर्केर योगदान गर्ने योजना पनि सोचनीय छ।'),
        h2('चेकलिस्ट'),
        list([
          'आधिकारिक स्रोत',
          'छात्रवृत्ति खोज',
          'ठगी कन्सल्टेन्सीबाट बच्ने',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Documents, cost plans and mental preparation all matter.'),
      ],
    }),
    base({
      id: 'art-ed-diaspora-5',
      slug: 'cultural-associations-abroad',
      categorySlug: 'diaspora',
      titleNe: 'प्रवासी साँस्कृतिक संघ: पहिचान र सहयोग',
      titleEn: 'Cultural associations abroad: identity and mutual aid',
      deckNe: 'चाडपर्व मात्र होइन, संकट सहयोग र नयाँ आएका सदस्य अभिमुखीकरण पनि संघको काम हो।',
      deckEn: 'Beyond festivals, associations orient newcomers and help in crises.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('साँस्कृतिक संघ प्रवासको घरजस्तो हुन्छ। नागरिक वाच डेस्कले सुशासन अभ्यास साझा गर्छ।'),
        p('राजनीतिक विभाजनले सहयोग कमजोर पार्न सक्छ।'),
        p('नेपाली भाषा कक्षा बालबालिकाका लागि उपयोगी छ।'),
        p('नेपालसँग ज्ञान आदानप्रदान सम्भावना छ।'),
        h2('राम्रो अभ्यास'),
        list([
          'पारदर्शी लेखा',
          'युवा समावेश',
          'महिला समिति',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Beyond festivals, associations orient newcomers and help in crises.'),
      ],
    })
  ]
}
