import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionEducation(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-education-1',
      slug: 'see-grade12-result-culture',
      categorySlug: 'education',
      titleNe: 'परीक्षा नतिजा संस्कृति: अंकभन्दा सिकाइ',
      titleEn: 'Exam result culture: learning beyond marks',
      deckNe: 'नतिजा आएपछिको दबाब व्यवस्थापन र मार्गदर्शन उत्तिकै महत्त्वपूर्ण छ।',
      deckEn: 'After results, pressure management and guidance matter as much as scores.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('परीक्षा नतिजा संवेदनशील समय हो। नागरिक वाच शिक्षा डेस्कले बालबालिकाको गरिमा जोगाउन आग्रह गर्छ।'),
        p('असफलता अन्त्य होइन।'),
        p('क्यारियर परामर्श विद्यालयमै चाहिन्छ।'),
        p('डिजिटल नतिजा पहुँच समान होस्।'),
        h2('अभिभावक भूमिका'),
        list([
          'तुलना कम गर्ने',
          'वैकल्पिक मार्ग खुला राख्ने',
          'मानसिक सहयोग',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('After results, pressure management and guidance matter as much as scores.'),
      ],
    }),
    base({
      id: 'art-ed-education-2',
      slug: 'teacher-shortage-hills',
      categorySlug: 'education',
      titleNe: 'पहाडी शिक्षक अभाव: कक्षा कोठाको वास्तविकता',
      titleEn: 'Teacher shortages in the hills',
      deckNe: 'विषयगत शिक्षक नहुँदा सिकाइ अधुरो हुन्छ। प्रोत्साहन र आवास योजना चाहिन्छ।',
      deckEn: 'Missing subject teachers leave learning incomplete; incentives and housing help.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'बागलुङ',
      bodyNe: [
        p('शिक्षक अभाव संख्या मात्र होइन गुणस्तर संकट हो। नागरिक वाच डेस्कले कक्षा अनुभव रेकर्ड गर्छ।'),
        p('महिला शिक्षक सुरक्षा र आवास निर्णायक हुन्छ।'),
        p('प्रविधिले सहयोग गर्न सक्छ तर प्रतिस्थापन होइन।'),
        p('समुदाय अनुगमन रचनात्मक होस्।'),
        h2('नीति औजार'),
        list([
          'दुर्गम भत्ता',
          'स्थानीय करार मापदण्ड',
          'बहुविषय तालिम',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Missing subject teachers leave learning incomplete; incentives and housing help.'),
      ],
    }),
    base({
      id: 'art-ed-education-3',
      slug: 'digital-classrooms-equity',
      categorySlug: 'education',
      titleNe: 'डिजिटल कक्षा: समानता बिना अधुरो',
      titleEn: 'Digital classrooms incomplete without equity',
      deckNe: 'ल्यापटप वितरण मात्र पर्याप्त होइन। कनेक्टिभिटी, तालिम र सामग्री चाहिन्छ।',
      deckEn: 'Devices alone are not enough without connectivity, training and content.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["data-story"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('डिजिटल शिक्षा सम्भावनाशील छ। नागरिक वाच डेस्क असमान पहुँच चिन्ता गर्छ।'),
        p('ग्रामीण विद्यालय छायामा पर्नु हुँदैन।'),
        p('अभिभावक खर्च बढाउने मोडल दिगो होइन।'),
        p('खुला शैक्षिक स्रोत उपयोगी छन्।'),
        h2('समानता जाँच'),
        list([
          'बिजुली',
          'शिक्षक तालिम',
          'अफलाइन सामग्री',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Devices alone are not enough without connectivity, training and content.'),
      ],
    }),
    base({
      id: 'art-ed-education-4',
      slug: 'scholarship-access-clarity',
      categorySlug: 'education',
      titleNe: 'छात्रवृत्ति पहुँच: जानकारी नै पहिलो सिँढी',
      titleEn: 'Scholarship access starts with clear information',
      deckNe: 'योग्य विद्यार्थीले अवसर नदेख्ने अवस्था अन्त्य गर्न एकद्वार सूचना चाहिन्छ।',
      deckEn: 'A single information window stops eligible students missing opportunities.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["budget-2083"],
      reportingLocation: 'धनुषा',
      bodyNe: [
        p('छात्रवृत्ति समानताको औजार हो। नागरिक वाच डेस्क जटिल प्रक्रियाले बाहिर पार्ने जोखिम देखाउँछ।'),
        p('दलित, महिला र अपाङ्गता कोटा कार्यान्वयन मापनयोग्य होस्।'),
        p('स्कुल स्तरमा अभिमुखीकरण गर्नुपर्छ।'),
        p('ठगी विज्ञापनबारे सतर्कता जरुरी छ।'),
        h2('सुधार'),
        list([
          'सरल आवेदन',
          'समयतालिका',
          'सहयोग डेस्क',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('A single information window stops eligible students missing opportunities.'),
      ],
    }),
    base({
      id: 'art-ed-education-5',
      slug: 'monsoon-school-closures-plan',
      categorySlug: 'education',
      titleNe: 'मनसुन विद्यालय बन्द: सिकाइ निरन्तरता योजना',
      titleEn: 'Monsoon school closures need continuity plans',
      deckNe: 'बन्द अपरिहार्य हुँदा गृहकार्य प्याक र वैकल्पिक स्थानले क्षति घटाउँछ।',
      deckEn: 'When closures are needed, homework packs and alternate sites reduce loss.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["climate"],
      reportingLocation: 'सिन्धुली',
      bodyNe: [
        p('वर्षाले विद्यालय प्रभावित पार्छ। नागरिक वाच डेस्क सुरक्षा पहिला राख्छ।'),
        p('हठात बन्द अफवाह रोक्न आधिकारिक सूचना चाहिन्छ।'),
        p('परीक्षा पात्रो लचिलो बनाउनुपर्छ।'),
        p('मध्याह्न भोजन व्यवस्था पनि योजनामा पर्नुपर्छ।'),
        h2('तयारी सूची'),
        list([
          'सुरक्षा मापदण्ड',
          'अभिभावक सूचना',
          'पुनःपठन तालिका',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('When closures are needed, homework packs and alternate sites reduce loss.'),
      ],
    })
  ]
}
