import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionEntertainment(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-entertainment-1',
      slug: 'nepali-film-festival-prep',
      categorySlug: 'entertainment',
      titleNe: 'नेपाली चलचित्र महोत्सव तयारी: दर्शक र सिर्जनाकारको पुल',
      titleEn: 'Nepali film festival prep bridges audiences and makers',
      deckNe: 'महोत्सवले नयाँ फिल्म देखाउने मात्र होइन, छलफल र सहकार्यको मञ्च पनि खुलाउनुपर्छ।',
      deckEn: 'Festivals should open discussion and collaboration, not only screenings.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('चलचित्र महोत्सव सांस्कृतिक क्यालेन्डरको महत्त्वपूर्ण हिस्सा हो। नागरिक वाच डेस्कले पहुँच र विविधतालाई मापदण्ड मान्छ।'),
        p('केवल प्रचार होइन, सिर्जनाकार संवाद चाहिन्छ।'),
        p('भाषा उपशीर्षकले फरक दर्शक जोड्छ।'),
        p('स्थानीय हल सहकार्यले लागत घटाउन सक्छ।'),
        h2('महोत्सवका मापदण्ड'),
        list([
          'सुलभ टिकट',
          'नयाँ निर्देशक खण्ड',
          'उपशीर्षक पहुँच',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Festivals should open discussion and collaboration, not only screenings.'),
      ],
    }),
    base({
      id: 'art-ed-entertainment-2',
      slug: 'folk-music-revival-stages',
      categorySlug: 'entertainment',
      titleNe: 'लोक संगीत पुनरुत्थान: मञ्च र पुस्ता हस्तान्तरण',
      titleEn: 'Folk music revival needs stages and generational handoff',
      deckNe: 'लोक धुन जोगाउन रेकर्डिङसँगै जीवित प्रदर्शन र शिक्षण चाहिन्छ।',
      deckEn: 'Keeping folk music alive needs live stages and teaching, not only recordings.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: [],
      reportingLocation: 'पोखरा',
      province: 'gandaki',
      bodyNe: [
        p('लोक संगीत पहिचानको अंश हो। नागरिक वाच डेस्कले पुस्ता हस्तान्तरण कमजोर हुँदा चिन्ता व्यक्त गर्छ।'),
        p('पर्यटन प्रदर्शन मात्र पर्याप्त होइन।'),
        p('महिला लोक गायिकाको मञ्च पहुँच बढाउनुपर्छ।'),
        p('डिजिटल अभिलेखले संरक्षण सहयोग गर्छ।'),
        h2('जोगाउने उपाय'),
        list([
          'विद्यालय कार्यक्रम',
          'सामुदायिक रेडियो प्रसारण',
          'युवा कलाकार मेन्टरसिप',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Keeping folk music alive needs live stages and teaching, not only recordings.'),
      ],
    }),
    base({
      id: 'art-ed-entertainment-3',
      slug: 'kathmandu-theatre-season',
      categorySlug: 'entertainment',
      titleNe: 'काठमाडौं रङ्गमञ्च याम: सानो हल, ठूलो संवाद',
      titleEn: 'Kathmandu theatre season: small halls, big conversation',
      deckNe: 'रङ्गमञ्चले सामाजिक विषय उठाउँछ। टिकट मूल्य र हल उपलब्धताले पहुँच निर्धारण गर्छ।',
      deckEn: 'Theatre raises social themes; ticket price and hall access decide who can attend.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('रङ्गमञ्च समुदाय संवादको शक्तिशाली माध्यम हो। नागरिक वाच डेस्कले साना उत्पादनलाई स्थान दिन आग्रह गर्छ।'),
        p('हल भाडा मुख्य खर्च हो।'),
        p('समीक्षा संस्कृतिले गुणस्तर बहस खुलाउँछ।'),
        p('प्रदेश सहरमा भ्रमणले दर्शक आधार फराकिलो बनाउँछ।'),
        h2('दर्शक विस्तार'),
        list([
          'विद्यार्थी छुट',
          'भ्रमण प्रदर्शनी',
          'स्थानीय भाषा नाटक',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Theatre raises social themes; ticket price and hall access decide who can attend.'),
      ],
    }),
    base({
      id: 'art-ed-entertainment-4',
      slug: 'streaming-vs-cinema-debate',
      categorySlug: 'entertainment',
      titleNe: 'स्ट्रिमिङ र सिनेमा हल: सहअस्तित्वको बाटो',
      titleEn: 'Streaming and cinema halls can coexist',
      deckNe: 'दर्शक आदत फेरिएको छ। हल अनुभव र घरेलु हेराइ दुवैका लागि स्पष्ट रणनीति चाहिन्छ।',
      deckEn: 'Audience habits changed; halls and home viewing both need clear strategies.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      isFeatured: 'secondary',
      tagSlugs: [],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('स्ट्रिमिङले पहुँच बढायो तर हल अर्थतन्त्रमा चाप पर्‍यो। नागरिक वाच डेस्क दुवै माध्यमको सहअस्तित्व खोज्छ।'),
        p('नेपाली सामग्रीको खोज योग्यता महत्त्वपूर्ण छ।'),
        p('सिनेमा हल सामाजिक अनुभव बेच्न सक्छ।'),
        p('नीतिले साना निर्मातालाई ठाउँ दिनुपर्छ।'),
        h2('उद्योगका प्रश्न'),
        list([
          'रिलिज झ्याल पारदर्शिता',
          'राजस्व बाँडफाँड',
          'पाइरेसी निवारण',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Audience habits changed; halls and home viewing both need clear strategies.'),
      ],
    }),
    base({
      id: 'art-ed-entertainment-5',
      slug: 'heritage-cultural-events-calendar',
      categorySlug: 'entertainment',
      titleNe: 'साँस्कृतिक सम्पदा कार्यक्रम: पात्रो र सहभागिता',
      titleEn: 'Heritage cultural events need a clear calendar',
      deckNe: 'जात्रा र प्रदर्शनीको अग्रिम पात्रो आए परिवार र पर्यटक दुवै योजना बनाउन सक्छन्।',
      deckEn: 'Advance calendars help families and visitors plan around festivals and exhibitions.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["climate"],
      reportingLocation: 'भक्तपुर',
      province: 'bagmati',
      bodyNe: [
        p('साँस्कृतिक कार्यक्रम शहरको पहिचान हो। नागरिक वाच डेस्कले सुरक्षा र पहुँचलाई जोड दिन्छ।'),
        p('मनसुन याममा वैकल्पिक स्थल योजना चाहिन्छ।'),
        p('युवा स्वयंसेवक परिचालनले ऊर्जा थप्छ।'),
        p('अभिलेखीकरणले पछिल्ला पुस्तालाई सम्पदा बुझाउँछ।'),
        h2('आयोजना सुधार'),
        list([
          'अग्रिम सूचना',
          'भीड व्यवस्थापन',
          'स्थानीय कलाकार प्राथमिकता',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Advance calendars help families and visitors plan around festivals and exhibitions.'),
      ],
    })
  ]
}
