import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionHealth(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-health-1',
      slug: 'monsoon-disease-alert-guide',
      categorySlug: 'health',
      titleNe: 'मनसुन रोग सतर्कता: ज्वरो र पानीजन्य संक्रमण',
      titleEn: 'Monsoon disease alert: fever and water-borne infection',
      deckNe: 'सफा पानी, हात धुने बानी र छिटो जाँचले जटिलता घटाउँछ।',
      deckEn: 'Clean water, handwashing and early checks reduce complications.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('मनसुनमा संक्रमण जोखिम बढ्छ। नागरिक वाच स्वास्थ्य डेस्कले डर होइन तयारीको सन्देश दिन्छ।'),
        p('अस्पताल भीड व्यवस्थापन चाहिन्छ।'),
        p('गर्भवती र बालबालिका प्राथमिक समूह हुन्।'),
        p('अफवाह औषधि सेवन घातक हुन सक्छ।'),
        h2('घरमा अपनाउने सावधानी'),
        list([
          'उमालेको/शोधित पानी',
          'झुलको प्रयोग',
          'लक्षण देखिए जाँच',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Clean water, handwashing and early checks reduce complications.'),
      ],
    }),
    base({
      id: 'art-ed-health-2',
      slug: 'rural-maternal-care-access',
      categorySlug: 'health',
      titleNe: 'ग्रामीण मातृ देखभाल: पहुँच र सम्मान',
      titleEn: 'Rural maternal care: access with dignity',
      deckNe: 'प्रसूति सेवा नजिक र सम्मानजनक हुनुपर्छ। यातायात र २४ घण्टे जनशक्ति मुख्य चुनौती हुन्।',
      deckEn: 'Maternity care must be near and respectful; transport and 24-hour staffing are key hurdles.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: [],
      reportingLocation: 'अछाम',
      bodyNe: [
        p('मातृ मृत्यु घटाउने लक्ष्य सेवा गुणस्तरमा निर्भर छ। नागरिक वाच डेस्कले बाधा रेकर्ड गर्छ।'),
        p('घर प्रसूति बाध्यता बन्नु हुँदैन।'),
        p('परिवार निर्णय प्रक्रियामा महिला आवाज सुनिनुपर्छ।'),
        p('रेफरल अस्पतालसँग समन्वय अनिवार्य छ।'),
        h2('सुधारका स्तम्भ'),
        list([
          'एम्बुलेन्स/कोष',
          'प्रशिक्षित कर्मी',
          'पोषण परामर्श',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Maternity care must be near and respectful; transport and 24-hour staffing are key hurdles.'),
      ],
    }),
    base({
      id: 'art-ed-health-3',
      slug: 'mental-health-stigma-break',
      categorySlug: 'health',
      titleNe: 'मानसिक स्वास्थ्य कलंक तोड्ने कुरा',
      titleEn: 'Breaking mental health stigma',
      deckNe: 'सहयोग माग्नु कमजोरी होइन। परामर्श पहुँच र गोपनीयता बढाउनुपर्छ।',
      deckEn: 'Seeking help is not weakness; counselling access and privacy must expand.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('मानसिक स्वास्थ्य बहस बढे पनि कलंक बाँकी छ। नागरिक वाच डेस्क संवेदनशील भाषामा जोड दिन्छ।'),
        p('आत्महत्या समाचारमा सावधानी अपरिहार्य छ।'),
        p('सेवा शुल्क र दूरी अवरोध हुन्।'),
        p('परिवार समर्थन निर्णायक हुन्छ।'),
        h2('समुदाय भूमिका'),
        list([
          'विद्यालय परामर्श',
          'कार्यस्थल नीति',
          'मिडिया भाषा',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Seeking help is not weakness; counselling access and privacy must expand.'),
      ],
    }),
    base({
      id: 'art-ed-health-4',
      slug: 'hospital-waiting-time-transparency',
      categorySlug: 'health',
      titleNe: 'अस्पताल प्रतीक्षा समय: पारदर्शिता किन चाहिन्छ',
      titleEn: 'Hospital waiting times need transparency',
      deckNe: 'कति कुर्नुपर्छ भन्ने जानकारी आए बिरामी योजना बनाउन सक्छन्।',
      deckEn: 'Knowing expected waits helps patients plan.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["data-story"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('लामो लहरले विश्वास घटाउँछ। नागरिक वाच डेस्क मापन र प्रकाशन माग्छ।'),
        p('कर्मचारी अभाव लुकाएर समाधान हुँदैन।'),
        p('डिजिटल अपोइन्टमेन्ट सहयोगी हुन सक्छ।'),
        p('निजी र सरकारी दुवैमा मापदण्ड चाहिन्छ।'),
        h2('प्रशासन कदम'),
        list([
          'विभागगत औसत समय',
          'टोकन प्रणाली',
          'आपतकाल छुट्याउने',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Knowing expected waits helps patients plan.'),
      ],
    }),
    base({
      id: 'art-ed-health-5',
      slug: 'vaccine-awareness-community',
      categorySlug: 'health',
      titleNe: 'खोप चेतना: समुदाय विश्वास पुनर्निर्माण',
      titleEn: 'Vaccine awareness and rebuilding community trust',
      deckNe: 'स्पष्ट जानकारी र स्वास्थ्यकर्मी संवादले द्विविधा घटाउँछ।',
      deckEn: 'Clear information and health-worker dialogue reduce doubt.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: [],
      reportingLocation: 'महोत्तरी',
      bodyNe: [
        p('खोप कार्यक्रम जनस्वास्थ्यको आधार हो। नागरिक वाच डेस्क अफवाहको जवाफ तथ्यले दिन्छ।'),
        p('विद्यालय अभियान प्रभावकारी हुन्छ।'),
        p('गर्भवती परामर्श छुटाउनु हुँदैन।'),
        p('शितल श्रृंखला विश्वसनीय बनाउनुपर्छ।'),
        h2('सञ्चार सुझाव'),
        list([
          'स्थानीय भाषा',
          'साइड इफेक्ट इमानदारी',
          'प्रश्नोत्तर सत्र',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Clear information and health-worker dialogue reduce doubt.'),
      ],
    })
  ]
}
