import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionInterview(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-interview-1',
      slug: 'interview-provincial-planner',
      categorySlug: 'interview',
      titleNe: 'अन्तर्वार्ता: प्रदेश योजना अधिकृतसँग सेवा प्राथमिकता',
      titleEn: 'Interview: a provincial planner on service priorities',
      deckNe: 'बजेट होइन, कार्यान्वयन अनुशासनले प्रदेश सफलता देखाउँछ भन्ने उनीहरूको तर्क।',
      deckEn: 'They argue implementation discipline, not budgets alone, shows provincial success.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["exclusive-report"],
      reportingLocation: 'हेटौंडा',
      bodyNe: [
        p('नागरिक वाच डेस्कले प्रदेश योजना अधिकृतसँग सेवा प्राथमिकताबारे कुराकानी गरेको छ। नाम र विवरण गोपनीयताका लागि सामान्यीकृत छ।'),
        p('उनीहरूका अनुसार वडास्तर डाटा बिना योजना हावामा बन्छ।'),
        p('महिला र युवा सहभागिता बैठकमा देखिनुपर्छ।'),
        p('पारदर्शिताले राजनीतिक दबाब पनि व्यवस्थापन गर्छ।'),
        h2('मुख्य अंश'),
        list([
          'प्राथमिकता छनोट',
          'नागरिक सुनुवाइ',
          'सूचक सार्वजनिक',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('They argue implementation discipline, not budgets alone, shows provincial success.'),
      ],
    }),
    base({
      id: 'art-ed-interview-2',
      slug: 'interview-women-entrepreneur',
      categorySlug: 'interview',
      titleNe: 'अन्तर्वार्ता: महिला उद्यमीसँग पुँजी र बजार',
      titleEn: 'Interview: a woman entrepreneur on capital and markets',
      deckNe: 'कर्जा प्रक्रिया सरल भए धेरै महिला व्यवसाय विस्तार गर्न सक्छन्।',
      deckEn: 'Simpler credit processes would let more women expand businesses.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'बुटवल',
      bodyNe: [
        p('नागरिक वाचले साना खाद्य प्रशोधन उद्यम चलाउने महिलासँग अन्तर्वार्ता लिएको छ।'),
        p('परिवार जिम्मेवारी र व्यवसाय समय व्यवस्थापन चुनौती हो।'),
        p('डिजिटल भुक्तानीले ग्राहक आधार बढाएको अनुभव छ।'),
        p('स्थानीय मेला नियमित हुनुपर्ने माग राखियो।'),
        h2('उनीहरूको जोड'),
        list([
          'धितो विकल्प',
          'बजार लिंक',
          'तालिम',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Simpler credit processes would let more women expand businesses.'),
      ],
    }),
    base({
      id: 'art-ed-interview-3',
      slug: 'interview-cricket-coach',
      categorySlug: 'interview',
      titleNe: 'अन्तर्वार्ता: क्रिकेट प्रशिक्षकसँग युवा विकास',
      titleEn: 'Interview: a cricket coach on youth development',
      deckNe: 'प्रतिभा छनोटमा पारदर्शिता र दीर्घकालीन फिटनेस दुवै चाहिन्छ।',
      deckEn: 'Talent selection needs transparency and long-term fitness focus.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["nepal-cricket"],
      reportingLocation: 'कीर्तिपुर',
      bodyNe: [
        p('नागरिक वाच खेलकुद डेस्कले युवा प्रशिक्षकसँग संवाद गरेको छ।'),
        p('धेरै अभिभावक नतिजा हतार गर्छन्।'),
        p('विद्यालय क्रिकेटले आधार दिन्छ।'),
        p('महिला क्रिकेटमा मैदान पहुँच सुधार्न आग्रह गरियो।'),
        h2('प्रशिक्षक दृष्टिकोण'),
        list([
          'आधारभूत सीप',
          'अभिभावक अपेक्षा',
          'चोट रोकथाम',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Talent selection needs transparency and long-term fitness focus.'),
      ],
    }),
    base({
      id: 'art-ed-interview-4',
      slug: 'interview-climate-scientist',
      categorySlug: 'interview',
      titleNe: 'अन्तर्वार्ता: जलवायु वैज्ञानिकसँग हिमाली जोखिम',
      titleEn: 'Interview: a climate scientist on Himalayan risk',
      deckNe: 'डाटा खुला भए स्थानीय योजना सटीक हुन्छ भन्ने उनीहरूको जोड।',
      deckEn: 'They stress open data makes local planning more precise.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाचले जलवायु अनुसन्धानकर्मीसँग हिमाली जोखिमबारे कुराकानी गर्‍यो।'),
        p('ग्लेसियर ताल निगरानी निरन्तर चाहिन्छ।'),
        p('कृषक अनुभवलाई डाटासँग जोड्नुपर्छ।'),
        p('नीति ढिलाइले अनुकूलन खर्च बढाउँछ।'),
        h2('वैज्ञानिक सन्देश'),
        list([
          'पूर्वसूचना',
          'भू-उपयोग',
          'समुदाय विज्ञान',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('They stress open data makes local planning more precise.'),
      ],
    }),
    base({
      id: 'art-ed-interview-5',
      slug: 'interview-diaspora-organizer',
      categorySlug: 'interview',
      titleNe: 'अन्तर्वार्ता: प्रवासी संगठकसँग सामूहिक सहयोग',
      titleEn: 'Interview: a diaspora organizer on mutual aid',
      deckNe: 'संकटमा सूचना र कानुनी सल्लाह नेटवर्कले जीवन जोगाउँछ।',
      deckEn: 'Crisis information and legal-advice networks can protect lives.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाच प्रवास डेस्कले स्वयंसेवी संगठकसँग अन्तर्वार्ता गर्‍यो।'),
        p('नयाँ आएका कामदार अभिमुखीकरण अभाव भोग्छन्।'),
        p('महिला हेल्पडेस्क अलग आवश्यक छ।'),
        p('नेपालमा परिवार परामर्श पनि जोड्नुपर्ने बताइयो।'),
        h2('संगठन अभ्यास'),
        list([
          'स्वयंसेवक तालिम',
          'पारदर्शी कोष',
          'दूतावास समन्वय',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Crisis information and legal-advice networks can protect lives.'),
      ],
    })
  ]
}
