import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionLiterature(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-literature-1',
      slug: 'new-nepali-poetry-collections',
      categorySlug: 'literature',
      titleNe: 'नयाँ नेपाली कविता संग्रह: स्वर र प्रयोग',
      titleEn: 'New Nepali poetry collections: voice and experiment',
      deckNe: 'युवा कविताले शहर, प्रवास र पहिचानका प्रश्न उठाएको छ।',
      deckEn: 'Young poetry raises questions of city, migration and identity.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ['editor-pick'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('नागरिक वाच साहित्य डेस्कले नयाँ संग्रहलाई पाठक र लेखकबीचको पुलका रूपमा हेर्छ।'),
        p('कविता महोत्सवले संवाद बढाउँछ।'),
        p('विद्यालय पुस्तकालयमा कविता खण्ड चाहिन्छ।'),
        p('अनुवादले पहुँच फराकिलो बनाउँछ।'),
        h2('पढ्दा ध्यान दिनुहोस्'),
        list(['भाषा प्रयोग', 'सामाजिक सन्दर्भ', 'पाठ समूह छलफल']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Young poetry raises questions of city, migration and identity.')],
    }),
    base({
      id: 'art-ed-literature-2',
      slug: 'classic-prose-translation-wave',
      categorySlug: 'literature',
      titleNe: 'क्लासिक गद्य अनुवाद: नयाँ पुस्तासम्मको पुल',
      titleEn: 'Classic prose translation as a bridge to new readers',
      deckNe: 'पुराना कृति अनुवाद र सम्पादनले साहित्यिक सम्पदा जीवित राख्छ।',
      deckEn: 'Edited translations keep literary heritage alive for new readers.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: [],
      reportingLocation: 'ललितपुर',
      province: 'bagmati',
      bodyNe: [
        p('अनुवाद श्रमसँग जोडिएको काम हो। नागरिक वाच डेस्क गुणस्तरमा जोड दिन्छ।'),
        p('पाठ्यक्रममा क्लासिक समावेश बहस खुला हुनुपर्छ।'),
        p('महिला लेखक पुनःपठन आवश्यक छ।'),
        p('सार्वजनिक पुस्तकालय साझेदार हुन सक्छन्।'),
        h2('संरक्षणका काम'),
        list(['सटीक टिप्पणी', 'सुलभ संस्करण', 'डिजिटल अभिलेख']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Edited translations keep literary heritage alive for new readers.')],
    }),
    base({
      id: 'art-ed-literature-3',
      slug: 'literary-festivals-access',
      categorySlug: 'literature',
      titleNe: 'साहित्य महोत्सव: पहुँच र विविध स्वर',
      titleEn: 'Literary festivals need access and diverse voices',
      deckNe: 'महोत्सवले ठूला नाम मात्र होइन, नयाँ लेखक पनि स्थान दिनुपर्छ।',
      deckEn: 'Festivals must platform new writers, not only big names.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ['editor-pick'],
      reportingLocation: 'पोखरा',
      province: 'gandaki',
      bodyNe: [
        p('साहित्य महोत्सव उत्सव मात्र होइन। नागरिक वाच डेस्क संवाद गुणस्तर हेर्छ।'),
        p('टिकट महँगो हुँदा युवा टाढिन्छन्।'),
        p('स्थानीय भाषा सत्रले विविधता देखाउँछ।'),
        p('पुस्तक बिक्री र लेखक रोजीरोटी जोडिनुपर्छ।'),
        h2('पहुँच सुधार'),
        list(['निःशुल्क सत्र', 'सांकेतिक भाषा/उपशीर्षक', 'प्रदेश भ्रमण']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Festivals must platform new writers, not only big names.')],
    }),
    base({
      id: 'art-ed-literature-4',
      slug: 'school-reading-culture',
      categorySlug: 'literature',
      titleNe: 'विद्यालय पठन संस्कृति: परीक्षाभन्दा पर',
      titleEn: 'School reading culture beyond exams',
      deckNe: 'रुचिपूर्ण पठनले भाषा र सोच दुवै बलियो बनाउँछ।',
      deckEn: 'Pleasure reading strengthens language and thought.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ['budget-2083'],
      reportingLocation: 'कास्की',
      province: 'gandaki',
      bodyNe: [
        p('परीक्षा केन्द्रित पठनले रुचि मार्छ। नागरिक वाच डेस्क स्वतन्त्र पठन प्रोत्साहन गर्छ।'),
        p('पुस्तकालय बजेट सानो तर प्रभावशाली हुन सक्छ।'),
        p('बाल साहित्य विविधता चाहिन्छ।'),
        p('शिक्षक तालिमले फरक पार्छ।'),
        h2('विद्यालय कदम'),
        list(['पुस्तक कुना', 'साप्ताहिक पठन समय', 'अभिभावक सहभागिता']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Pleasure reading strengthens language and thought.')],
    }),
    base({
      id: 'art-ed-literature-5',
      slug: 'diaspora-writers-notebook',
      categorySlug: 'literature',
      titleNe: 'प्रवासी लेखक नोटबुक: दुई दुनियाबीचको कथा',
      titleEn: 'Diaspora writers notebook: stories between two worlds',
      deckNe: 'प्रवास अनुभवले नेपाली साहित्यमा नयाँ भूगोल थपेको छ।',
      deckEn: 'Migration experience adds new geographies to Nepali literature.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ['labour-migration'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('प्रवासी लेखन सेतु हो। नागरिक वाच साहित्य डेस्क यसलाई मूलधार बहसमा ल्याउँछ।'),
        p('प्रकाशन पहुँच असमान छ।'),
        p('अनलाइन पत्रिकाले ठाउँ दिएका छन्।'),
        p('पाठक क्लबले संवाद जीवित राख्छ।'),
        h2('सम्पादकीय चासो'),
        list(['भाषा मिश्रण', 'घरको स्मृति', 'पहचान द्वन्द्व']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Migration experience adds new geographies to Nepali literature.')],
    }),
  ]
}
