import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionOpinion(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-opinion-1',
      slug: 'federalism-accountability-column',
      categorySlug: 'opinion',
      titleNe: 'संघीयतामा जवाफदेहिता: सेवा नतिजाबाट मापन',
      titleEn: 'Federalism accountability must be measured by service results',
      deckNe: 'पद होइन, सेवा गति र गुणस्तरले संघीयता जाँच्नुपर्छ।',
      deckEn: 'Judge federalism by service speed and quality, not posts.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('संघीयताको सफलता नागरिकको दैनिक अनुभवमा देखिनुपर्छ। नागरिक वाच विचार डेस्कले सेवा नतिजालाई केन्द्रमा राख्छ।'),
        p('दोहोरो जिम्मेवारीले नागरिक अन्योलमा पर्छन्।'),
        p('खुला तथ्यांकले तुलना सजिलो बनाउँछ।'),
        p('स्थानीय सुनुवाइ नियमित हुनुपर्छ।'),
        h2('तीन तहका प्रश्न'),
        list([
          'वडा सेवा समय',
          'प्रदेश बजेट कार्यान्वयन',
          'संघीय मापदण्ड',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Judge federalism by service speed and quality, not posts.'),
      ],
    }),
    base({
      id: 'art-ed-opinion-2',
      slug: 'monsoon-urban-planning-oped',
      categorySlug: 'opinion',
      titleNe: 'मनसुन र सहरी योजना: नालीदेखि आवाससम्म',
      titleEn: 'Monsoon and urban planning from drains to housing',
      deckNe: 'वर्षा हरेक साल आउँछ। तयारी हरेक साल अधुरो किन?',
      deckEn: 'Rain is annual; preparation should not stay incomplete.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('सहरी बाढी प्राकृतिक मात्र होइन। नागरिक वाच डेस्क योजना कमजोरीतिर औंल्याउँछ।'),
        p('नक्सा र वास्तविक नाली फरक हुनुहुँदैन।'),
        p('गरिब बस्ती जोखिममा बढी पर्छ।'),
        p('दीर्घकालीन लगानी अल्पकालीन राहतभन्दा सस्तो हुन्छ।'),
        h2('योजनाका प्राथमिकता'),
        list([
          'निकास क्षमता',
          'अवैध निर्माण नियन्त्रण',
          'हरित क्षेत्र',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Rain is annual; preparation should not stay incomplete.'),
      ],
    }),
    base({
      id: 'art-ed-opinion-3',
      slug: 'press-freedom-ethics-note',
      categorySlug: 'opinion',
      titleNe: 'प्रेस स्वतन्त्रता र नैतिकता: एकै सिक्काका दुई पाटा',
      titleEn: 'Press freedom and ethics are two sides of one coin',
      deckNe: 'स्वतन्त्रतालाई विश्वसनीयतासँग जोडेर मात्र सार्वजनिक हित जोगिन्छ।',
      deckEn: 'Freedom only serves the public when paired with credibility.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["exclusive-report"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('नागरिक वाच विचारमा प्रेस स्वतन्त्रता जिम्मेवारीसहित आउँछ।'),
        p('हतारको हेडलाइनले क्षति पुर्‍याउन सक्छ।'),
        p('पाठक गुनासो सुनुवाइ खुला हुनुपर्छ।'),
        p('स्वतन्त्र पत्रकारिता लोकतन्त्रको अक्सिजन हो।'),
        h2('सम्पादकीय मापदण्ड'),
        list([
          'स्रोत संरक्षण',
          'सच्याइ नीति',
          'घृणा भाषण बन्देज',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Freedom only serves the public when paired with credibility.'),
      ],
    }),
    base({
      id: 'art-ed-opinion-4',
      slug: 'youth-employment-policy-view',
      categorySlug: 'opinion',
      titleNe: 'युवा रोजगारी नीति: वाचा होइन बाटो चाहिन्छ',
      titleEn: 'Youth employment policy needs pathways not pledges',
      deckNe: 'सीप, इंटर्नसिप र उद्यम सहयोग एकै प्याकेजमा आउनुपर्छ।',
      deckEn: 'Skills, internships and enterprise support must arrive as one package.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('रोजगारी अभावले निराशा बढाउँछ। नागरिक वाच डेस्क बाटो मापनयोग्य होस् भन्छ।'),
        p('वैदेशिक रोजगारी मात्र उत्तर होइन।'),
        p('स्थानीय उद्योगसँग तालिम जोड्नुपर्छ।'),
        p('युवा आवाज नीति बनाउँदा सुनिनुपर्छ।'),
        h2('नीति जाँच सूची'),
        list([
          'सीप माग मिलान',
          'क्षेत्रीय अवसर',
          'महिला सुरक्षा',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Skills, internships and enterprise support must arrive as one package.'),
      ],
    }),
    base({
      id: 'art-ed-opinion-5',
      slug: 'public-transport-investment-case',
      categorySlug: 'opinion',
      titleNe: 'सार्वजनिक यातायात लगानी: शहरको साझा हित',
      titleEn: 'Public transport investment is a shared city interest',
      deckNe: 'सस्तो, सुरक्षित र भरपर्दो यातायातले वायु र समय दुवै जोगाउँछ।',
      deckEn: 'Affordable reliable transit saves air and time.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["budget-2083"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('निजी सवारी मात्रले शहर धान्दैन। नागरिक वाच डेस्क सार्वजनिक विकल्प बलियो बनाउन तर्क गर्छ।'),
        p('अनुदान पारदर्शी हुनुपर्छ।'),
        p('पैदल र साइकल पूर्वाधार छुटाउनु हुँदैन।'),
        p('डेटामा आधारित रुट योजना चाहिन्छ।'),
        h2('लगानीका आधार'),
        list([
          'बस फ्रिक्वेन्सी',
          'महिला सुरक्षा',
          'एकीकृत टिकट',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Affordable reliable transit saves air and time.'),
      ],
    })
  ]
}
