import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionPhotoStory(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-photo-story-1',
      slug: 'photo-monsoon-markets',
      categorySlug: 'photo-story',
      titleNe: 'फोटो कथा: मनसुन बजारका अनुहार',
      titleEn: 'Photo story: faces of monsoon markets',
      deckNe: 'पानीमा पनि खुला पसल। व्यापारी र ग्राहकको दैनिक संघर्ष दृश्यमा।',
      deckEn: 'Shops stay open in the rain; traders and customers persist in the frame.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ['climate'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('नागरिक वाच फोटो डेस्कले मनसुन बजारलाई दैनिक अर्थतन्त्रको चित्रका रूपमा देखायो।'),
        p('छविहरूमा पानीको चमक र थकान दुवै छ।'),
        p('पाठकलाई लाग्न सक्छ यो सामान्य दृश्य हो, तर यो शहरको जीवन रेखा हो।'),
        p('क्याप्सनमा नाम र अनुमति सम्मान गरिएको छ।'),
        h2('दृश्य नोट'),
        list(['तारपोल र पानी', 'बिहानको आपूर्ति', 'महिला विक्रेता']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Shops stay open in the rain; traders and customers persist in the frame.')],
    }),
    base({
      id: 'art-ed-photo-story-2',
      slug: 'photo-highway-repair-crews',
      categorySlug: 'photo-story',
      titleNe: 'फोटो कथा: राजमार्ग मर्मत टोली',
      titleEn: 'Photo story: highway repair crews',
      deckNe: 'पहिरो पछिको सफाइ गर्ने हातहरू। जोखिमबीचको सार्वजनिक सेवा।',
      deckEn: 'Hands clearing landslide debris; public service inside risk.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ['climate'],
      reportingLocation: 'धादिङ',
      province: 'bagmati',
      bodyNe: [
        p('नागरिक वाचले मर्मत टोलीसँग समय बितायो।'),
        p('छविले पसिना र धुलो देखाउँछ।'),
        p('समुदाय चिया र पानी लिएर आएको दृश्य पनि छ।'),
        p('यो कथा श्रमिक सम्मानको हो।'),
        h2('श्रृंखला जोड'),
        list(['मेसिन र मजदुर', 'सुरक्षा गियर', 'रातको बत्ती']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Hands clearing landslide debris; public service inside risk.')],
    }),
    base({
      id: 'art-ed-photo-story-3',
      slug: 'photo-kathmandu-dawn',
      categorySlug: 'photo-story',
      titleNe: 'फोटो कथा: काठमाडौं बिहान',
      titleEn: 'Photo story: Kathmandu at dawn',
      deckNe: 'मन्दिरदेखि बसपार्कसम्म शहर बिउँझिने क्षण।',
      deckEn: 'From temples to bus parks, the city waking.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: [],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('बिहानको प्रकाश शहरको अर्को अनुहार हो। नागरिक वाच फोटो कथा शान्त तर व्यस्त लय देखाउँछ।'),
        p('प्रदूषण र सुन्दरता सँगै छन्।'),
        p('पाठक आफ्नै सहर चिन्हन्।'),
        p('कुनै नाटकीय अतिरञ्जना छैन।'),
        h2('समय रेखांकन'),
        list(['चिया पसल', 'अखबार पाठक', 'विद्यालय जाने बच्चा']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('From temples to bus parks, the city waking.')],
    }),
    base({
      id: 'art-ed-photo-story-4',
      slug: 'photo-tea-garden-workers',
      categorySlug: 'photo-story',
      titleNe: 'फोटो कथा: चिया बगानका कामदार',
      titleEn: 'Photo story: tea garden workers',
      deckNe: 'पात टिप्ने हात र पहाडी मौसम। श्रमको दृश्य कथा।',
      deckEn: 'Hands picking leaves in hill weather; a labour visual story.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ['labour-migration'],
      reportingLocation: 'इलाम',
      province: 'koshi',
      bodyNe: [
        p('नागरिक वाच डेस्कले बगान श्रमलाई नजिकबाट कैद गर्‍यो।'),
        p('महिला कामदारको केन्द्रीयता देखिन्छ।'),
        p('ज्याला र मौसम दुवै चुनौती हुन्।'),
        p('कथा उपभोग मात्र होइन सम्मान माग्छ।'),
        h2('दृश्य तत्व'),
        list(['टोकरी', 'हिम/कुहिरो', 'सामुदायिक बास']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Hands picking leaves in hill weather; a labour visual story.')],
    }),
    base({
      id: 'art-ed-photo-story-5',
      slug: 'photo-river-erosion-communities',
      categorySlug: 'photo-story',
      titleNe: 'फोटो कथा: नदी कटानले छोएका बस्ती',
      titleEn: 'Photo story: communities edged by river erosion',
      deckNe: 'घरको आँगन साँघुरिँदै गएको दृश्य। विपद्अघिको चेतावनी।',
      deckEn: 'Yards shrinking toward the river; a warning before disaster.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ['climate'],
      reportingLocation: 'बारा',
      province: 'madhesh',
      bodyNe: [
        p('नदी कटान धीमा विपद् हो। नागरिक वाच फोटोले समयको असर देखाउँछ।'),
        p('मानिस अझै आशा राखेर बसेका छन्।'),
        p('नीति ढिलाइ दृश्यमै देखिन्छ।'),
        p('यो कथा पूर्वतयारीको अपील हो।'),
        h2('फ्रेममा जोखिम'),
        list(['बालुवा थुप्रो', 'स्थानान्तरण छलफल', 'बालबालिका खेल']),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [p('Yards shrinking toward the river; a warning before disaster.')],
    }),
  ]
}
