import type { StoredArticle } from '../json-store'
import { base, p, h2, list, quote, isoDaysAgo } from './_helpers'

export function editionPolitics(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-politics-1',
      slug: 'provincial-alliance-realignment-2083',
      categorySlug: 'politics',
      titleNe: 'प्रदेश गठबन्धन फेरबदल: सत्ता समीकरणमा नयाँ दबाब',
      titleEn: 'Provincial alliance shifts put new pressure on power equations',
      deckNe: 'सातै प्रदेशमा दलहरूबीच सहकार्यका सर्त फेरिँदा शासन स्थिरता र बजेट पास प्रक्रिया प्रभावित हुन सक्ने देखिएको छ।',
      deckEn: 'Changing coalition terms across seven provinces may affect government stability and budget passage.',
      publishedAt: isoDaysAgo(0, 6),
      updatedAt: isoDaysAgo(0, 6),
      isFeatured: 'lead',
      tagSlugs: ['local-election'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('नागरिक वाच डेस्कको प्रदेश राजनीति अनुगमनअनुसार सातै प्रदेशमा दलहरूबीचको सहकार्य फेरिँदा सत्ता समीकरणमा नयाँ दबाब देखिएको छ। केही प्रदेशमा बजेट पास र मन्त्रिपरिषद् विस्तारसँग जोडिएका विवादले गठबन्धनका सर्त सार्वजनिक बहसको विषय बनेका छन्।'),
        p('संघीय संरचनामा प्रदेश सरकारहरू जनतासँग प्रत्यक्ष जोडिने सेवा वितरणको मुख्य थलो हुन्। त्यसैले गठबन्धन फेरबदलले केवल पद बाँडफाँड होइन, स्वास्थ्य, सडक र शिक्षाका कार्यक्रम कार्यान्वयनमा पनि असर पार्न सक्छ।'),
        h2('के हेर्नुपर्छ'),
        p('नागरिक वाचले तीन सूचकलाई प्राथमिकता दिएको छ: प्रदेशसभामा बहुमतको स्पष्टता, बजेट पारित समयरेखा, र मन्त्रालय जिम्मेवारी बाँडफाँडको पारदर्शिता। यी तीनैमा ढिलाइ भए सार्वजनिक सेवा प्रभावित हुने जोखिम रहन्छ।'),
        list([
          'प्रदेशसभा बैठक कार्यसूची सार्वजनिक हुनुपर्ने',
          'बजेट छलफलमा पर्याप्त समय सुनिश्चित गर्नुपर्ने',
          'गठबन्धन समझदारी लिखित र पढ्न मिल्ने बनाउनुपर्ने',
        ]),
        p('विपक्षी भूमिकामा रहेका दलहरूले जवाफदेहिताको माग गर्दै प्रश्न समय र समिति बैठक बढाउन दबाब दिएका छन्। सत्तापक्षले भने सेवा निरन्तरतालाई प्राथमिकता दिने दाबी गरेको छ।'),
        quote('गठबन्धन फेरिए पनि नागरिकले पाउने सेवा रोकिनु हुँदैन।', 'नागरिक वाच सम्पादकीय नोट'),
        p('आगामी साता प्रदेश राजधानीहरूमा हुने दलिय परामर्शले समीकरण स्पष्ट पार्ने अपेक्षा छ। नागरिक वाच डेस्कले प्रत्येक प्रदेशको बैठक नतिजा र बजेट स्थिति अलग-अलग अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Nagarik Watch desk monitoring finds shifting provincial coalitions are adding fresh pressure on power equations.'),
        p('Readers should watch majority clarity, budget timelines, and transparent portfolio sharing.'),
      ],
    }),
    base({
      id: 'art-ed-politics-2',
      slug: 'monsoon-session-budget-implementation-bills',
      categorySlug: 'politics',
      titleNe: 'मनसुन अधिवेशन: बजेट कार्यान्वयन र विधेयक प्राथमिकता',
      titleEn: 'Monsoon session priorities: budget delivery and key bills',
      deckNe: 'संघीय संसदको मनसुन अधिवेशनमा बजेट कार्यान्वयनसँग जोडिएका विधेयक र सार्वजनिक खरिद सुधार मुख्य एजेन्डा बन्ने संकेत देखिएको छ।',
      deckEn: 'Budget-linked bills and procurement reform look set to lead the monsoon parliamentary agenda.',
      publishedAt: isoDaysAgo(1, 7),
      updatedAt: isoDaysAgo(1, 7),
      isFeatured: 'secondary',
      tagSlugs: ['budget-2083'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('संघीय संसदको मनसुन अधिवेशनमा सरकारको प्राथमिकतासूची बजेट कार्यान्वयनतिर केन्द्रित देखिएको छ। नागरिक वाच संसदीय डेस्कले सभा र समितिका प्रारम्भिक कार्यसूची अध्ययन गर्दा खर्च प्रणाली, सार्वजनिक खरिद र जवाफदेहितासँग जोडिएका विधेयक अगाडि बढ्ने सम्भावना देखिएको छ।'),
        p('मनसुन याममा संसद् बैठकले नीतिगत छलफल मात्र होइन, विपद् तयारी र सडक अवरोधजस्ता तत्कालका विषयमा सांसद प्रश्न पनि निम्त्याउँछ। त्यसैले अधिवेशनको समय व्यवस्थापन महत्त्वपूर्ण हुन्छ।'),
        h2('प्राथमिकताका क्षेत्र'),
        p('नागरिक वाचले पाठकलाई तीन क्षेत्रमा ध्यान दिन आग्रह गरेको छ: बजेट विनियोजन कार्यान्वयनको प्रगति रिपोर्ट, समितिमा विचाराधीन विधेयकको समयतालिका, र प्रश्नोत्तरमा उठ्ने विपद्/पूर्वाधार विषय।'),
        p('प्रतिपक्षी दलहरूले पर्याप्त छलफल समय माग्दै आएका छन्। उनीहरूका अनुसार अघिल्लो बजेटका अधुरा प्रतिबद्धता समीक्षा नगरी नयाँ प्रस्तावमा मात्र केन्द्रित हुनुहुँदैन।'),
        list([
          'समिति बैठकको कार्यसूची नियमित सार्वजनिक गर्नु',
          'विधेयकको सरल भाषा सारांश पाठकमैत्री बनाउनु',
          'खर्च प्रगतिमा प्रदेश र स्थानीय तहको भूमिका स्पष्ट पार्नु',
        ]),
        p('नागरिक वाच डेस्कले अधिवेशन अवधिभर प्रमुख विधेयकको स्थिति र सांसद प्रश्नका सार पाठकलाई साप्ताहिक रूपमा प्रस्तुत गर्नेछ।'),
      ],
      bodyEn: [
        p('The monsoon session appears focused on budget delivery and procurement-linked bills.'),
      ],
    }),
    base({
      id: 'art-ed-politics-3',
      slug: 'local-election-finance-transparency-bar',
      categorySlug: 'politics',
      titleNe: 'स्थानीय चुनाव खर्च: पारदर्शिताको नयाँ मापदण्ड किन जरुरी',
      titleEn: 'Why a tougher bar on local election spending matters',
      deckNe: 'उम्मेदवार र दलले खर्च विवरण समयमै सार्वजनिक गर्नु मतदाता विश्वासको आधार हो। ढिलाइ र अपारदर्शिताले स्थानीय शासनमा प्रश्न जन्माउँछ।',
      deckEn: 'Timely campaign spending disclosure is foundational to voter trust in local government.',
      publishedAt: isoDaysAgo(2, 8),
      updatedAt: isoDaysAgo(2, 8),
      isFeatured: 'featured',
      tagSlugs: ['local-election'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('स्थानीय तहको निर्वाचन तयारीसँगै खर्च पारदर्शिता फेरि चर्चामा आएको छ। नागरिक वाच डेस्कले मतदाता शिक्षा र खर्च विवरणको पहुँचलाई लोकतन्त्रको आधारभूत सर्तका रूपमा हेर्ने गरेको छ।'),
        p('खर्च विवरण ढिलो आउँदा मतदाताले उम्मेदवारको स्रोत र प्राथमिकता बुझ्न पाउँदैनन्। यसले समान खेल मैदान कमजोर बनाउँछ र शंका बढाउँछ।'),
        h2('पाठकले माग्न सक्ने कुरा'),
        list([
          'उम्मेदवारको खर्च विवरणको सार',
          'दलिय सहयोग र विज्ञापन खर्चको छुट्टाछुट्टै जानकारी',
          'स्थानीय कार्यालयमा हेर्न मिल्ने प्रतिलिपि',
        ]),
        p('निर्वाचन प्रक्रिया सफा देखिनु मात्र पर्याप्त होइन। विवरण बुझ्न सकिने भाषामा उपलब्ध हुनुपर्छ। नागरिक वाचले महानगर र नगरपालिकाका नमूना फारम तुलना गरी पाठकमैत्री सूची प्रकाशित गर्नेछ।'),
        quote('पारदर्शिता भनेको फारम भर्नु मात्र होइन, मतदाताले पढेर बुझ्न सक्नु हो।'),
        p('स्थानीय शासन नजिकको सरकार हो। खर्च खुला हुँदा सेवा प्राथमिकतामाथि बहस गर्न सजिलो हुन्छ। नागरिक वाच डेस्कले यो श्रृंखला निरन्तर अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Timely, readable spending disclosure strengthens trust ahead of local elections.'),
      ],
    }),
    base({
      id: 'art-ed-politics-4',
      slug: 'federal-civil-service-reform-briefing',
      categorySlug: 'politics',
      titleNe: 'संघीय निजामती सुधार: सेवा प्रवाहमा के फेरिन्छ',
      titleEn: 'Federal civil service reform: what could change for service delivery',
      deckNe: 'कर्मचारी समायोजन, पदपूर्ति र जिम्मेवारी स्पष्टता संघीयता कार्यान्वयनका संवेदनशील विषय हुन्। सुधारले सेवा गति बढाउने अपेक्षा छ।',
      deckEn: 'Staff adjustment, recruitment and clearer duties remain sensitive federalism tests for faster services.',
      publishedAt: isoDaysAgo(3, 9),
      updatedAt: isoDaysAgo(3, 9),
      tagSlugs: ['budget-2083'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('संघीय निजामती सुधारको बहस फेरि सक्रिय भएको छ। नागरिक वाच डेस्कका अनुसार पाठकका लागि मुख्य प्रश्न सरल छ: सुधारपछि वडा कार्यालय र अस्पतालमा सेवा छिटो र स्पष्ट हुन्छ कि हुँदैन।'),
        p('कर्मचारी अभाव र दोहोरो जिम्मेवारीले स्थानीय तहमा ढिलाइ बढाएको गुनासो पुरानो हो। सुधारले पदपूर्ति प्रक्रिया र तालिम प्रणालीलाई एकै लयमा ल्याउन खोजेको देखिन्छ।'),
        h2('जोखिम र अवसर'),
        p('यदि जिम्मेवारी स्पष्ट भएन भने सुधार कागजी मात्र बन्न सक्छ। उल्टो, स्पष्ट मार्गचित्र र समयतालिका आए सेवा मापनयोग्य बन्न सक्छ।'),
        list([
          'रिक्त दरबन्दीको सार्वजनिक सूची',
          'तालिम र सरुवा मापदण्डको पारदर्शिता',
          'नागरिक उजुरी सुनुवाइको समयसीमा',
        ]),
        p('नागरिक वाचले संघ, प्रदेश र स्थानीय तहका अधिकारीसँगको संवादका आधारमा सेवा प्रवाह सूचक तयार पार्नेछ। राजनीति होइन, सेवा नतिजालाई केन्द्रमा राखिनेछ।'),
      ],
      bodyEn: [
        p('Civil service reform should be judged by faster, clearer local services.'),
      ],
    }),
    base({
      id: 'art-ed-politics-5',
      slug: 'youth-protest-governance-follow-up',
      categorySlug: 'politics',
      titleNe: 'युवा आन्दोलनपछिको शासन: जवाफदेहिता कसरी मापन गर्ने',
      titleEn: 'After youth protests: how to measure accountability',
      deckNe: 'सडकको आवाज नीतिमा रूपान्तरण भए/नभएको जाँच्न स्पष्ट सूचक चाहिन्छ। रोजगारी, सुरक्षा र संवाद संयन्त्र तीन मुख्य मापदण्ड हुन्।',
      deckEn: 'Turning street demands into policy needs clear metrics on jobs, safety and dialogue channels.',
      publishedAt: isoDaysAgo(4, 10),
      updatedAt: isoDaysAgo(4, 10),
      tagSlugs: ['exclusive-report'],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('युवा आन्दोलन र सार्वजनिक असन्तुष्टिले शासन प्रणालीमाथि नयाँ प्रश्न उठाइरहेका छन्। नागरिक वाच डेस्कले आक्रोशको समाचार मात्र होइन, त्यसपछिको नीति प्रतिक्रिया मापन गर्ने दृष्टिकोण अँगालेको छ।'),
        p('जवाफदेहिता देखाउन सरकारले संवाद मञ्च, उजुरी सुनुवाइ र रोजगारीसम्बन्धी ठोस कदम सार्वजनिक गर्नुपर्छ। मौखिक आश्वासन पर्याप्त होइन।'),
        h2('मापनका तीन स्तम्भ'),
        list([
          'रोजगारी र सीप कार्यक्रमको वास्तविक पहुँच',
          'सुरक्षा निकायको अनुपातपूर्ण व्यवहार र पारदर्शिता',
          'युवासँग नियमित संवादको कार्यतालिका',
        ]),
        p('नागरिक समाज र दलहरूबीचको संवाद अवरुद्ध हुँदा अफवाह बढ्छ। खुला तथ्यांक र स्वतन्त्र अनुगमनले विश्वास पुनर्निर्माणमा सहयोग गर्छ।'),
        p('नागरिक वाचले प्रदेश र संघीय नीति दस्तावेजमा युवा सम्बन्धी प्रतिबद्धताको कार्यान्वयन स्थिति आवधिक रूपमा तुलना गर्नेछ। पाठकलाई बुझ्न मिल्ने सारांश प्राथमिकता हुनेछ।'),
      ],
      bodyEn: [
        p('Accountability after youth protests should be measured with clear public metrics.'),
      ],
    }),
  ]
}
