import type { StoredArticle } from '../json-store'
import { base, p, h2, list, quote, isoDaysAgo } from './_helpers'

export function editionSociety(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-society-1',
      slug: 'monsoon-highway-community-impact',
      categorySlug: 'society',
      titleNe: 'मनसुनमा सडक अवरोध: समुदायको दैनिक जीवन कसरी प्रभावित',
      titleEn: 'Monsoon roadblocks: how daily life is disrupted',
      deckNe: 'पहिरो र बाढीले राजमार्ग अवरुद्ध हुँदा यातायात, बजार आपूर्ति र स्वास्थ्य सेवामा चाप बढेको छ।',
      deckEn: 'Landslides and floods blocking highways raise pressure on transport, markets and health access.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["climate"],
      reportingLocation: 'सिन्धुपाल्चोक',
      province: 'bagmati',
      bodyNe: [
        p('मनसुन सक्रिय रहँदा पहाडी सडकखण्डमा पहिरो र नदी कटान दोहोरिएका छन्। नागरिक वाच डेस्कले यात्रु, चालक र स्थानीय व्यापारीसँगको संवादमा आपूर्ति श्रृंखला प्रभावित भएको पाएको छ।'),
        p('रातको यातायात प्रतिबन्ध र आकस्मिक बन्दले विद्यार्थी र बिरामी परिवारलाई बढी मर्का परेको छ। वैकल्पिक मार्गबारे स्पष्ट सूचना नहुँदा अन्योल बढ्छ।'),
        p('स्थानीय प्रशासन र सडक विभागले सफाइ अभियान तीव्र पारेको दाबी गरे पनि पाठकलाई चाहिने कुरा हो: कहिले खुल्छ, कुन बाटो सुरक्षित छ।'),
        p('विपद् जोखिमयुक्त बस्तीमा पूर्वसूचना र अस्थायी बसोबास योजना पनि सडक सफाइसँगै जानुपर्छ।'),
        h2('समुदायले भोगेका समस्या'),
        list([
          'वैकल्पिक बाटोको जानकारी समयमै नआउनु',
          'अत्यावश्यक औषधि ढुवानी ढिला हुनु',
          'बजार मूल्यमा अचानक चाप',
        ]),
        quote('सडक खुलाउने कामसँगै स्थानीय सूचना प्रवाह पनि उत्तिकै जरुरी छ।'),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Landslides and floods blocking highways raise pressure on transport, markets and health access.'),
      ],
    }),
    base({
      id: 'art-ed-society-2',
      slug: 'urban-waste-management-pressure',
      categorySlug: 'society',
      titleNe: 'शहरी फोहोर व्यवस्थापन: मनसुनले बढाएको चाप',
      titleEn: 'Urban waste under monsoon pressure',
      deckNe: 'वर्षाले नाली अवरुद्ध र फोहोर थुप्रिँदा स्वास्थ्य जोखिम बढ्छ। नगर सेवा र नागरिक सहकार्य दुवै चाहिन्छ।',
      deckEn: 'Rain-clogged drains and piled waste raise health risks; city services and civic habits both matter.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('मनसुनमा शहरी फोहोर व्यवस्थापन थप चुनौतीपूर्ण हुन्छ। नागरिक वाच डेस्कले महानगरका केही वडामा संकलन ढिलाइ र नाली थुप्रिएको अवस्था रेकर्ड गरेको छ।'),
        p('फोहोर खुला ठाउँमा जम्मा हुँदा पानीजन्य रोगको जोखिम बढ्छ। यो सार्वजनिक स्वास्थ्यको विषय हो।'),
        p('स्रोतमै जैविक र अजैविक छुट्याउने अभ्यासले संकलन सहज बनाउँछ।'),
        p('पारदर्शी ठेक्का र सेवा मापनले जवाफदेहिता बढाउँछ।'),
        h2('के सुधार्न सकिन्छ'),
        list([
          'वडास्तरको संकलन समयतालिका सार्वजनिक गर्नु',
          'निकास सफाइ प्राथमिकता तोक्नु',
          'घरधुरी स्रोतमै छुट्याउने अभ्यास बढाउनु',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Rain-clogged drains and piled waste raise health risks; city services and civic habits both matter.'),
      ],
    }),
    base({
      id: 'art-ed-society-3',
      slug: 'women-public-safety-transit',
      categorySlug: 'society',
      titleNe: 'सार्वजनिक यातायातमा महिला सुरक्षा: व्यवहारिक कदम',
      titleEn: 'Women safety on public transit: practical steps',
      deckNe: 'उजुरी संयन्त्र, प्रकाश व्यवस्था र चालक तालिम एकैपटक अघि बढ्नुपर्छ।',
      deckEn: 'Complaint channels, lighting and crew training must move together.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'featured',
      tagSlugs: ["editor-pick"],
      reportingLocation: 'ललितपुर',
      province: 'bagmati',
      bodyNe: [
        p('सार्वजनिक यातायातमा महिला सुरक्षा दीर्घकालीन बहस हो। नागरिक वाच डेस्कले यात्रु अनुभवलाई नीति सुधारसँग जोडेर हेर्छ।'),
        p('उजुरीपछिको प्रक्रिया अस्पष्ट हुँदा धेरै मौन बस्छन्।'),
        p('रातको रुटमा प्रकाश र भीड व्यवस्थापनले जोखिम घटाउन सक्छ।'),
        p('व्यवसायी र स्थानीय तहको सहकार्यबिना दिगो परिवर्तन गाह्रो हुन्छ।'),
        h2('तत्काल गर्न सकिने काम'),
        list([
          'हटलाइन र उजुरीको स्पष्ट प्रक्रिया',
          'बसपार्क र स्टपमा पर्याप्त प्रकाश',
          'तालिम र अनुगमनको सार्वजनिक सार',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Complaint channels, lighting and crew training must move together.'),
      ],
    }),
    base({
      id: 'art-ed-society-4',
      slug: 'rural-health-post-staffing',
      categorySlug: 'society',
      titleNe: 'ग्रामीण स्वास्थ्य चौकी: जनशक्ति अभाव र सेवा निरन्तरता',
      titleEn: 'Rural health posts: staffing gaps and continuity',
      deckNe: 'स्वास्थ्यकर्मी अभावले मातृशिशु सेवामा असर पर्छ। सरुवा, तालिम र औषधि आपूर्ति सँगै हेर्नुपर्छ।',
      deckEn: 'Staffing gaps hit maternal care; transfers, training and medicine supply must align.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["labour-migration"],
      reportingLocation: 'रुकुम',
      province: 'karnali',
      bodyNe: [
        p('दुर्गम स्वास्थ्य चौकीमा जनशक्ति अभाव पुरानो समस्या हो। नागरिक वाच डेस्कले सेवाग्राही कथा रेकर्ड गरेको छ।'),
        p('एकल कर्मीमा निर्भर इकाईमा बिदाले सेवा रोकिन सक्छ।'),
        p('औषधि आपूर्ति ढिला हुँदा निजी खर्च बढ्छ।'),
        p('तीनै तहको समन्वयबिना सुधार अधुरो रहन्छ।'),
        h2('सेवा निरन्तरताका सर्त'),
        list([
          'रिक्त दरबन्दीको सार्वजनिक सूची',
          'आकस्मिक औषधि बफर स्टक',
          'रेफरल यातायात तयारी',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Staffing gaps hit maternal care; transfers, training and medicine supply must align.'),
      ],
    }),
    base({
      id: 'art-ed-society-5',
      slug: 'community-disaster-preparedness-drills',
      categorySlug: 'society',
      titleNe: 'समुदायिक विपद् अभ्यास: पूर्वतयारी नै जीवनरक्षा',
      titleEn: 'Community disaster drills: preparedness saves lives',
      deckNe: 'जोखिमयुक्त बस्तीमा पूर्वअभ्यास, आपतकालीन झोला र सम्पर्क सूचीले क्षति घटाउन सक्छ।',
      deckEn: 'Drills, go-bags and contact lists can reduce harm in high-risk settlements.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      isFeatured: 'secondary',
      tagSlugs: ["climate"],
      reportingLocation: 'कास्की',
      province: 'gandaki',
      bodyNe: [
        p('विपद्पछि मात्र प्रतिक्रिया जनाउने शैली महँगो हुन्छ। नागरिक वाच डेस्कले अभ्यासलाई जीवनरक्षा लगानी मान्छ।'),
        p('विद्यालय र वडा मिलेर अभ्यास गर्दा बालबालिका तयार हुन्छन्।'),
        p('पूर्वसूचना स्थानीय भाषामा बुझिने हुनुपर्छ।'),
        p('महिला, वृद्ध र अपाङ्गता भएका व्यक्तिको आवश्यकता योजनामा देखिनुपर्छ।'),
        h2('परिवार स्तरको तयारी'),
        list([
          'आपतकालीन झोला र कागजात कपी',
          'छिमेकी सम्पर्क सूची',
          'निकासी मार्गको पूर्वजानकारी',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Drills, go-bags and contact lists can reduce harm in high-risk settlements.'),
      ],
    })
  ]
}
