import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionTechnology(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-technology-1',
      slug: 'digital-id-public-services',
      categorySlug: 'technology',
      titleNe: 'डिजिटल परिचय र सार्वजनिक सेवा: सहजता र सुरक्षा',
      titleEn: 'Digital ID and public services: ease with security',
      deckNe: 'अनलाइन सेवाले समय बचत गर्छ। डाटा सुरक्षा र अफलाइन विकल्प भने अनिवार्य छ।',
      deckEn: 'Online services save time; data security and offline options remain essential.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["data-story"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('डिजिटल सेवा विस्तार सकारात्मक छ। नागरिक वाच प्रविधि डेस्कले पहुँच र गोपनीयता सँगै हेर्छ।'),
        p('ग्रामीण इन्टरनेट अभावले असमानता बढाउँछ।'),
        p('फिसिङ चेतना अभियान चाहिन्छ।'),
        p('सरकारी एप अद्यावधिक र सरल हुनुपर्छ।'),
        h2('प्रयोगकर्ता अधिकार'),
        list([
          'सहमति स्पष्टता',
          'उजुरी मार्ग',
          'अफलाइन सेवा',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Online services save time; data security and offline options remain essential.'),
      ],
    }),
    base({
      id: 'art-ed-technology-2',
      slug: 'fintech-rural-access',
      categorySlug: 'technology',
      titleNe: 'फिनटेक ग्रामीण पहुँच: मोबाइल बैकिङको अर्को चरण',
      titleEn: 'Fintech rural access: next step for mobile banking',
      deckNe: 'भुक्तानी सजिलो बनाउँदा शुल्क पारदर्शिता र ग्राहक शिक्षा छुटाउनु हुँदैन।',
      deckEn: 'Easier payments still need clear fees and customer education.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["budget-2083"],
      reportingLocation: 'धनकुटा',
      bodyNe: [
        p('डिजिटल भुक्तानीले बजार चलायमान बनाउँछ। नागरिक वाच डेस्क दुरुपयोग जोखिम पनि देखाउँछ।'),
        p('महिला प्रयोगकर्ता तालिम प्रभावकारी हुन्छ।'),
        p('एजेन्ट नेटवर्क गुणस्तर मापनयोग्य बनाउनुपर्छ।'),
        p('नेटवर्क डाउन हुँदा वैकल्पिक प्रक्रिया चाहिन्छ।'),
        h2('विश्वासका सर्त'),
        list([
          'शुल्क देखिने',
          'लेनदेन रसीद',
          'ग्राहक सहयोग',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Easier payments still need clear fees and customer education.'),
      ],
    }),
    base({
      id: 'art-ed-technology-3',
      slug: 'cyber-hygiene-for-readers',
      categorySlug: 'technology',
      titleNe: 'साइबर स्वच्छता: पाठकका लागि व्यावहारिक गाइड',
      titleEn: 'Cyber hygiene: a practical reader guide',
      deckNe: 'पासवर्ड, फिसिङ लिंक र सार्वजनिक वाईफाई सावधानीले ठगी जोखिम घटाउँछ।',
      deckEn: 'Password habits, phishing caution and public Wi-Fi care cut fraud risk.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["exclusive-report"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('साइबर ठगी बढ्दो चिन्ता हो। नागरिक वाच डेस्कले जटिल शब्द बिना गाइड दिन्छ।'),
        p('परिवारका वृद्ध सदस्यलाई छुट्टै सघाउ चाहिन्छ।'),
        p('बैंक/सेवा प्रदायक अलर्ट पढ्ने बानी बसाल्नुहोस्।'),
        p('विद्यालयमा आधारभूत पाठ्यक्रम उपयोगी हुन्छ।'),
        h2('आजै गर्न सकिने'),
        list([
          'दुई चरणीय प्रमाणीकरण',
          'अपरिचित लिंक नखोल्ने',
          'सफ्टवेयर अद्यावधिक',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Password habits, phishing caution and public Wi-Fi care cut fraud risk.'),
      ],
    }),
    base({
      id: 'art-ed-technology-4',
      slug: 'ai-newsroom-ethics',
      categorySlug: 'technology',
      titleNe: 'एआई र न्यूजरुम नैतिकता: मानव सम्पादन अपरिहार्य',
      titleEn: 'AI and newsroom ethics: human editing stays essential',
      deckNe: 'औजारले गति बढाउन सक्छ। सत्यता जाँच र जवाफदेहिता मानव जिम्मेवारी नै रहन्छ।',
      deckEn: 'Tools can speed work; accuracy checks and accountability stay human.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('एआई बहस न्यूजरुमभित्र पनि छ। नागरिक वाच डेस्क मानव सम्पादनलाई केन्द्र मान्छ।'),
        p('अन्धो निर्भरताले त्रुटि फैलाउँछ।'),
        p('पाठकलाई प्रक्रिया बुझाउनु विश्वास हो।'),
        p('तालिम र नीति दुवै चाहिन्छ।'),
        h2('प्रयोग मापदण्ड'),
        list([
          'स्रोत प्रमाण',
          'पारदर्शी खुलासा',
          'सच्याइ प्रक्रिया',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Tools can speed work; accuracy checks and accountability stay human.'),
      ],
    }),
    base({
      id: 'art-ed-technology-5',
      slug: 'broadband-in-the-hills',
      categorySlug: 'technology',
      titleNe: 'पहाडी ब्रोडब्यान्ड: शिक्षा र स्वास्थ्यको पूर्वाधार',
      titleEn: 'Hill broadband as education and health infrastructure',
      deckNe: 'इन्टरनेट विलासिता होइन। दूरशिक्षा र टेलिमेडिसिनका लागि आधारभूत सेवा हो।',
      deckEn: 'Internet is basic infrastructure for remote learning and telemedicine.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["climate"],
      reportingLocation: 'सोल्खुम्बु',
      bodyNe: [
        p('पहाडी कनेक्टिभिटी असमान छ। नागरिक वाच डेस्कले यसलाई विकास सूचक मान्छ।'),
        p('केबल र वायरलेस मिश्रित समाधान चाहिन्छ।'),
        p('बिजुली आपूर्तिसँगै योजना बनाउनुपर्छ।'),
        p('स्थानीय प्राविधिक तालिम दिगोपन हो।'),
        h2('लगानी प्राथमिकता'),
        list([
          'विद्यालय कनेक्टिभिटी',
          'स्वास्थ्य चौकी लिंक',
          'मर्मत सम्झौता',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Internet is basic infrastructure for remote learning and telemedicine.'),
      ],
    })
  ]
}
