import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionVideo(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-video-1',
      slug: 'video-desk-how-we-work',
      categorySlug: 'video',
      titleNe: 'भिडियो डेस्क कसरी काम गर्छ: नागरिक वाच भित्र',
      titleEn: 'How the Nagarik Watch video desk works',
      deckNe: 'फिल्ड शटदेखि सम्पादनसम्मको प्रक्रिया। पारदर्शिता नै विश्वास।',
      deckEn: 'From field shots to edit: transparency builds trust.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["exclusive-report"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाच भिडियो डेस्कले आफ्नो कार्यशैली पाठकसामु खुलाएको छ।'),
        p('हतारमा गलत दृश्य नआओस् भनेर दोहोरो जाँच हुन्छ।'),
        p('सहमति बिना नजिकको अनुहार नदेखाउने नीति छ।'),
        p('मोबाइल पनि क्यामेरा हो, जिम्मेवारी उस्तै हो।'),
        h2('प्रक्रिया चरण'),
        list([
          'पाइच',
          'फिल्ड सुरक्षा',
          'सम्पादन जाँच',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('From field shots to edit: transparency builds trust.'),
      ],
    }),
    base({
      id: 'art-ed-video-2',
      slug: 'live-blog-vs-video-explainers',
      categorySlug: 'video',
      titleNe: 'लाइभ ब्लग र भिडियो व्याख्या: कहिले कुन?',
      titleEn: 'Live blogs vs video explainers: when to use which',
      deckNe: 'तत्काल अद्यावधिक ब्लगमा, बुझाइ भिडियोमा बलियो हुन्छ।',
      deckEn: 'Use blogs for rapid updates and video for clearer explanation.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: [],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाच डेस्क ढाँचा छनोटलाई पाठक हितमा जोड्छ।'),
        p('मनसुन अलर्टमा छोटो भिडियो उपयोगी हुन्छ।'),
        p('लाइभ ब्लगले समयरेखा दिन्छ।'),
        p('दुवैमा स्रोत स्पष्टता अनिवार्य छ।'),
        h2('सम्पादकीय छनोट'),
        list([
          'इन्टरनेट लागत',
          'दृश्य आवश्यकता',
          'सच्याइ सजिलो',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Use blogs for rapid updates and video for clearer explanation.'),
      ],
    }),
    base({
      id: 'art-ed-video-3',
      slug: 'monsoon-alert-on-camera',
      categorySlug: 'video',
      titleNe: 'क्यामेरामा मनसुन सतर्कता: देखिने चेतावनी',
      titleEn: 'Monsoon alerts on camera: visible warnings',
      deckNe: 'नक्सा र सरल भाषा भिडियोले जोखिम बुझाउन सघाउँछ।',
      deckEn: 'Maps and plain language on video help people grasp risk.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'secondary',
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाचले मौसम सतर्कता भिडियोलाई सेवा मान्छ।'),
        p('डर फैलाउने संगीत प्रयोग हुँदैन।'),
        p('उपशीर्षक नेपालीमा हुन्छ।'),
        p('पुनःप्रसारण समय तोकिएको हुन्छ।'),
        h2('उत्पादन सुझाव'),
        list([
          'ठूलो फन्ट',
          'स्थानीय उदाहरण',
          'कल टु एक्शन',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Maps and plain language on video help people grasp risk.'),
      ],
    }),
    base({
      id: 'art-ed-video-4',
      slug: 'short-form-news-ethics',
      categorySlug: 'video',
      titleNe: 'छोटो भिडियो समाचार नैतिकता',
      titleEn: 'Ethics for short-form news video',
      deckNe: 'क्लिप भाइरल हुँदैमा सन्दर्भ काट्नु हुँदैन।',
      deckEn: 'Virality does not justify cutting away context.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      tagSlugs: ["editor-pick"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('छोटो ढाँचाले ध्यान तान्छ। नागरिक वाच डेस्क सन्दर्भ जोगाउने वचनबद्ध छ।'),
        p('सच्याइ नोट पिन गरिन्छ।'),
        p('थम्बनेल भ्रामक नहोस्।'),
        p('टिम तालिम नियमित छ।'),
        h2('लाल रेखा'),
        list([
          'हिंसा ग्लोरिफाइ नगर्ने',
          'बालबालिका पहिचान',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Virality does not justify cutting away context.'),
      ],
    }),
    base({
      id: 'art-ed-video-5',
      slug: 'archive-digitization-video',
      categorySlug: 'video',
      titleNe: 'भिडियो अभिलेख डिजिटाइजेसन: स्मृति जोगाउने काम',
      titleEn: 'Digitizing the video archive to keep memory',
      deckNe: 'पुराना टेप र फाइल व्यवस्थित भए इतिहास खोज्न सकिन्छ।',
      deckEn: 'Ordered tapes and files make history searchable.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["data-story"],
      reportingLocation: 'काठमाडौं',
      bodyNe: [
        p('नागरिक वाचले आफ्नो भिडियो स्मृति व्यवस्थित गर्दैछ।'),
        p('यसले तथ्य जाँचमा पनि सहयोग गर्छ।'),
        p('कपीराइट र अनुमति ध्यानमा छ।'),
        p('पाठक विशेष कथा श्रृंखला आउनेछ।'),
        h2('अभिलेख प्राथमिकता'),
        list([
          'मेटाडेटा',
          'ब्याकअप',
          'सार्वजनिक पहुँच तह',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Ordered tapes and files make history searchable.'),
      ],
    })
  ]
}
