import type { StoredArticle } from '../json-store'
import { base, p, h2, list, isoDaysAgo } from './_helpers'

export function editionWorld(): StoredArticle[] {
  return [
    base({
      id: 'art-ed-world-1',
      slug: 'west-asia-energy-shock-nepal-lens',
      categorySlug: 'world',
      titleNe: 'पश्चिम एशिया ऊर्जा तनाव: नेपाली अर्थतन्त्रको लेन्स',
      titleEn: 'West Asia energy tension through a Nepal lens',
      deckNe: 'वैश्विक इन्धन मूल्य उकालो लाग्दा आयात बिल र यातायात खर्चमा चाप पर्छ। तयारी र पारदर्शिता चाहिन्छ।',
      deckEn: 'Global fuel spikes hit import bills and transport costs; preparation and transparency matter.',
      publishedAt: isoDaysAgo(0, 7),
      updatedAt: isoDaysAgo(0, 7),
      isFeatured: 'lead',
      tagSlugs: ["geopolitics"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('वैश्विक ऊर्जा तनाव टाढाको समाचार होइन। नागरिक वाच विश्व डेस्कले यसलाई घरेलु लागतसँग जोडेर हेर्छ।'),
        p('अफवाहले बजार बिगार्छ। आधिकारिक तथ्यांक नियमित आउनुपर्छ।'),
        p('ऊर्जा विविधीकरण दीर्घकालीन सुरक्षा हो।'),
        p('पाठकलाई सरल व्याख्या प्राथमिकता हुनेछ।'),
        h2('नेपालले हेर्नुपर्ने पक्ष'),
        list([
          'इन्धन मौज्दात स्थिति',
          'सार्वजनिक यातायात विकल्प',
          'मूल्य समायोजन प्रक्रिया',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Global fuel spikes hit import bills and transport costs; preparation and transparency matter.'),
      ],
    }),
    base({
      id: 'art-ed-world-2',
      slug: 'south-asia-monsoon-regional-picture',
      categorySlug: 'world',
      titleNe: 'दक्षिण एसिया मनसुन: क्षेत्रीय तस्बिर र साझा जोखिम',
      titleEn: 'South Asia monsoon: shared regional risks',
      deckNe: 'वर्षा प्रणाली सिमाना पार गर्छ। बाढी पूर्वसूचना सहकार्यले क्षति घटाउन सक्छ।',
      deckEn: 'Rain systems cross borders; flood warning cooperation can cut losses.',
      publishedAt: isoDaysAgo(1, 8),
      updatedAt: isoDaysAgo(1, 8),
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('मनसुन क्षेत्रीय घटना हो। नागरिक वाच डेस्कले नदी र बाढी जोखिमलाई साझा चुनौती मान्छ।'),
        p('डाटा आदानप्रदान ढिला हुँदा तयारी कमजोर हुन्छ।'),
        p('कृषकलाई मौसम सार समयमै चाहिन्छ।'),
        p('जलवायु अनुकूलन बजेट प्राथमिकतामा पर्नुपर्छ।'),
        h2('सहकार्यका क्षेत्र'),
        list([
          'नदी प्रवाह आदानप्रदान',
          'पूर्वसूचना भाषा सरलता',
          'सीमावर्ती राहत समन्वय',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Rain systems cross borders; flood warning cooperation can cut losses.'),
      ],
    }),
    base({
      id: 'art-ed-world-3',
      slug: 'remittance-corridors-global-context',
      categorySlug: 'world',
      titleNe: 'विप्रेषण करिडोर: विश्व श्रम बजारको सन्दर्भ',
      titleEn: 'Remittance corridors in the global labour market',
      deckNe: 'गन्तव्य मुलुकको नीति फेरिँदा नेपाली परिवारको आय प्रभावित हुन्छ। सूचना पहुँच महत्त्वपूर्ण छ।',
      deckEn: 'Destination policy shifts affect Nepali household income; information access matters.',
      publishedAt: isoDaysAgo(2, 9),
      updatedAt: isoDaysAgo(2, 9),
      isFeatured: 'featured',
      tagSlugs: ["labour-migration"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('श्रम प्रवास विश्व श्रम बजारसँग जोडिएको छ। नागरिक वाच डेस्कले करिडोर जोखिम पाठकलाई बुझाउँछ।'),
        p('अनौपचारिक दलाली महँगो र जोखिमपूर्ण हुन्छ।'),
        p('सीप प्रमाणीकरणले रोजगारी सुरक्षा बढाउँछ।'),
        p('महिला कामदार सुरक्षा अलग प्राथमिकता हो।'),
        h2('परिवारले जान्नुपर्ने'),
        list([
          'कानुनी कामदार मार्ग',
          'शुल्क पारदर्शिता',
          'गुनासो संयन्त्र',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Destination policy shifts affect Nepali household income; information access matters.'),
      ],
    }),
    base({
      id: 'art-ed-world-4',
      slug: 'climate-summit-prep-reader-brief',
      categorySlug: 'world',
      titleNe: 'जलवायु सम्मेलन तयारी: पाठक ब्रिफ',
      titleEn: 'Climate summit prep: a reader brief',
      deckNe: 'सम्मेलनका वाचा घरेलु नीतिमा झर्दा मात्र अर्थ राख्छन्। अनुकूलन र वित्त दुवै हेर्नुपर्छ।',
      deckEn: 'Summit pledges matter when they land in domestic policy on adaptation and finance.',
      publishedAt: isoDaysAgo(3, 10),
      updatedAt: isoDaysAgo(3, 10),
      isFeatured: 'secondary',
      tagSlugs: ["climate"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('जलवायु कूटनीति जटिल लाग्न सक्छ। नागरिक वाच डेस्कले यसलाई स्थानीय प्रभावमा अनुवाद गर्छ।'),
        p('अनुकूलन आयोजना ढिलाइले क्षति बढाउँछ।'),
        p('युवा आवाज नीति छलफलमा सुनिनुपर्छ।'),
        p('पारदर्शी प्रतिवेदनले विश्वास जन्माउँछ।'),
        h2('नेपालका प्राथमिकता'),
        list([
          'हिमाली जोखिम',
          'कृषि बीमा',
          'हरित वित्त पहुँच',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Summit pledges matter when they land in domestic policy on adaptation and finance.'),
      ],
    }),
    base({
      id: 'art-ed-world-5',
      slug: 'human-rights-displacement-context',
      categorySlug: 'world',
      titleNe: 'विस्थापन र मानव अधिकार: विश्व सन्दर्भको पाठ',
      titleEn: 'Displacement and human rights: a global context lesson',
      deckNe: 'संघर्ष र विपद्ले मानिस विस्थापित हुँदा अन्तर्राष्ट्रिय मापदण्ड र स्थानीय तयारी दुवै जाँच्नुपर्छ।',
      deckEn: 'Conflict and disaster displacement test international standards and local readiness.',
      publishedAt: isoDaysAgo(4, 6),
      updatedAt: isoDaysAgo(4, 6),
      tagSlugs: ["geopolitics"],
      reportingLocation: 'काठमाडौं',
      province: 'bagmati',
      bodyNe: [
        p('विस्थापनको समाचार संख्यामा मात्र सीमित हुनुहुँदैन। नागरिक वाच डेस्क मानवीय मापदण्डमा जोड दिन्छ।'),
        p('महिला र बालबालिका जोखिममा बढी पर्छन्।'),
        p('मिडियाले गरिमा जोगाएर रिपोर्ट गर्नुपर्छ।'),
        p('नेपालको आफ्नै विपद् अनुभवले सहानुभूति मात्र होइन, तयारी पाठ दिन्छ।'),
        h2('पाठकका लागि मुख्य बुँदा'),
        list([
          'सुरक्षित आश्रय',
          'सूचना पहुँच',
          'बालबालिका संरक्षण',
        ]),
        p('नागरिक वाच डेस्कले यस विषयलाई निरन्तर अनुगमन गरी पाठकमैत्री सार अद्यावधिक गर्नेछ।'),
      ],
      bodyEn: [
        p('Conflict and disaster displacement test international standards and local readiness.'),
      ],
    })
  ]
}
