/**
 * Honest algorithm / capability catalog for the newsroom admin surface.
 *
 * Status meanings:
 *   live      — exported, called from a real surface, covered by tests or production traffic path
 *   partial   — real code exists but missing data, model, or full product wiring
 *   scaffold  — types/helpers/hooks exist; not a production algorithm yet
 *   blocked   — cannot be honestly completed without vendors, partners, or stack migration
 *   planned   — specified, not started
 */

export type AlgorithmStatus = 'live' | 'partial' | 'scaffold' | 'blocked' | 'planned'

export type AlgorithmCategory =
  | 'ranking'
  | 'recommendation'
  | 'search'
  | 'nlp'
  | 'notifications'
  | 'community'
  | 'trust'
  | 'growth'
  | 'revenue'
  | 'performance'
  | 'infrastructure'
  | 'retention'
  | 'advertising'
  | 'experimentation'
  | 'distribution'
  | 'security'
  | 'syndication'
  | 'epaper'

export type AlgorithmEntry = {
  id: string
  number: number
  label: string
  category: AlgorithmCategory
  surface: string
  status: AlgorithmStatus
  summary: string
  implementation?: string
  dependency?: string
  /** Editorial priority 1 = ship first for a Nepal civic portal. */
  priority: number
}

export const ALGORITHM_CATALOG: readonly AlgorithmEntry[] = [
  // Ranking 1–8
  {
    id: 'weighted-scoring-ranker',
    number: 1,
    label: 'Weighted Scoring Ranker',
    category: 'ranking',
    surface: 'homepage / category / trending',
    status: 'live',
    summary: 'Combines editorial priority, decay, engagement, affinity, and trust into one score.',
    implementation: 'apps/web/lib/ranking.ts#weightedScore',
    priority: 1,
  },
  {
    id: 'time-decay-ranking',
    number: 2,
    label: 'Time Decay Algorithm',
    category: 'ranking',
    surface: 'latest / breaking',
    status: 'live',
    summary:
      'Age-penalizes stories so fresh news outranks stale evergreen unless engagement compensates.',
    implementation: 'apps/web/lib/ranking.ts#timeDecayScore',
    priority: 1,
  },
  {
    id: 'trending-detection',
    number: 3,
    label: 'Trending Detection',
    category: 'ranking',
    surface: 'trending pages / admin live',
    status: 'partial',
    summary:
      'Uses read, approved-comment, share, and bookmark samples for velocity/burst detection; remains partial until sustained traffic establishes stable baselines.',
    implementation: 'packages/db/src/trending.ts + apps/web/lib/engagement/store.ts#getTrendingSamples',
    priority: 1,
  },
  {
    id: 'velocity-ranking',
    number: 4,
    label: 'Velocity Ranking',
    category: 'ranking',
    surface: 'ranking engine',
    status: 'live',
    summary: 'Scores short-window engagement growth versus baseline.',
    implementation: 'apps/web/lib/ranking.ts#velocityScore',
    priority: 2,
  },
  {
    id: 'burst-detection',
    number: 5,
    label: 'Burst Detection',
    category: 'ranking',
    surface: 'elections / disasters / sports finals',
    status: 'live',
    summary: 'Flags ≥5× baseline short-window traffic as a burst.',
    implementation: 'apps/web/lib/ranking.ts#burstScore',
    priority: 2,
  },
  {
    id: 'multi-armed-bandit',
    number: 6,
    label: 'Multi-Armed Bandit',
    category: 'ranking',
    surface: 'homepage exploration',
    status: 'partial',
    summary:
      'UCB1 exploration uses ranking-event CTR; experiment assignment/store is live, but homepage slot arms are not yet fully attributed.',
    implementation: 'apps/web/lib/ranking.ts#banditExplorationScore + apps/web/lib/experiments',
    priority: 3,
  },
  {
    id: 'bayesian-ranking',
    number: 7,
    label: 'Bayesian Ranking',
    category: 'ranking',
    surface: 'CTR / low-sample correction',
    status: 'live',
    summary: 'Prior-smoothed CTR prevents 10/10 from beating 9k/10k.',
    implementation: 'apps/web/lib/ranking.ts#bayesianAverage',
    priority: 1,
  },
  {
    id: 'wilson-score-ranking',
    number: 8,
    label: 'Wilson Score Ranking',
    category: 'community',
    surface: 'comments / reputation',
    status: 'live',
    summary: 'Wilson lower bound for upvotes and approve/reject history.',
    implementation: 'packages/db/src/moderation.ts#wilsonScore',
    priority: 2,
  },

  // Recommendations 9–16
  {
    id: 'content-based-filtering',
    number: 9,
    label: 'Content-Based Filtering',
    category: 'recommendation',
    surface: 'related stories / for-you',
    status: 'live',
    summary: 'Cosine similarity over category/tag/author/title terms.',
    implementation: 'packages/db/src/recommend.ts#contentBasedScore',
    priority: 1,
  },
  {
    id: 'collaborative-filtering',
    number: 10,
    label: 'Collaborative Filtering',
    category: 'recommendation',
    surface: 'for-you',
    status: 'partial',
    summary: 'Pure item-item co-read baseline exists; production use remains volume-gated.',
    implementation: 'packages/db/src/cf.ts#coReadRecommend',
    dependency: 'Consent-aware event store + enough active readers',
    priority: 4,
  },
  {
    id: 'matrix-factorization',
    number: 11,
    label: 'Matrix Factorization',
    category: 'recommendation',
    surface: 'offline recommender training',
    status: 'planned',
    summary: 'Advanced collaborative model; not justified until CF baseline exists.',
    dependency: 'Offline training job + interaction logs',
    priority: 5,
  },
  {
    id: 'knn-recommendation',
    number: 12,
    label: 'k-NN Recommendation',
    category: 'recommendation',
    surface: 'for-you',
    status: 'partial',
    summary: 'Exact cosine k-NN baseline exists for small caller-supplied interest vectors; no production ANN index.',
    implementation: 'packages/db/src/cf.ts#knnRecommend',
    dependency: 'Interaction vectors',
    priority: 4,
  },
  {
    id: 'embedding-similarity',
    number: 13,
    label: 'Embedding Similarity',
    category: 'recommendation',
    surface: 'related / semantic modules',
    status: 'planned',
    summary: 'Vector embeddings + cosine ANN.',
    dependency: 'Embedding provider or local model + vector index',
    priority: 4,
  },
  {
    id: 'session-based-recommendation',
    number: 14,
    label: 'Session-Based Recommendation',
    category: 'recommendation',
    surface: 'sidebar / article end',
    status: 'live',
    summary: 'Uses the last few reads in-session to steer next suggestions.',
    implementation: 'packages/db/src/recommend.ts#sessionBasedScore',
    priority: 1,
  },
  {
    id: 'sequential-prediction',
    number: 15,
    label: 'Sequential Prediction',
    category: 'recommendation',
    surface: 'next-click',
    status: 'partial',
    summary: 'Recent category transitions provide a transparent Markov-ish next-category boost; no trained sequence model.',
    implementation: 'packages/db/src/recommend.ts#nextCategoryScore',
    priority: 5,
  },
  {
    id: 'hybrid-recommender',
    number: 16,
    label: 'Hybrid Recommender',
    category: 'recommendation',
    surface: 'saved / recommended modules',
    status: 'live',
    summary:
      'nw-hybrid-v3 blends content, session sequence, freshness, follows, editorial, and optional volume-gated co-read signals with fatigue guards.',
    implementation: 'packages/db/src/recommend.ts#recommend',
    priority: 1,
  },

  // Search 17–23
  {
    id: 'tf-idf',
    number: 17,
    label: 'TF-IDF',
    category: 'search',
    surface: 'search (legacy baseline)',
    status: 'partial',
    summary:
      'Superseded as primary ranker by BM25; term weighting concepts remain in field boosts.',
    implementation: 'apps/web/lib/search.ts',
    priority: 3,
  },
  {
    id: 'bm25-search',
    number: 18,
    label: 'BM25 Search',
    category: 'search',
    surface: 'search bar / search page',
    status: 'live',
    summary: 'Fielded BM25 over title/deck/author/category with AND semantics.',
    implementation: 'apps/web/lib/search.ts#search',
    priority: 1,
  },
  {
    id: 'inverted-index',
    number: 19,
    label: 'Inverted Index',
    category: 'search',
    surface: 'search retrieval',
    status: 'live',
    summary: 'Posting lists map terms to document field frequencies.',
    implementation: 'apps/web/lib/search.ts#buildIndex',
    priority: 1,
  },
  {
    id: 'fuzzy-matching',
    number: 20,
    label: 'Fuzzy Matching',
    category: 'search',
    surface: 'search bar',
    status: 'live',
    summary: 'Latin typo recovery via capped Levenshtein against vocabulary.',
    implementation: 'apps/web/lib/search.ts#fuzzyExpandTerm',
    priority: 2,
  },
  {
    id: 'autocomplete-trie',
    number: 21,
    label: 'Autocomplete Trie',
    category: 'search',
    surface: 'search suggestions',
    status: 'live',
    summary: 'Prefix trie over titles, authors, and categories.',
    implementation: 'apps/web/lib/search.ts#autocomplete',
    priority: 2,
  },
  {
    id: 'semantic-search',
    number: 22,
    label: 'Semantic Search',
    category: 'search',
    surface: 'search',
    status: 'planned',
    summary: 'Meaning-based retrieval for paraphrases.',
    dependency: 'Embeddings + ANN index',
    priority: 4,
  },
  {
    id: 'query-expansion',
    number: 23,
    label: 'Query Expansion',
    category: 'search',
    surface: 'search',
    status: 'live',
    summary:
      'Editorial Nepali↔English civic lexicon expands queries at a lower boost than exact/fuzzy matches.',
    implementation: 'apps/web/lib/search-lexicon.ts + apps/web/lib/search.ts#expandQueryTerm',
    priority: 2,
  },

  // NLP 24–32
  {
    id: 'named-entity-recognition',
    number: 24,
    label: 'Named Entity Recognition',
    category: 'nlp',
    surface: 'article pipeline',
    status: 'partial',
    summary: 'Small Nepal civic gazetteer extracts known people, organizations and places; no statistical NER model.',
    implementation: 'apps/web/lib/nlp/gazetteer.ts#extractEntities',
    dependency: 'Broader maintained entity registry or NER model',
    priority: 3,
  },
  {
    id: 'topic-classification',
    number: 25,
    label: 'Topic Classification',
    category: 'nlp',
    surface: 'ingest / CMS assist',
    status: 'partial',
    summary: 'Manual taxonomy live; auto-classifier not shipped.',
    priority: 3,
  },
  {
    id: 'sentiment-analysis',
    number: 26,
    label: 'Sentiment Analysis',
    category: 'nlp',
    surface: 'comments / opinion',
    status: 'planned',
    summary: 'Useful for moderation assist; not a publish gate.',
    priority: 4,
  },
  {
    id: 'summarization',
    number: 27,
    label: 'Summarization',
    category: 'nlp',
    surface: 'mobile cards / editor assist',
    status: 'partial',
    summary: 'Extractive draft summaries are wired into the journalist desk with explicit editor acceptance.',
    implementation: 'apps/web/lib/ai/index.ts#draftSummary + apps/web/app/api/journalist/ai/route.ts',
    priority: 2,
  },
  {
    id: 'keyword-extraction',
    number: 28,
    label: 'Keyword Extraction',
    category: 'nlp',
    surface: 'journalist desk / taxonomy assist',
    status: 'partial',
    summary: 'Frequency-based draft tags are wired to the journalist desk and only apply after editor acceptance.',
    implementation: 'apps/web/lib/ai/index.ts#draftTags + apps/web/components/journalist/JournalistArticleDraftForm.tsx',
    priority: 3,
  },
  {
    id: 'topic-modeling-lda',
    number: 29,
    label: 'Topic Modeling (LDA)',
    category: 'nlp',
    surface: 'analytics',
    status: 'planned',
    summary: 'Hidden theme discovery for newsroom analytics.',
    priority: 5,
  },
  {
    id: 'clustering',
    number: 30,
    label: 'Clustering',
    category: 'nlp',
    surface: 'wire dedupe',
    status: 'planned',
    summary: 'Group similar agency copy.',
    priority: 4,
  },
  {
    id: 'duplicate-detection',
    number: 31,
    label: 'Duplicate Detection',
    category: 'nlp',
    surface: 'editorial backend',
    status: 'live',
    summary: 'Jaccard near-duplicate pairs for editor investigation.',
    implementation: 'apps/web/lib/ai/index.ts#detectDuplicates',
    priority: 2,
  },
  {
    id: 'headline-generator',
    number: 32,
    label: 'Headline Generator',
    category: 'nlp',
    surface: 'editor assist',
    status: 'partial',
    summary: 'Extractive headline seeds are wired to the journalist desk; editors choose a candidate explicitly.',
    implementation: 'apps/web/lib/ai/index.ts#draftHeadlines + apps/web/components/journalist/JournalistArticleDraftForm.tsx',
    priority: 3,
  },

  // Notifications / community / trust / growth / revenue 33–50
  {
    id: 'notification-priority-scoring',
    number: 33,
    label: 'Notification Priority Scoring',
    category: 'notifications',
    surface: 'push / email',
    status: 'live',
    summary: 'Urgency×preference scoring ranks delivery candidates before push fan-out.',
    implementation:
      'packages/db/src/notify.ts#scoreNotification + apps/web/lib/notifications/subscriptions.ts',
    priority: 2,
  },
  {
    id: 'send-time-optimization',
    number: 34,
    label: 'Send-Time Optimization',
    category: 'notifications',
    surface: 'newsletter / push',
    status: 'planned',
    summary: 'Requires delivery provider + open/click feedback loop.',
    dependency: 'Newsletter provider worker',
    priority: 4,
  },
  {
    id: 'fatigue-prevention',
    number: 35,
    label: 'Fatigue Prevention',
    category: 'notifications',
    surface: 'recommendations / push',
    status: 'live',
    summary:
      'Recommend fatigue windows and push maxPerDay/cooldown caps gate delivery before provider send.',
    implementation: 'packages/db/src/recommend.ts + packages/db/src/notify.ts',
    priority: 2,
  },
  {
    id: 'toxicity-detection',
    number: 36,
    label: 'Toxicity Detection',
    category: 'community',
    surface: 'comment moderation',
    status: 'live',
    summary:
      'Unicode-normalized lexical scorer with admin+env policy list; token-aware Latin matching; reputation-gated hide/reject.',
    implementation:
      'packages/db/src/moderation.ts + apps/web/lib/admin-settings.ts#getModerationBannedWords',
    priority: 1,
  },
  {
    id: 'spam-detection',
    number: 37,
    label: 'Spam Detection',
    category: 'community',
    surface: 'comment moderation',
    status: 'live',
    summary:
      'Spam heuristics score every new comment and can auto-flag or reject before the human queue.',
    implementation: 'apps/web/lib/engagement/store.ts#createComment',
    priority: 1,
  },
  {
    id: 'troll-probability',
    number: 38,
    label: 'Troll Probability',
    category: 'community',
    surface: 'moderation',
    status: 'planned',
    summary: 'Behavioral analysis across threads; needs history features.',
    priority: 4,
  },
  {
    id: 'comment-ranking',
    number: 39,
    label: 'Comment Ranking',
    category: 'community',
    surface: 'article comments',
    status: 'live',
    summary: 'Wilson + recency blend for display order.',
    implementation: 'packages/db/src/moderation.ts#rankComment',
    priority: 2,
  },
  {
    id: 'reputation-score',
    number: 40,
    label: 'Reputation Score',
    category: 'community',
    surface: 'moderation',
    status: 'live',
    summary: 'Wilson on approve/reject history; new users start neutral.',
    implementation: 'packages/db/src/moderation.ts#reputationScore',
    priority: 2,
  },
  {
    id: 'source-reliability-score',
    number: 41,
    label: 'Source Reliability Score',
    category: 'trust',
    surface: 'editorial backend',
    status: 'partial',
    summary: 'Flag set only — editors own verdicts.',
    implementation: 'packages/db/src/moderation.ts#sourceReliabilityFlags',
    priority: 2,
  },
  {
    id: 'fact-consistency-check',
    number: 42,
    label: 'Fact Consistency Check',
    category: 'trust',
    surface: 'editorial backend',
    status: 'scaffold',
    summary: 'Claim scaffold for humans; no automated cross-source verdicts.',
    implementation: 'apps/web/lib/ai/index.ts#draftFactCheckScaffold',
    priority: 3,
  },
  {
    id: 'misinformation-pattern-detection',
    number: 43,
    label: 'Misinformation Pattern Detection',
    category: 'trust',
    surface: 'editorial backend',
    status: 'planned',
    summary: 'Needs labelled dataset + model; wrappers deferred deliberately.',
    priority: 4,
  },
  {
    id: 'bot-traffic-detection',
    number: 44,
    label: 'Bot Traffic Detection',
    category: 'trust',
    surface: 'analytics / ads integrity',
    status: 'planned',
    summary: 'Rate limits exist; behavioral bot scoring does not.',
    priority: 3,
  },
  {
    id: 'churn-prediction',
    number: 45,
    label: 'Churn Prediction',
    category: 'growth',
    surface: 'analytics',
    status: 'planned',
    summary: 'Requires stable identity + return visits over weeks.',
    priority: 4,
  },
  {
    id: 'ltv-prediction',
    number: 46,
    label: 'LTV Prediction',
    category: 'growth',
    surface: 'admin live / recommendations',
    status: 'scaffold',
    summary: 'Monetary LTV requires payments; see ltv-engagement-score for the live heuristic.',
    dependency: 'Payment + entitlement data',
    priority: 3,
  },
  {
    id: 'ltv-engagement-score',
    number: 175,
    label: 'LTV / Engagement Score',
    category: 'growth',
    surface: 'admin live panel and recommendations',
    status: 'live',
    summary: 'Dwell/completion/share/bookmark heuristic used in ranking — not revenue LTV.',
    implementation: 'apps/web/lib/ranking.ts#ltvEngagementScore',
    priority: 2,
  },
  {
    id: 'virality-prediction',
    number: 47,
    label: 'Virality Prediction (Heuristic)',
    category: 'growth',
    surface: 'homepage / social desk',
    status: 'scaffold',
    summary: 'Bounded share/comment velocity heuristic exists; no predictive model is claimed.',
    implementation: 'apps/web/lib/ranking.ts#viralityScore',
    priority: 4,
  },
  {
    id: 'ab-testing-algorithm',
    number: 48,
    label: 'A/B Testing Algorithm',
    category: 'experimentation',
    surface: 'headline / layout experiments',
    status: 'live',
    summary:
      'Deterministic assignment + Bayesian analysis; public homepage exposure and article-completion conversion are consented client events.',
    implementation:
      'apps/web/lib/experiments + apps/web/components/experiments/ExperimentExposure.tsx',
    priority: 2,
  },
  {
    id: 'dynamic-paywall',
    number: 49,
    label: 'Dynamic Paywall Algorithm',
    category: 'revenue',
    surface: 'article gate',
    status: 'partial',
    summary: 'Manual/premium gate live; behavioral meter not personalized yet.',
    implementation: 'apps/web/lib/membership.ts + paywall admin',
    dependency: 'Payment provider for true dynamic offers',
    priority: 2,
  },
  {
    id: 'ad-yield-optimization',
    number: 50,
    label: 'Ad Targeting / Yield Optimization',
    category: 'revenue',
    surface: 'ad stack',
    status: 'scaffold',
    summary: 'House ads + placement audit; no auction yield optimizer.',
    priority: 3,
  },

  // High-value performance / retention / security samples that are code-actionable
  {
    id: 'swr-service-worker',
    number: 110,
    label: 'Stale-While-Revalidate Service Worker',
    category: 'performance',
    surface: 'PWA',
    status: 'live',
    summary:
      'Article navigations serve cached HTML immediately, revalidate in background, and fall back to the offline shell with a 30-article cap.',
    implementation: 'apps/web/app/sw.js/route.ts + apps/web/lib/pwa/offline-cache.ts',
    priority: 2,
  },
  {
    id: 'circuit-breaker',
    number: 131,
    label: 'Circuit Breaker Pattern',
    category: 'infrastructure',
    surface: 'live widgets / third-party fetches',
    status: 'live',
    summary: 'Stops cascading failures when weather, AQI, forex, or NEPSE upstreams fail.',
    implementation: 'apps/web/lib/resilience/circuit-breaker.ts#execCircuit',
    priority: 2,
  },
  {
    id: 'save-data-detection',
    number: 142,
    label: 'Save-Data Header Detection',
    category: 'retention',
    surface: 'public pages',
    status: 'live',
    summary: 'Detect data-saver requests and reduce decorative public-page effects.',
    implementation: 'apps/web/lib/request/save-data.ts',
    priority: 2,
  },
  {
    id: 'continue-reading-restore',
    number: 139,
    label: 'Continue-Reading Position Restore',
    category: 'retention',
    surface: 'article page',
    status: 'live',
    summary:
      'Restores prior scroll depth for unfinished articles when personalization consent is granted.',
    implementation: 'apps/web/components/reader/ReaderArticleControls.tsx',
    priority: 2,
  },
  {
    id: 'ads-txt-sellers-json',
    number: 164,
    label: 'Ads.txt / Sellers.json Verification',
    category: 'advertising',
    surface: 'public trust files',
    status: 'live',
    summary: 'Publish honest, environment-configurable advertiser trust files.',
    implementation: 'apps/web/app/ads.txt/route.ts',
    priority: 2,
  },
  {
    id: 'token-bucket-rate-limiting',
    number: 197,
    label: 'Per-Endpoint Token-Bucket Rate Limiting',
    category: 'security',
    surface: 'public write APIs',
    status: 'live',
    summary: 'Postgres-backed counters in production; memory fallback in local dev.',
    implementation: 'apps/web/lib/rate-limit.ts',
    priority: 1,
  },
  {
    id: 'resumability-qwik',
    number: 116,
    label: 'Resumability Architecture (Qwik-style)',
    category: 'performance',
    surface: 'framework',
    status: 'blocked',
    summary: 'Conflicts with the Next/React architecture decision. Prefer RSC islands instead.',
    dependency: 'Framework migration — rejected',
    priority: 5,
  },
  {
    id: 'data-clean-room',
    number: 157,
    label: 'Data Clean Room Matching',
    category: 'advertising',
    surface: 'advertiser matching',
    status: 'blocked',
    summary: 'Requires enterprise clean-room vendor and legal agreements.',
    dependency: 'External clean-room partner',
    priority: 5,
  },
  {
    id: 'apple-news-format',
    number: 216,
    label: 'Apple News Format Feed',
    category: 'syndication',
    surface: 'Apple News',
    status: 'blocked',
    summary:
      'ANF generation must wait for stable partner-feed infrastructure and an approved Apple Publisher account.',
    dependency: 'Stable partner feeds + Apple Publisher account',
    priority: 4,
  },
  {
    id: 'epaper-replica',
    number: 228,
    label: 'Print-to-Digital Layout Conversion',
    category: 'epaper',
    surface: 'e-paper edition',
    status: 'planned',
    summary: 'Paginated replica edition — separate product module.',
    priority: 4,
  },

  // Performance 101–125
  {
    id: 'edge-rendered-ttfb',
    number: 101,
    label: 'Edge-Rendered TTFB Reduction',
    category: 'performance',
    surface: 'public HTML delivery',
    status: 'planned',
    summary: 'Move suitable public rendering closer to Nepal readers after measuring origin TTFB.',
    dependency: 'Edge runtime compatibility and deployment configuration',
    priority: 2,
  },
  {
    id: 'critical-css-inlining',
    number: 102,
    label: 'Critical CSS Extraction & Inlining',
    category: 'performance',
    surface: 'public pages',
    status: 'planned',
    summary:
      'Inline measured above-the-fold styles without duplicating the full global stylesheet.',
    priority: 3,
  },
  {
    id: 'route-code-splitting',
    number: 103,
    label: 'Route-Based Code Splitting',
    category: 'performance',
    surface: 'Next.js application',
    status: 'partial',
    summary: 'App Router provides route chunks, but no route-by-route bundle budget is enforced.',
    implementation: 'apps/web/app',
    priority: 2,
  },
  {
    id: 'tree-shaking',
    number: 104,
    label: 'Tree Shaking / Dead Code Elimination',
    category: 'performance',
    surface: 'production build',
    status: 'partial',
    summary:
      'The Next.js production build performs elimination, but bundle regressions are not measured in CI.',
    implementation: 'apps/web/next.config.ts',
    priority: 3,
  },
  {
    id: 'http3-delivery',
    number: 105,
    label: 'HTTP/3 (QUIC) Delivery',
    category: 'performance',
    surface: 'CDN transport',
    status: 'blocked',
    summary: 'HTTP/3 is controlled by the selected production CDN rather than application code.',
    dependency: 'Production CDN configuration',
    priority: 3,
  },
  {
    id: 'compression-negotiation',
    number: 106,
    label: 'Brotli/Zstd Compression Negotiation',
    category: 'performance',
    surface: 'CDN transport',
    status: 'blocked',
    summary:
      'Compression negotiation belongs to the hosting and CDN layer and is not configured in this repository.',
    dependency: 'Production CDN configuration',
    priority: 3,
  },
  {
    id: 'resource-hint-scheduling',
    number: 107,
    label: 'Resource Hint Scheduling',
    category: 'performance',
    surface: 'document head',
    status: 'planned',
    summary:
      'Add measured preload, preconnect, and prefetch hints only for proven critical resources.',
    priority: 3,
  },
  {
    id: 'speculation-rules-prerender',
    number: 108,
    label: 'Speculation Rules API Prerendering',
    category: 'performance',
    surface: 'article navigation',
    status: 'live',
    summary:
      'Article pages emit Speculation Rules for the top related stories only — never blanket site prerender.',
    implementation: 'apps/web/components/SpeculationRules.tsx',
    priority: 2,
  },
  {
    id: 'yield-to-main',
    number: 109,
    label: 'Long-Task Splitting (Yield-to-Main)',
    category: 'performance',
    surface: 'client interactions',
    status: 'planned',
    summary:
      'Measure INP long tasks before introducing scheduler yields into expensive client work.',
    priority: 3,
  },
  {
    id: 'prepared-statement-cache',
    number: 111,
    label: 'Prepared-Statement Query Caching',
    category: 'performance',
    surface: 'database access',
    status: 'planned',
    summary: 'No explicit prepared-statement or query-plan cache policy is configured.',
    priority: 3,
  },
  {
    id: 'redis-read-through-cache',
    number: 112,
    label: 'Redis Read-Through Cache Layer',
    category: 'performance',
    surface: 'homepage and trending reads',
    status: 'planned',
    summary:
      'Short-lived shared caching needs invalidation rules and an operational Redis-compatible store.',
    dependency: 'Shared cache provider',
    priority: 3,
  },
  {
    id: 'image-cdn-resizing',
    number: 113,
    label: 'On-the-Fly Image CDN Resizing',
    category: 'performance',
    surface: 'editorial images',
    status: 'partial',
    summary:
      'Next Image and AVIF/WebP formats are configured, but production resizing depends on the image host.',
    implementation: 'apps/web/next.config.ts',
    dependency: 'Production image optimizer or CDN',
    priority: 2,
  },
  {
    id: 'font-subsetting-swap',
    number: 114,
    label: 'Font Subsetting + font-display: swap',
    category: 'performance',
    surface: 'typography',
    status: 'live',
    summary: 'next/font loads Devanagari and Latin subsets with display swap.',
    implementation: 'apps/web/app/fonts.ts',
    priority: 2,
  },
  {
    id: 'third-party-script-sandbox',
    number: 115,
    label: 'Third-Party Script Sandboxing',
    category: 'performance',
    surface: 'ads and analytics',
    status: 'planned',
    summary:
      'No worker sandbox is wired; introduce one only when real third-party scripts require isolation.',
    priority: 4,
  },
  {
    id: 'rsc-islands',
    number: 117,
    label: 'Islands Architecture / React Server Components',
    category: 'performance',
    surface: 'public application',
    status: 'live',
    summary:
      'Public routes render as Server Components while interactive reader, search, ad, and PWA controls are client islands.',
    implementation: 'apps/web/app + apps/web/components',
    priority: 1,
  },
  {
    id: 'virtualized-lists',
    number: 118,
    label: 'Virtualized List Rendering',
    category: 'performance',
    surface: 'long feeds and comments',
    status: 'planned',
    summary:
      'No list virtualization is present; adopt it only where DOM measurements justify the complexity.',
    priority: 4,
  },
  {
    id: 'cls-budget-gate',
    number: 119,
    label: 'CI Layout-Shift Budget Gate',
    category: 'performance',
    surface: 'continuous integration',
    status: 'planned',
    summary: 'CI builds and tests the app but does not enforce a measured CLS threshold.',
    implementation: '.github/workflows/ci.yml',
    priority: 2,
  },
  {
    id: 'skeleton-progressive-rendering',
    number: 120,
    label: 'Skeleton-Screen Progressive Rendering',
    category: 'performance',
    surface: 'loading states',
    status: 'planned',
    summary: 'No catalog-wide skeleton strategy is verified for slow public routes.',
    priority: 4,
  },
  {
    id: 'web-worker-offloading',
    number: 121,
    label: 'Web Worker Offloading',
    category: 'performance',
    surface: 'client search and sorting',
    status: 'planned',
    summary:
      'Search currently runs on the main thread; worker transfer costs should be measured before migration.',
    priority: 4,
  },
  {
    id: 'passive-event-listeners',
    number: 122,
    label: 'Passive Event Listeners',
    category: 'performance',
    surface: 'article scroll tracking',
    status: 'live',
    summary: 'Article scroll-depth tracking registers its scroll listener with passive true.',
    implementation: 'apps/web/components/reader/ReaderArticleControls.tsx',
    priority: 2,
  },
  {
    id: 'debounce-throttle-events',
    number: 123,
    label: 'Debounce/Throttle for Scroll & Resize',
    category: 'performance',
    surface: 'client event handlers',
    status: 'live',
    summary:
      'Search input is debounced; article reading scroll depth updates coalesce to one requestAnimationFrame.',
    implementation: 'apps/web/lib/browser/raf-throttle.ts + ReaderArticleControls',
    priority: 2,
  },
  {
    id: 'cls-safe-ad-reservation',
    number: 124,
    label: 'CLS-Safe Ad Slot Reservation',
    category: 'performance',
    surface: 'advertising slots',
    status: 'live',
    summary:
      'Every rendered ad placement reserves its configured height before campaign content arrives.',
    implementation: 'apps/web/components/AdSlot.tsx',
    priority: 1,
  },
  {
    id: 'visual-stability-index',
    number: 125,
    label: 'Visual Stability Index Monitoring',
    category: 'performance',
    surface: 'field monitoring',
    status: 'planned',
    summary: 'No whole-session visual stability telemetry or reporting pipeline exists.',
    priority: 5,
  },

  // Infrastructure 126–135
  {
    id: 'multi-cdn-failover',
    number: 126,
    label: 'Multi-CDN Failover Routing',
    category: 'infrastructure',
    surface: 'global delivery',
    status: 'blocked',
    summary:
      'Regional failover requires contracts, health checks, and routing across multiple CDN vendors.',
    dependency: 'Multiple CDN vendors and authoritative DNS control',
    priority: 5,
  },
  {
    id: 'anycast-dns',
    number: 127,
    label: 'Anycast DNS Routing',
    category: 'infrastructure',
    surface: 'DNS',
    status: 'blocked',
    summary:
      'Anycast behavior is supplied by the production DNS and CDN provider, not this application.',
    dependency: 'Managed DNS provider',
    priority: 3,
  },
  {
    id: 'edge-personalization',
    number: 128,
    label: 'Edge-Function Personalization',
    category: 'infrastructure',
    surface: 'locale and feature flags',
    status: 'planned',
    summary:
      'Current locale routing runs in middleware, while consent-aware personalization remains at origin or client.',
    implementation: 'apps/web/middleware.ts',
    priority: 3,
  },
  {
    id: 'predictive-autoscaling',
    number: 129,
    label: 'Predictive Auto-Scaling',
    category: 'infrastructure',
    surface: 'election and breaking traffic',
    status: 'blocked',
    summary:
      'Forecast-based capacity controls require production traffic history and hosting-provider integration.',
    dependency: 'Hosting metrics and scaling controls',
    priority: 4,
  },
  {
    id: 'canary-blue-green',
    number: 130,
    label: 'Canary / Blue-Green Deployment',
    category: 'infrastructure',
    surface: 'deployment pipeline',
    status: 'blocked',
    summary:
      'Traffic splitting and automated promotion require deployment-provider controls beyond the current CI build.',
    dependency: 'Deployment provider traffic management',
    priority: 3,
  },
  {
    id: 'connection-pool-optimization',
    number: 132,
    label: 'Connection Pool Optimization',
    category: 'infrastructure',
    surface: 'Postgres',
    status: 'planned',
    summary:
      'A measured production pool size and saturation policy has not been documented or enforced.',
    priority: 2,
  },
  {
    id: 'log-anomaly-detection',
    number: 133,
    label: 'Log-Based Anomaly Detection',
    category: 'infrastructure',
    surface: 'operations',
    status: 'planned',
    summary: 'Logs are not connected to an anomaly detector with alert thresholds.',
    dependency: 'Observability backend',
    priority: 2,
  },
  {
    id: 'rum-synthetic-fusion',
    number: 134,
    label: 'RUM + Synthetic Monitoring Fusion',
    category: 'infrastructure',
    surface: 'performance operations',
    status: 'planned',
    summary:
      'No shared view currently combines consented field metrics with scheduled synthetic probes.',
    dependency: 'RUM and synthetic monitoring providers',
    priority: 2,
  },
  {
    id: 'performance-budgets-ci',
    number: 135,
    label: 'Automated Performance Budgets in CI/CD',
    category: 'infrastructure',
    surface: 'continuous integration',
    status: 'live',
    summary:
      'CI runs pnpm audit --prod, perf:budget:test, and a post-build JS chunk budget gate. Browser LCP/INP budgets remain a separate job.',
    implementation: '.github/workflows/ci.yml + scripts/perf-budget.mjs',
    priority: 2,
  },

  // Retention 136–150
  {
    id: 'pwa-install-prompt-timing',
    number: 136,
    label: 'PWA Install-Prompt Timing',
    category: 'retention',
    surface: 'returning readers',
    status: 'scaffold',
    summary:
      'The manifest and service-worker registration exist, but no engagement-based install prompt is wired.',
    implementation: 'apps/web/components/PwaBoot.tsx',
    priority: 3,
  },
  {
    id: 'offline-first-articles',
    number: 137,
    label: 'Offline-First Article Caching',
    category: 'retention',
    surface: 'article reading',
    status: 'live',
    summary:
      'Public article HTML is cached with stale-while-revalidate plus shell fallback when offline.',
    implementation: 'apps/web/app/sw.js/route.ts',
    priority: 2,
  },
  {
    id: 'reading-streaks',
    number: 138,
    label: 'Reading-Streak / Habit-Loop Mechanic',
    category: 'retention',
    surface: 'reader profile',
    status: 'planned',
    summary: 'No streak state or non-manipulative habit UI is implemented.',
    priority: 4,
  },
  {
    id: 'sunrise-theme',
    number: 140,
    label: 'Sunrise/Sunset-Aware Theme Switching',
    category: 'retention',
    surface: 'reader theme',
    status: 'planned',
    summary: 'Theme selection does not currently calculate local sunrise or sunset.',
    priority: 5,
  },
  {
    id: 'automated-accessibility-audit',
    number: 141,
    label: 'Automated Accessibility Auditing (WCAG)',
    category: 'retention',
    surface: 'continuous integration',
    status: 'partial',
    summary:
      'Axe scans critical public routes for serious and critical WCAG A/AA violations in CI; the gate remains partial until it is proven on the hosted workflow.',
    implementation: 'e2e/a11y.spec.ts + .github/workflows/ci.yml',
    priority: 1,
  },
  {
    id: 'push-permission-priming',
    number: 143,
    label: 'Delayed Push-Permission Priming',
    category: 'retention',
    surface: 'notifications',
    status: 'planned',
    summary:
      'Push support exists in the worker, but no reader-value primer controls permission timing.',
    implementation: 'apps/web/app/sw.js/route.ts',
    priority: 3,
  },
  {
    id: 'exit-intent-save',
    number: 144,
    label: 'Exit-Intent Save/Return Prompt',
    category: 'retention',
    surface: 'article exit',
    status: 'planned',
    summary: 'No exit-intent detector or contextual save prompt is implemented.',
    priority: 5,
  },
  {
    id: 'personalized-onboarding',
    number: 145,
    label: 'Personalized Onboarding Path',
    category: 'retention',
    surface: 'first reader session',
    status: 'planned',
    summary: 'Referral-aware topic and language onboarding is not implemented.',
    priority: 3,
  },
  {
    id: 'feedback-timing',
    number: 146,
    label: 'In-App Feedback Timing',
    category: 'retention',
    surface: 'completed reads',
    status: 'planned',
    summary: 'Feedback prompts are not triggered from positive engagement milestones.',
    priority: 3,
  },
  {
    id: 'reader-loyalty-tiers',
    number: 147,
    label: 'Reader Loyalty Tiers',
    category: 'retention',
    surface: 'reader account',
    status: 'planned',
    summary: 'No transparent loyalty tier calculation or reader-facing recognition exists.',
    priority: 4,
  },
  {
    id: 'session-replay-sampling',
    number: 148,
    label: 'Session Replay Sampling',
    category: 'retention',
    surface: 'UX diagnostics',
    status: 'blocked',
    summary:
      'Privacy-scrubbed replay requires a vetted vendor, consent controls, retention limits, and policy review.',
    dependency: 'Approved replay vendor and privacy review',
    priority: 5,
  },
  {
    id: 'micro-interaction-feedback',
    number: 149,
    label: 'Micro-Interaction Feedback',
    category: 'retention',
    surface: 'save, like, and comment actions',
    status: 'planned',
    summary: 'A consistent optimistic-action system with rollback behavior has not been verified.',
    priority: 3,
  },
  {
    id: 'adaptive-font-layout',
    number: 150,
    label: 'Adaptive Font-Size Layout',
    category: 'retention',
    surface: 'public reading UI',
    status: 'partial',
    summary:
      'Responsive rem-based layouts exist, but OS text scaling is not continuously regression-tested.',
    implementation: 'apps/web/app/globals.css',
    priority: 1,
  },

  // Advertising 151–170
  {
    id: 'attention-metric-scoring',
    number: 151,
    label: 'Attention Metric Scoring',
    category: 'advertising',
    surface: 'ad measurement',
    status: 'partial',
    summary:
      'Consent-gated viewability impressions exist, but pixel percentage, dwell, and engagement are not combined into attention scores.',
    implementation: 'apps/web/components/ads/AdTracker.tsx',
    priority: 3,
  },
  {
    id: 'true-cpm-reporting',
    number: 152,
    label: 'TrueCPM Reporting',
    category: 'advertising',
    surface: 'advertiser reporting',
    status: 'planned',
    summary:
      'Quality-adjusted CPM needs campaign cost, fraud, and viewability inputs that are not collected.',
    priority: 4,
  },
  {
    id: 'spo-transparency',
    number: 153,
    label: 'Supply Path Optimization Transparency',
    category: 'advertising',
    surface: 'programmatic supply chain',
    status: 'planned',
    summary: 'No bid-path or intermediary reporting exists beyond public seller declarations.',
    priority: 4,
  },
  {
    id: 'mfa-self-screening',
    number: 154,
    label: 'Made-for-Advertising Self-Screening',
    category: 'advertising',
    surface: 'inventory quality',
    status: 'scaffold',
    summary:
      'Stable labelled ad placements exist, but no automated ad-to-content ratio audit runs.',
    implementation: 'apps/web/components/AdSlot.tsx',
    priority: 2,
  },
  {
    id: 'header-bidding-timeout',
    number: 155,
    label: 'Header-Bidding Timeout Optimization',
    category: 'advertising',
    surface: 'programmatic auction',
    status: 'blocked',
    summary: 'There is no header-bidding vendor or live auction to tune honestly.',
    dependency: 'Header-bidding stack and demand partners',
    priority: 5,
  },
  {
    id: 'pmp-prioritization',
    number: 156,
    label: 'Private Marketplace Deal Prioritization',
    category: 'advertising',
    surface: 'premium campaigns',
    status: 'blocked',
    summary: 'PMP deal ordering requires an ad server and contracted demand partners.',
    dependency: 'Ad server and PMP agreements',
    priority: 5,
  },
  {
    id: 'publisher-provided-id',
    number: 158,
    label: 'Publisher-Provided ID / First-Party Identity Graph',
    category: 'advertising',
    surface: 'consented audience identity',
    status: 'planned',
    summary:
      'Reader identity exists for product features, but no advertising identity graph or PPID export exists.',
    priority: 5,
  },
  {
    id: 'contextual-sentiment-targeting',
    number: 159,
    label: 'AI-Powered Contextual & Sentiment Targeting',
    category: 'advertising',
    surface: 'campaign targeting',
    status: 'planned',
    summary:
      'Manual taxonomy exists, but no approved sentiment model or campaign targeting workflow is wired.',
    priority: 3,
  },
  {
    id: 'cross-device-frequency-cap',
    number: 160,
    label: 'Cross-Device Frequency Capping',
    category: 'advertising',
    surface: 'campaign delivery',
    status: 'planned',
    summary: 'No consented cross-device campaign exposure store exists.',
    priority: 5,
  },
  {
    id: 'viewability-ad-refresh',
    number: 161,
    label: 'Viewability-Triggered Ad Refresh',
    category: 'advertising',
    surface: 'ad slots',
    status: 'scaffold',
    summary: 'IntersectionObserver records a first viewable impression, but slots do not refresh.',
    implementation: 'apps/web/components/ads/AdTracker.tsx',
    priority: 4,
  },
  {
    id: 'ad-incrementality-holdout',
    number: 162,
    label: 'Incrementality / Holdout Testing',
    category: 'advertising',
    surface: 'campaign measurement',
    status: 'planned',
    summary: 'No campaign-level assignment, holdout, or causal lift reporting exists.',
    priority: 5,
  },
  {
    id: 'media-mix-modeling',
    number: 163,
    label: 'Media Mix Modeling Reporting',
    category: 'advertising',
    surface: 'advertiser analytics',
    status: 'planned',
    summary: 'Aggregate outcome data and modeling infrastructure are not available.',
    priority: 5,
  },
  {
    id: 'dynamic-floor-pricing',
    number: 165,
    label: 'Dynamic Floor Pricing',
    category: 'advertising',
    surface: 'programmatic auction',
    status: 'blocked',
    summary: 'Dynamic floors require live bidstream demand and an ad exchange integration.',
    dependency: 'Ad exchange bidstream',
    priority: 5,
  },
  {
    id: 'native-ad-rendering',
    number: 166,
    label: 'Native Ad Format Rendering',
    category: 'advertising',
    surface: 'native placements',
    status: 'partial',
    summary:
      'A clearly labelled native placement renderer exists for house inventory; network creative delivery is not wired.',
    implementation: 'apps/web/components/AdSlot.tsx',
    priority: 2,
  },
  {
    id: 'video-ssai',
    number: 167,
    label: 'Server-Side Ad Insertion for Video',
    category: 'advertising',
    surface: 'video',
    status: 'blocked',
    summary:
      'SSAI requires a video origin, manifest stitcher, and ad decision service that are not part of the stack.',
    dependency: 'Video and SSAI vendors',
    priority: 5,
  },
  {
    id: 'reach-frequency-dedup',
    number: 168,
    label: 'Cross-Device Reach & Frequency Deduplication',
    category: 'advertising',
    surface: 'advertiser reporting',
    status: 'planned',
    summary: 'No privacy-safe cross-device identity or campaign reach pipeline exists.',
    priority: 5,
  },
  {
    id: 'advertiser-dashboard-pipeline',
    number: 169,
    label: 'Real-Time Advertiser Dashboard Pipeline',
    category: 'advertising',
    surface: 'admin ads dashboard',
    status: 'partial',
    summary:
      'Consent-gated impressions persist and aggregate in admin, but there is no advertiser access or streaming pipeline.',
    implementation: 'apps/web/app/admin/ads/page.tsx + apps/web/lib/ad-events.ts',
    priority: 3,
  },
  {
    id: 'attention-yield-optimization',
    number: 170,
    label: 'Attention-Weighted Yield Optimization',
    category: 'advertising',
    surface: 'ad yield',
    status: 'planned',
    summary:
      'Attention scoring and a live auction must exist before yield can be optimized against attention.',
    priority: 5,
  },

  // Experimentation 171–180
  {
    id: 'sequential-ab-testing',
    number: 171,
    label: 'Sequential (Always-Valid) A/B Testing',
    category: 'experimentation',
    surface: 'product experiments',
    status: 'partial',
    summary:
      'Results can be monitored continuously with minimum-sample and posterior thresholds, but no formal e-value confidence sequence is claimed.',
    implementation: 'apps/web/lib/experiments/core.ts#analyzeExperiment',
    priority: 4,
  },
  {
    id: 'bayesian-experimentation',
    number: 172,
    label: 'Bayesian Experimentation Framework',
    category: 'experimentation',
    surface: 'product experiments',
    status: 'live',
    summary:
      'Beta posteriors estimate conversion rate and probability each variant is best; admin never calls a winner before guardrails pass.',
    implementation: 'apps/web/lib/experiments/core.ts + apps/web/app/admin/experiments/page.tsx',
    priority: 2,
  },
  {
    id: 'progressive-feature-rollout',
    number: 173,
    label: 'Progressive Feature Flag Rollout',
    category: 'experimentation',
    surface: 'release controls',
    status: 'partial',
    summary:
      'Deterministic weighted rollout is live; automated health-metric promotion and rollback are not.',
    implementation: 'apps/web/lib/experiments/core.ts#assignVariant',
    priority: 3,
  },
  {
    id: 'cohort-retention-forecasting',
    number: 174,
    label: 'Cohort Retention Forecasting',
    category: 'experimentation',
    surface: 'reader analytics',
    status: 'planned',
    summary: 'Longitudinal cohort data and a retention curve model are not available.',
    priority: 4,
  },
  {
    id: 'funnel-anomaly-detection',
    number: 176,
    label: 'Funnel Anomaly Detection',
    category: 'experimentation',
    surface: 'signup and engagement funnels',
    status: 'planned',
    summary: 'No funnel baseline, anomaly model, or alert destination exists.',
    priority: 3,
  },
  {
    id: 'clickmap-heatmap',
    number: 177,
    label: 'Click-Map / Heatmap Aggregation',
    category: 'experimentation',
    surface: 'UX analytics',
    status: 'planned',
    summary: 'Consent-aware coordinate aggregation and privacy thresholds are not implemented.',
    priority: 5,
  },
  {
    id: 'session-quality-scoring',
    number: 178,
    label: 'Session Quality Scoring',
    category: 'experimentation',
    surface: 'reader analytics',
    status: 'live',
    summary:
      'Privacy-preserving 24-hour report aggregates dwell, completion, shares, and bookmarks into a transparent quality heuristic.',
    implementation: 'apps/web/lib/session-quality.ts + apps/web/app/admin/session-quality/page.tsx',
    priority: 3,
  },
  {
    id: 'traffic-source-clustering',
    number: 179,
    label: 'Traffic-Source Attribution Clustering',
    category: 'experimentation',
    surface: 'acquisition analytics',
    status: 'planned',
    summary: 'Referral events and a clustering pipeline are not implemented.',
    priority: 4,
  },
  {
    id: 'bot-human-classification',
    number: 180,
    label: 'Bot-vs-Human Traffic Classification',
    category: 'experimentation',
    surface: 'traffic quality',
    status: 'planned',
    summary: 'Rate limiting exists, but no behavioral traffic classifier is trained or deployed.',
    priority: 2,
  },

  // Distribution and SEO 181–190
  {
    id: 'crawl-budget-allocation',
    number: 181,
    label: 'Crawl-Budget Allocation',
    category: 'distribution',
    surface: 'sitemap',
    status: 'partial',
    summary:
      'Dynamic sitemap priorities and update frequencies exist, but no measured crawl-log feedback loop does.',
    implementation: 'apps/web/app/sitemap.ts',
    priority: 2,
  },
  {
    id: 'canonical-url-resolution',
    number: 182,
    label: 'Canonical URL Resolution',
    category: 'distribution',
    surface: 'public routes',
    status: 'live',
    summary:
      'Locale-aware canonical metadata covers articles, home, category pages, and major hubs through a shared clean-URL helper.',
    implementation: 'apps/web/lib/seo/canonical.ts + apps/web/app/[locale]',
    priority: 1,
  },
  {
    id: 'hreflang-mapping',
    number: 183,
    label: 'Hreflang Mapping for Nepali/English',
    category: 'distribution',
    surface: 'metadata and sitemap',
    status: 'live',
    summary: 'Articles, home, categories, major hubs, and sitemap emit Nepali/English alternates with x-default.',
    implementation: 'apps/web/lib/seo/canonical.ts + apps/web/app/sitemap.ts',
    priority: 1,
  },
  {
    id: 'internal-link-authority',
    number: 184,
    label: 'Internal Link-Graph Authority Flow',
    category: 'distribution',
    surface: 'related and evergreen links',
    status: 'planned',
    summary: 'No graph-based audit or authority allocation algorithm controls internal links.',
    priority: 3,
  },
  {
    id: 'faq-howto-schema',
    number: 185,
    label: 'Auto-Generated FAQ/HowTo Schema',
    category: 'distribution',
    surface: 'explainer pages',
    status: 'planned',
    summary:
      'NewsArticle schema exists, but FAQ and HowTo blocks are not generated from verified structured content.',
    priority: 3,
  },
  {
    id: 'rss-atom-optimization',
    number: 186,
    label: 'RSS/Atom Feed Optimization',
    category: 'distribution',
    surface: 'RSS feed',
    status: 'live',
    summary:
      'Nepali and English RSS plus locale-selectable Atom publish canonical links, stable IDs, dates, and escaped summaries.',
    implementation: 'apps/web/app/rss.xml/route.ts + apps/web/app/en/rss.xml/route.ts + apps/web/app/atom.xml/route.ts',
    priority: 1,
  },
  {
    id: 'instant-static-rendering',
    number: 187,
    label: 'Instant-Loading Static Rendering (AMP successor)',
    category: 'distribution',
    surface: 'high-traffic public pages',
    status: 'partial',
    summary:
      'Next server rendering and route revalidation exist, but no traffic-aware prerender program is configured.',
    implementation: 'apps/web/app',
    priority: 2,
  },
  {
    id: 'open-graph-previews',
    number: 188,
    label: 'Open Graph / Social Card Auto-Preview',
    category: 'distribution',
    surface: 'shared article links',
    status: 'partial',
    summary:
      'Article Open Graph metadata uses editorial images, but platform previews are not continuously validated.',
    implementation: 'apps/web/app/[locale]/[category]/[slug]/page.tsx',
    priority: 1,
  },
  {
    id: 'whatsapp-viber-previews',
    number: 189,
    label: 'WhatsApp/Viber Share-Preview Optimization',
    category: 'distribution',
    surface: 'messaging shares',
    status: 'partial',
    summary:
      'Generic Open Graph previews are emitted, but WhatsApp and Viber-specific preview tests are absent.',
    implementation: 'apps/web/app/[locale]/[category]/[slug]/page.tsx',
    priority: 2,
  },
  {
    id: 'newsletter-send-curation',
    number: 190,
    label: 'Newsletter Send-Time & Curation Algorithm',
    category: 'distribution',
    surface: 'newsletter',
    status: 'planned',
    summary:
      'Newsletter administration exists, but subscriber-level send-time and story selection do not.',
    priority: 3,
  },

  // Security 191–200
  {
    id: 'waf-rule-engine',
    number: 191,
    label: 'Web Application Firewall Rule Engine',
    category: 'security',
    surface: 'edge security',
    status: 'blocked',
    summary:
      'Application validation exists, but a WAF must be configured with the production edge provider.',
    dependency: 'Cloudflare or equivalent WAF',
    priority: 1,
  },
  {
    id: 'behavioral-bot-score',
    number: 192,
    label: 'Behavioral Bot-Score Classification',
    category: 'security',
    surface: 'public traffic',
    status: 'planned',
    summary: 'No privacy-reviewed behavioral fingerprint classifier exists.',
    priority: 3,
  },
  {
    id: 'invisible-bot-challenge',
    number: 193,
    label: 'Invisible Bot Challenge',
    category: 'security',
    surface: 'public write forms',
    status: 'blocked',
    summary:
      'A passive challenge requires a selected provider, keys, server verification, and privacy disclosure.',
    dependency: 'Bot-challenge provider',
    priority: 2,
  },
  {
    id: 'tls-resumption-ocsp',
    number: 194,
    label: 'TLS Session Resumption + OCSP Stapling',
    category: 'security',
    surface: 'TLS termination',
    status: 'blocked',
    summary: 'TLS session and OCSP behavior is controlled by the production host or CDN.',
    dependency: 'Production TLS terminator',
    priority: 3,
  },
  {
    id: 'auto-generated-csp',
    number: 195,
    label: 'Auto-Generated Content Security Policy',
    category: 'security',
    surface: 'response headers',
    status: 'partial',
    summary:
      'Baseline CSP is emitted from next.config; full auto-inventory tightening still needs network-ad allowlist generation.',
    implementation: 'apps/web/next.config.ts',
    priority: 1,
  },
  {
    id: 'credential-stuffing-detection',
    number: 196,
    label: 'Credential-Stuffing Detection',
    category: 'security',
    surface: 'authentication',
    status: 'planned',
    summary:
      'Rate limits protect writes, but breached-credential and distributed-attempt detection are not wired.',
    priority: 2,
  },
  {
    id: 'dependency-vulnerability-scanning',
    number: 198,
    label: 'Automated Dependency/Vulnerability Scanning',
    category: 'security',
    surface: 'continuous integration',
    status: 'live',
    summary:
      'CI runs pnpm audit --prod at high severity and Dependabot groups weekly npm/action updates.',
    implementation: '.github/workflows/ci.yml + .github/dependabot.yml',
    priority: 1,
  },
  {
    id: 'scheduled-secret-rotation',
    number: 199,
    label: 'Scheduled Secrets Rotation',
    category: 'security',
    surface: 'operations',
    status: 'blocked',
    summary:
      'Rotation requires ownership of each external secret and provider-specific automation.',
    dependency: 'Secret manager and provider integrations',
    priority: 2,
  },
  {
    id: 'error-spike-auto-rollback',
    number: 200,
    label: 'Auto-Rollback on Error-Rate Spike',
    category: 'security',
    surface: 'deployment safety',
    status: 'blocked',
    summary:
      'Health-based rollback requires production telemetry connected to deployment-provider controls.',
    dependency: 'Observability and deployment provider integration',
    priority: 2,
  },

  // Syndication 216–227
  {
    id: 'dwell-syndication-format',
    number: 217,
    label: 'Dwell-Time-Optimized Syndication Formatting',
    category: 'syndication',
    surface: 'partner feeds',
    status: 'planned',
    summary: 'No partner-specific long-form formatting or dwell feedback loop exists.',
    priority: 4,
  },
  {
    id: 'google-news-discover-feed',
    number: 218,
    label: 'Google News/Discover Feed Optimization',
    category: 'syndication',
    surface: 'Google News',
    status: 'partial',
    summary:
      'A 48-hour news sitemap and article structured data exist; Publisher Center and Discover performance are external.',
    implementation:
      'apps/web/app/news-sitemap.xml/route.ts + apps/web/components/article/ArticleJsonLd.tsx',
    dependency: 'Google Publisher Center account',
    priority: 1,
  },
  {
    id: 'partner-discovery-matching',
    number: 219,
    label: 'Syndication Partner Discovery Matching',
    category: 'syndication',
    surface: 'business development',
    status: 'planned',
    summary: 'No partner inventory, audience-fit data, or matching model exists.',
    priority: 5,
  },
  {
    id: 'multi-platform-feed-compliance',
    number: 220,
    label: 'Multi-Platform Feed Spec Compliance',
    category: 'syndication',
    surface: 'partner feeds',
    status: 'partial',
    summary:
      'RSS, Atom, and a canonical-plus-attribution partner JSON scaffold exist; partner-specific validators and contracts remain.',
    implementation: 'apps/web/app/rss.xml/route.ts + apps/web/app/atom.xml/route.ts + apps/web/app/feeds/partner.json/route.ts',
    priority: 4,
  },
  {
    id: 'commerce-feed-enrichment',
    number: 221,
    label: 'Commerce-Content Feed Enrichment',
    category: 'syndication',
    surface: 'commerce partner feeds',
    status: 'planned',
    summary: 'No commerce content model or product-feed agreement exists.',
    priority: 5,
  },
  {
    id: 'syndication-revenue-reconciliation',
    number: 222,
    label: 'Syndication Revenue Reconciliation',
    category: 'syndication',
    surface: 'partner finance',
    status: 'planned',
    summary: 'Partner delivery logs, statements, and payout matching are not implemented.',
    priority: 5,
  },
  {
    id: 'embargo-windowing',
    number: 223,
    label: 'Embargoed/Exclusive Windowing',
    category: 'syndication',
    surface: 'publishing workflow',
    status: 'planned',
    summary: 'No syndication queue enforces delayed release after first-party publication.',
    priority: 3,
  },
  {
    id: 'syndicated-copy-canonical',
    number: 224,
    label: 'Syndicated-Copy Canonicalization',
    category: 'syndication',
    surface: 'partner feeds',
    status: 'scaffold',
    summary:
      'Canonical article URLs exist and can be exported, but no partner feed contract enforces attribution.',
    implementation: 'apps/web/app/[locale]/[category]/[slug]/page.tsx',
    priority: 2,
  },
  {
    id: 'local-aggregator-onboarding',
    number: 225,
    label: 'Local Aggregator Onboarding',
    category: 'syndication',
    surface: 'Nepal distribution partners',
    status: 'planned',
    summary: 'No verified Nepal aggregator roster or onboarding workflow exists.',
    priority: 3,
  },
  {
    id: 'partner-health-scoring',
    number: 226,
    label: 'Syndication Partner Health Scoring',
    category: 'syndication',
    surface: 'partner analytics',
    status: 'planned',
    summary: 'Partner-level content, traffic, and revenue data are prerequisites for scoring.',
    priority: 5,
  },
  {
    id: 'white-label-wire-feed',
    number: 227,
    label: 'White-Label Wire Feed',
    category: 'syndication',
    surface: 'licensed reporting feed',
    status: 'planned',
    summary:
      'Licensing, authentication, rights metadata, and a customer delivery API are not implemented.',
    priority: 4,
  },

  // E-paper 228–232
  {
    id: 'epaper-entitlement',
    number: 229,
    label: 'E-Paper Entitlement Check',
    category: 'epaper',
    surface: 'e-paper access',
    status: 'planned',
    summary: 'The current membership gate has no separate edition entitlement or product tier.',
    priority: 4,
  },
  {
    id: 'offline-epaper-cache',
    number: 230,
    label: 'Offline E-Paper Caching',
    category: 'epaper',
    surface: 'e-paper reader',
    status: 'planned',
    summary: 'No edition asset, download manager, quota policy, or offline viewer exists.',
    priority: 4,
  },
  {
    id: 'circulation-reconciliation',
    number: 231,
    label: 'Print-vs-Digital Circulation Reconciliation',
    category: 'epaper',
    surface: 'circulation reporting',
    status: 'planned',
    summary:
      'Print circulation and digital edition entitlement data are not available to reconcile.',
    priority: 5,
  },
  {
    id: 'low-end-page-flip',
    number: 232,
    label: 'Low-End-Device Page-Flip Optimization',
    category: 'epaper',
    surface: 'e-paper viewer',
    status: 'planned',
    summary:
      'A page-flip viewer must exist before low-end Android performance can be measured and optimized.',
    priority: 5,
  },
] as const

export function algorithmsByStatus(status: AlgorithmStatus): AlgorithmEntry[] {
  return ALGORITHM_CATALOG.filter((entry) => entry.status === status)
}

export function algorithmsByCategory(category: AlgorithmCategory): AlgorithmEntry[] {
  return ALGORITHM_CATALOG.filter((entry) => entry.category === category)
}

export function rankAlgorithmsForShipping(limit = 20): AlgorithmEntry[] {
  return [...ALGORITHM_CATALOG]
    .filter((entry) => entry.status !== 'blocked')
    .sort((a, b) => a.priority - b.priority || a.number - b.number)
    .slice(0, limit)
}

export function algorithmCatalogStats() {
  const stats: Record<AlgorithmStatus, number> = {
    live: 0,
    partial: 0,
    scaffold: 0,
    blocked: 0,
    planned: 0,
  }
  for (const entry of ALGORITHM_CATALOG) stats[entry.status] += 1
  return {
    total: ALGORITHM_CATALOG.length,
    ...stats,
  }
}

/** Backward-compatible registry used by older admin cards. */
export const ACTIVE_ALGORITHM_REGISTRY = ALGORITHM_CATALOG.filter(
  (entry) => entry.status === 'live',
).map((entry) => ({
  id: entry.id,
  label: entry.label,
  surface: entry.surface,
}))

export const ALGORITHM_ROADMAP = ALGORITHM_CATALOG.map((entry) => entry.id)
