// ESLint (flat config) for the Payload CMS app.
//
// This workspace declared a `lint` script but shipped no config, so `eslint .`
// exited 2 ("all of the files matching the glob pattern are ignored") — and
// nothing noticed, because the root `lint` script never ran the workspace
// scripts. It now reuses the root base (ESLint recommended + typescript-eslint
// recommended, no type information required) and adds what only this app has.
import base from '../../eslint.config.mjs'

export default [
  ...base,
  {
    ignores: [
      '.next/**',
      'next-env.d.ts',
      // Regenerated by Payload from payload.config.ts; hand-edits are overwritten.
      'src/payload-types.ts',
    ],
  },
]
