/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    authors: Author;
    tags: Tag;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name (Devanagari or Latin as appropriate).
   */
  name: string;
  /**
   * Drives access control across all collections. Publisher + admin require 2FA (Phase 5).
   */
  roles: (
    | 'reader'
    | 'contributor'
    | 'journalist'
    | 'photo_video_editor'
    | 'copy_editor'
    | 'fact_checker'
    | 'assistant_editor'
    | 'sub_editor'
    | 'section_editor'
    | 'province_editor'
    | 'managing_editor'
    | 'editor_in_chief'
    | 'seo_manager'
    | 'moderator'
    | 'ad_manager'
    | 'analyst'
    | 'publisher'
    | 'admin'
    | 'super_admin'
  )[];
  /**
   * Sections this user can edit. Editors are scoped to their section(s).
   */
  section?: ('politics' | 'society' | 'business' | 'sports' | 'entertainment' | 'world' | 'opinion')[] | null;
  /**
   * Disable access without deleting the account.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nameNe: string;
  nameEn: string;
  slug: string;
  parent?: (number | null) | Category;
  description?: string | null;
  navOrder?: number | null;
  showInNav?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  role: 'staff' | 'columnist' | 'contributor' | 'wire';
  bio?: string | null;
  photo?: (number | null) | Media;
  email?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  nameNe: string;
  nameEn?: string | null;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  titleNe: string;
  titleEn?: string | null;
  slug: string;
  deckNe?: string | null;
  deckEn?: string | null;
  bodyNe:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  bodyEn?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  englishStatus?: ('none' | 'requested' | 'in_progress' | 'ready' | 'published') | null;
  englishBy?: (number | null) | User;
  workflowStage:
    | 'idea'
    | 'assigned'
    | 'draft'
    | 'submitted'
    | 'fact_check'
    | 'copy_edit'
    | 'seo_review'
    | 'legal_review'
    | 'ready'
    | 'scheduled'
    | 'published'
    | 'updated'
    | 'archived'
    | 'retracted';
  assignedTo?: (number | User)[] | null;
  editor?: (number | null) | User;
  factChecker?: (number | null) | User;
  copyEditor?: (number | null) | User;
  internalNotes?: string | null;
  category: number | Category;
  tags?:
    | {
        tag?: (number | null) | Tag;
        id?: string | null;
      }[]
    | null;
  authors: {
    author: number | Author;
    id?: string | null;
  }[];
  heroImage?: (number | null) | Media;
  heroCaption?: string | null;
  heroCredit?: string | null;
  sourceType: 'original' | 'aggregated' | 'wire';
  sourceName?: string | null;
  sourceUrl?: string | null;
  sourcePublishedAt?: string | null;
  isBreaking?: boolean | null;
  featuredState?: ('lead' | 'secondary' | 'none') | null;
  locale: 'ne' | 'en';
  publishAt?: string | null;
  submittedAt?: string | null;
  factCheckedAt?: string | null;
  copyEditedAt?: string | null;
  seoReviewedAt?: string | null;
  legalReviewedAt?: string | null;
  readingMinutes?: number | null;
  wordCount?: number | null;
  readingDifficultyNote?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  noIndex?: boolean | null;
  includeInNewsSitemap?: boolean | null;
  aiSummary?: string | null;
  aiSummaryApproved?: boolean | null;
  doNotRecommend?: boolean | null;
  premium?: boolean | null;
  sensitive?: boolean | null;
  corrections?:
    | {
        at: string;
        summary: string;
        madeBy: number | User;
        id?: string | null;
      }[]
    | null;
  adFree?: boolean | null;
  commentsEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  section?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nameNe?: T;
  nameEn?: T;
  slug?: T;
  parent?: T;
  description?: T;
  navOrder?: T;
  showInNav?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  email?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  nameNe?: T;
  nameEn?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titleNe?: T;
  titleEn?: T;
  slug?: T;
  deckNe?: T;
  deckEn?: T;
  bodyNe?: T;
  bodyEn?: T;
  englishStatus?: T;
  englishBy?: T;
  workflowStage?: T;
  assignedTo?: T;
  editor?: T;
  factChecker?: T;
  copyEditor?: T;
  internalNotes?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  authors?:
    | T
    | {
        author?: T;
        id?: T;
      };
  heroImage?: T;
  heroCaption?: T;
  heroCredit?: T;
  sourceType?: T;
  sourceName?: T;
  sourceUrl?: T;
  sourcePublishedAt?: T;
  isBreaking?: T;
  featuredState?: T;
  locale?: T;
  publishAt?: T;
  submittedAt?: T;
  factCheckedAt?: T;
  copyEditedAt?: T;
  seoReviewedAt?: T;
  legalReviewedAt?: T;
  readingMinutes?: T;
  wordCount?: T;
  readingDifficultyNote?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  noIndex?: T;
  includeInNewsSitemap?: T;
  aiSummary?: T;
  aiSummaryApproved?: T;
  doNotRecommend?: T;
  premium?: T;
  sensitive?: T;
  corrections?:
    | T
    | {
        at?: T;
        summary?: T;
        madeBy?: T;
        id?: T;
      };
  adFree?: T;
  commentsEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}