import type { Article } from '@nagarikwatch/db'
import { unsplash } from './media'

/**
 * Seed articles, batch 2: sports, entertainment, world, opinion, diaspora, plus a few
 * extra politics/society/business. Intentionally mixes `sourceType` — aggregated and wire
 * entries carry the `source` block so the attribution line renders and the Article
 * source-attribution hook stays exercised. A subset have an author-reviewed English version.
 */
export const articlesBatch2: Article[] = [
  // -- SPORTS ----------------------------------------------------------------
  {
    id: 'art-010',
    slug: 'nepal-cricket-series-win',
    category: { id: 'cat-sports', slug: 'sports', nameNe: 'खेलकुद', nameEn: 'Sports' },
    categoryLabel: 'खेलकुद',
    titleNe: 'नेपालले टी२० शृंखला जित्यो, कप्तानले जसरीको प्रशंसा गरे',
    titleEn: 'Nepal win the T20 series; captain praises the bowling unit',
    deckNe: 'घरेलु मैदानमा नेपालले शृंखला आफ्नो नाममा बनाएको छ।',
    heroImage: unsplash('1531415083146-9a1d5e5efade', 'क्रिकेट मैदानमा खेलाडी', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'रोशन महर्जन',
    authors: [{ id: 'aut-roshan', slug: 'roshan-maharjan', name: 'रोशन महर्जन' }],
    publishedAt: '2026-06-19T03:00:00.000Z',
    hasEnglish: true,
    isBreaking: true,
    readingMinutes: 3,
    tags: [
      {
        id: 'tag-cricket',
        slug: 'nepal-cricket',
        nameNe: 'नेपाली क्रिकेट',
        nameEn: 'Nepal cricket',
      },
    ],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'नेपाली राष्ट्रिय क्रिकेट टोलीले घरेलु मैदानमा तीन खेलको टी२० शृंखला आफ्नो नाममा बनाएको छ। अन्तिम खेलमा निर्णायक बलिङ प्रदर्शनले टोलीलाई जित दिलायो।',
      },
      {
        type: 'pullQuote',
        quoteNe: 'बलरहरूले दबाब कायम राखे, त्यही फरक ल्यायो।',
        attribution: 'कप्तान',
      },
      {
        type: 'paragraph',
        text: 'कप्तानले भने, "यो जित टोलीको मेहनत र रणनीतिको नतिजा हो।" अर्को शृंखला अर्को महिना सुरु हुनेछ।',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'Nepal sealed the three-match T20 series at home, with a decisive bowling spell closing out the final game.',
      },
      {
        type: 'paragraph',
        text: '"The bowlers kept the pressure on — that was the difference," the captain said.',
      },
    ],
    seoDescriptionNe: 'नेपालले घरेलु टी२० शृंखला जितेको छ।',
    seoDescriptionEn: 'Nepal sealed the home T20 series.',
  },
  {
    id: 'art-011',
    slug: 'football-league-kickoff',
    category: { id: 'cat-sports', slug: 'sports', nameNe: 'खेलकुद', nameEn: 'Sports' },
    categoryLabel: 'खेलकुद',
    titleNe: 'मार्टिन क्लब फुटबल लिगको नयाँ संस्करण सुरु',
    heroImage: unsplash('1522778526097-ce0a22ceb253', 'फुटबल खेलाडी', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'रोशन महर्जन',
    authors: [{ id: 'aut-roshan', slug: 'roshan-maharjan', name: 'रोशन महर्जन' }],
    publishedAt: '2026-06-17T05:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'क्लब फुटबल लिगको नयाँ संस्करण सुरु भएको छ। पहिलो खेलमा रक्षण र आक्रमण दुवै छातिमा दमदार प्रदर्शन देखियो।',
      },
    ],
    seoDescriptionNe: 'क्लब फुटबल लिगको नयाँ संस्करण सुरु भएको छ।',
  },
  {
    id: 'art-012',
    slug: 'athletics-record-national',
    category: { id: 'cat-sports', slug: 'sports', nameNe: 'खेलकुद', nameEn: 'Sports' },
    categoryLabel: 'खेलकुद',
    titleNe: 'राष्ट्रिय एथलेटिक्समा नयाँ रेकर्ड बन्यो',
    heroImage: unsplash('1552674605-db6ffd4facb5', 'दौड प्रतियोगिता', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'रोशन महर्जन',
    authors: [{ id: 'aut-roshan', slug: 'roshan-maharjan', name: 'रोशन महर्जन' }],
    publishedAt: '2026-06-14T02:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'राष्ट्रिय एथलेटिक्स प्रतियोगितामा महिला तीन हजार मिटर दौडमा नयाँ राष्ट्रिय रेकर्ड बनेको छ।',
      },
    ],
    seoDescriptionNe: 'राष्ट्रिय एथलेटिक्समा नयाँ रेकर्ड बनेको छ।',
  },

  // -- ENTERTAINMENT ---------------------------------------------------------
  {
    id: 'art-013',
    slug: 'film-festival-entries',
    category: {
      id: 'cat-entertainment',
      slug: 'entertainment',
      nameNe: 'मनोरञ्जन',
      nameEn: 'Entertainment',
    },
    categoryLabel: 'मनोरञ्जन',
    titleNe: 'अन्तर्राष्ट्रिय चलचित्र महोत्सवमा नेपाली चलचित्रको प्रतिनिधित्व',
    titleEn: 'Nepali films selected for the international festival',
    deckNe: 'तीन नेपाली चलचित्रले अन्तर्राष्ट्रिय महोत्सवमा प्रदर्शनको अवसर पाएका छन्।',
    heroImage: unsplash('1489599849927-2ee91cede3ba', 'चलचित्र देखाउने भवन', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'मीरा राजभण्डारी',
    authors: [{ id: 'aut-meera', slug: 'meera-rajbhandari', name: 'मीरा राजभण्डारी' }],
    publishedAt: '2026-06-18T07:00:00.000Z',
    hasEnglish: true,
    isBreaking: false,
    readingMinutes: 3,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'तीन नेपाली चलचित्रले विदेशी चलचित्र महोत्सवको आधिकारिक चयनमा स्थान पाएका छन्। निर्देशकहरूले यसले नेपाली सिनेमाको दायरा फराकिलो बनाएको बताएका छन्।',
      },
      {
        type: 'paragraph',
        text: 'निर्देशक एकले भने, "स्थानीय कथा विश्वस्तरीय मञ्चमा पुग्नु हाम्रा कलाकारका लागि ठूलो उपलब्धि हो।"',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'Three Nepali films were selected for official screenings at international festivals, widening the reach of Nepali cinema.',
      },
    ],
    seoDescriptionNe: 'नेपाली चलचित्रले अन्तर्राष्ट्रिय महोत्सवमा स्थान पाएका छन्।',
  },
  {
    id: 'art-014',
    slug: 'music-concert-summer',
    category: {
      id: 'cat-entertainment',
      slug: 'entertainment',
      nameNe: 'मनोरञ्जन',
      nameEn: 'Entertainment',
    },
    categoryLabel: 'मनोरञ्जन',
    titleNe: 'गर्मीमा सांगीतिक कार्यक्रमहरूको सुरुवात',
    heroImage: unsplash('1493225457124-a3eb161ffa5f', 'सांगीतिक मञ्च', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'मीरा राजभण्डारी',
    authors: [{ id: 'aut-meera', slug: 'meera-rajbhandari', name: 'मीरा राजभण्डारी' }],
    publishedAt: '2026-06-15T03:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'गर्मीको सुरुवातसँगै शहरभर सांगीतिक कार्यक्रमहरू सुरु भएका छन्। युवा कलाकारहरूले आफ्नो नयाँ सिर्जना सार्वजनिक गर्दै छन्।',
      },
    ],
    seoDescriptionNe: 'गर्मीमा सांगीतिक कार्यक्रमहरू सुरु भएका छन्।',
  },
  {
    id: 'art-015',
    slug: 'streaming-local-content',
    category: {
      id: 'cat-entertainment',
      slug: 'entertainment',
      nameNe: 'मनोरञ्जन',
      nameEn: 'Entertainment',
    },
    categoryLabel: 'मनोरञ्जन',
    titleNe: 'स्ट्रिमिङ प्लेटफर्ममा स्थानीय सामग्रीको उपस्थिति बढ्दो',
    heroImage: unsplash('1574267432553-4b4628081c31', 'स्ट्रिमिङ सेवा', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'मीरा राजभण्डारी',
    authors: [{ id: 'aut-meera', slug: 'meera-rajbhandari', name: 'मीरा राजभण्डारी' }],
    publishedAt: '2026-06-12T06:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'स्ट्रिमिङ प्लेटफर्महरूमा स्थानीय सामग्रीको माग बढ्दो छ। उद्योगका विश्लेषकहरूले यसले सिर्जनाको दायरा फराकिलो बनाएको बताउँछन्।',
      },
    ],
    seoDescriptionNe: 'स्ट्रिमिङ प्लेटफर्ममा स्थानीय सामग्रीको माग बढेको छ।',
  },

  // -- WORLD (wire / aggregated) --------------------------------------------
  {
    id: 'art-016',
    slug: 'global-energy-summit',
    category: { id: 'cat-world', slug: 'world', nameNe: 'विश्व', nameEn: 'World' },
    categoryLabel: 'विश्व',
    titleNe: 'विश्व ऊर्जा सम्मेलनमा नवीकरणीयमा सहमति',
    titleEn: 'Global energy summit reaches agreement on renewables',
    deckNe: 'सहभागी राष्ट्रहरूले नवीकरणीय ऊर्जा लगानी बढाउने प्रतिबद्धता जनाएका छन्।',
    heroImage: unsplash('1466611653911-95081537e5b7', 'ऊर्जा संयन्त्र', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'एजेन्सी रिपोर्ट',
    authors: [{ id: 'aut-agency', slug: 'agency-report', name: 'एजेन्सी रिपोर्ट' }],
    publishedAt: '2026-06-18T12:00:00.000Z',
    hasEnglish: true,
    isBreaking: false,
    readingMinutes: 3,
    tags: [{ id: 'tag-climate', slug: 'climate', nameNe: 'जलवायु', nameEn: 'Climate' }],
    source: {
      sourceType: 'wire',
      sourceName: 'Reuters',
      sourceUrl: 'https://www.reuters.com/',
      sourcePublishedAt: '2026-06-18T10:00:00.000Z',
    },
    bodyNe: [
      {
        type: 'paragraph',
        text: 'विश्व ऊर्जा सम्मेलनमा सहभागी राष्ट्रहरूले आगामी दशकमा नवीकरणीय ऊर्जामा लगानी बढाउने सहमतिमा पुगेका छन्।',
      },
      { type: 'heading2', text: 'लगानीको प्रतिबद्धता' },
      {
        type: 'paragraph',
        text: 'सम्मेलनको निष्कर्षमा दीर्घकालीन योजना र पारदर्शी प्रगति समीक्षाको व्यवस्था राखिएको छ।',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'Nations at the global energy summit agreed to scale up renewable investment over the coming decade.',
      },
    ],
    seoDescriptionNe: 'विश्व ऊर्जा सम्मेलनमा नवीकरणीयमा सहमति बनेको छ।',
    seoDescriptionEn: 'The global energy summit reached agreement on renewables.',
  },
  {
    id: 'art-017',
    slug: 'regional-trade-pact',
    category: { id: 'cat-world', slug: 'world', nameNe: 'विश्व', nameEn: 'World' },
    categoryLabel: 'विश्व',
    titleNe: 'क्षेत्रीय व्यापार सम्झौतामा प्रगति',
    heroImage: unsplash('1526304640581-d334cdbbf45e', 'व्यापार बन्दरगाह', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'एजेन्सी रिपोर्ट',
    authors: [{ id: 'aut-agency', slug: 'agency-report', name: 'एजेन्सी रिपोर्ट' }],
    publishedAt: '2026-06-16T11:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    source: {
      sourceType: 'aggregated',
      sourceName: 'Associated Press',
      sourceUrl: 'https://apnews.com/',
      sourcePublishedAt: '2026-06-16T09:00:00.000Z',
    },
    bodyNe: [
      {
        type: 'paragraph',
        text: 'क्षेत्रीय व्यापार सम्झौताको पछिल्लो चरणको छलफलमा भन्सार व्यवस्थामा सहमति जनाइएको छ।',
      },
    ],
    seoDescriptionNe: 'क्षेत्रीय व्यापार सम्झौतामा प्रगति भएको छ।',
  },
  {
    id: 'art-018',
    slug: 'world-health-vaccine',
    category: { id: 'cat-world', slug: 'world', nameNe: 'विश्व', nameEn: 'World' },
    categoryLabel: 'विश्व',
    titleNe: 'विश्वव्यापी स्वास्थ्य निकायले खोप आपूर्तिको समीक्षा गर्‍यो',
    heroImage: unsplash('1576765608535-5f04d1e3f5af', 'औषधि उत्पादन', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'एजेन्सी रिपोर्ट',
    authors: [{ id: 'aut-agency', slug: 'agency-report', name: 'एजेन्सी रिपोर्ट' }],
    publishedAt: '2026-06-13T07:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    source: {
      sourceType: 'wire',
      sourceName: 'Agence France-Presse',
      sourceUrl: 'https://www.afp.com/',
      sourcePublishedAt: '2026-06-13T05:00:00.000Z',
    },
    bodyNe: [
      {
        type: 'paragraph',
        text: 'विश्वव्यापी स्वास्थ्य निकायले खोप आपूर्ति शृंखलाको समीक्षा गर्दै बराबर वितरणका लागि सिफारिस जारी गरेको छ।',
      },
    ],
    seoDescriptionNe: 'विश्वव्यापी स्वास्थ्य निकायले खोप आपूर्तिको समीक्षा गरेको छ।',
  },

  // -- OPINION ---------------------------------------------------------------
  {
    id: 'art-019',
    slug: 'column-democratic-institutions',
    category: { id: 'cat-opinion', slug: 'opinion', nameNe: 'विचार', nameEn: 'Opinion' },
    categoryLabel: 'विचार',
    titleNe: 'लोकतान्त्रिक संस्था मजबुत गर्ने जिम्मेवारी',
    titleEn: 'The responsibility of strengthening democratic institutions',
    deckNe: 'संस्थागत स्वायत्तता र जवाफदेहिता बिना सुधार अर्थहीन हुन्छ।',
    heroImage: unsplash('1486325212027-8081e485255e', 'सार्वजनिक भवन', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'प्रकाश भट्टराई',
    authors: [{ id: 'aut-prakash', slug: 'prakash-bhattarai', name: 'प्रकाश भट्टराई' }],
    publishedAt: '2026-06-18T05:30:00.000Z',
    hasEnglish: true,
    isBreaking: false,
    readingMinutes: 5,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'लोकतन्त्रको बलियो संरचना भनेको संस्थाको स्वायत्तता र जवाफदेहितामा भर पर्छ। यी दुई आधार कमजोर हुँदा नीतिगत सुधारले अपेक्षित नतिजा दिँदैन।',
      },
      { type: 'heading2', text: 'स्वायत्तताको अर्थ' },
      {
        type: 'paragraph',
        text: 'संस्थालाई कार्यकारी दबाबबाट मुक्त राख्नु र तिनका निर्णयको पारदर्शी समीक्षा हुनु दुवै एकसाथ आवश्यक छ।',
      },
      {
        type: 'pullQuote',
        quoteNe: 'संस्था बिनाको सुधार घर बिनाको जग जस्तै हुन्छ।',
        attribution: 'लेखक',
      },
      {
        type: 'paragraph',
        text: 'अन्ततः लोकतन्त्रको मापदण्ड चुनावमा मात्र होइन, संस्थाले दैनिक रूपमा कसरी काम गर्छ भन्नामा झल्किन्छ।',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'A healthy democracy rests on institutional autonomy paired with accountability; weaken either and reforms lose meaning.',
      },
    ],
    seoDescriptionNe: 'लोकतान्त्रिक संस्था मजबुत गर्ने जिम्मेवारीमा एक स्तम्भ।',
    seoDescriptionEn: 'A column on strengthening democratic institutions.',
  },
  {
    id: 'art-020',
    slug: 'column-foreign-policy-balance',
    category: { id: 'cat-opinion', slug: 'opinion', nameNe: 'विचार', nameEn: 'Opinion' },
    categoryLabel: 'विचार',
    titleNe: 'छिमेकीबीच कूटनीतिक सन्तुलनको आवश्यकता',
    heroImage: unsplash('1528969477-3295c2b6e6c4', 'झण्डाहरू', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'प्रकाश भट्टराई',
    authors: [{ id: 'aut-prakash', slug: 'prakash-bhattarai', name: 'प्रकाश भट्टराई' }],
    publishedAt: '2026-06-14T04:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 4,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'दुई ठूला छिमेकीबीच कूटनीतिक सन्तुलन कायम राख्नु बाह्य नीतिको केन्द्रबिन्दु हो। यो सन्तुलन व्यावहारिक र दीर्घकालीन दृष्टिकोणबाट मात्र सम्भव छ।',
      },
    ],
    seoDescriptionNe: 'छिमेकीबीच कूटनीतिक सन्तुलनको आवश्यकतामा एक स्तम्भ।',
  },
  {
    id: 'art-021',
    slug: 'column-urban-planning',
    category: { id: 'cat-opinion', slug: 'opinion', nameNe: 'विचार', nameEn: 'Opinion' },
    categoryLabel: 'विचार',
    titleNe: 'शहर विस्तार र दीर्घकालीन योजनाको अभाव',
    heroImage: unsplash('1480714378408-67cf0d13bc1b', 'शहरको दृश्य', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'प्रकाश भट्टराई',
    authors: [{ id: 'aut-prakash', slug: 'prakash-bhattarai', name: 'प्रकाश भट्टराई' }],
    publishedAt: '2026-06-11T03:30:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 4,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'छिटो शहर विस्तारको तुलनामा दीर्घकालीन योजना पछाडि छ। यातायात, खुला ठाउँ र आधारभूत सेवाको सन्तुलनमा ध्यान नदिँदा समस्या थपिँदै छन्।',
      },
    ],
    seoDescriptionNe: 'शहर विस्तार र दीर्घकालीन योजनाको अभावमा एक स्तम्भ।',
  },

  // -- DIASPORA --------------------------------------------------------------
  {
    id: 'art-022',
    slug: 'diaspora-labour-rights',
    category: { id: 'cat-diaspora', slug: 'diaspora', nameNe: 'प्रवास', nameEn: 'Diaspora' },
    categoryLabel: 'प्रवास',
    titleNe: 'खाडी मुलुकमा श्रमिक अधिकारको मुद्दा पुनः बहसमा',
    titleEn: 'Migrant labour rights in the Gulf back in focus',
    deckNe: 'नयाँ सम्झौताले श्रमिकको सुरक्षा र जानकारीमा सुधार ल्याउने दाबी गरेको छ।',
    heroImage: unsplash('1454165804606-c3d57bc86b42', 'विदेशी श्रमिक', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'हेमन्त रिजाल',
    authors: [{ id: 'aut-diaspora', slug: 'hemant-rijal', name: 'हेमन्त रिजाल' }],
    publishedAt: '2026-06-17T06:00:00.000Z',
    hasEnglish: true,
    isBreaking: false,
    readingMinutes: 4,
    tags: [
      {
        id: 'tag-migration',
        slug: 'labour-migration',
        nameNe: 'श्रम प्रवास',
        nameEn: 'Labour migration',
      },
    ],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'नयाँ द्विपक्षीय सम्झौताले श्रमिकको सुरक्षा र कार्यसमयको जानकारी थप पारदर्शी बनाउने दाबी गरेको छ। प्रवासी नेपालीले भने कार्यान्वयनमा ध्यान दिनुपर्नेमा जोड दिएका छन्।',
      },
      {
        type: 'list',
        ordered: false,
        items: ['स्पष्ट कार्य सम्झौता', 'पहुँचयोग्य गुनासो संयन्त्र', 'नियमित स्वास्थ्य जाँच'],
      },
      {
        type: 'paragraph',
        text: 'कार्यान्वयनको अनुगमन बिना सम्झौताले भरपुर अर्थ राख्दैन भन्ने अनुभव विगतले देखाएको छ।',
      },
    ],
    bodyEn: [
      {
        type: 'paragraph',
        text: 'A new bilateral agreement claims stronger safeguards and clearer information for migrant workers, who stress that implementation is what matters.',
      },
    ],
    seoDescriptionNe: 'खाडी मुलुकमा श्रमिक अधिकारको मुद्दा पुनः बहसमा छ।',
    seoDescriptionEn: 'Migrant labour rights in the Gulf are back in focus.',
  },
  {
    id: 'art-023',
    slug: 'diaspora-remittance-families',
    category: { id: 'cat-diaspora', slug: 'diaspora', nameNe: 'प्रवास', nameEn: 'Diaspora' },
    categoryLabel: 'प्रवास',
    titleNe: 'रेमिट्यान्सले पारिवारिक जीवनमा पारेको असर',
    heroImage: unsplash('1605164599901-ci44e1a0e3e3', 'परिवार', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'हेमन्त रिजाल',
    authors: [{ id: 'aut-diaspora', slug: 'hemant-rijal', name: 'हेमन्त रिजाल' }],
    publishedAt: '2026-06-13T08:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 3,
    tags: [
      {
        id: 'tag-migration',
        slug: 'labour-migration',
        nameNe: 'श्रम प्रवास',
        nameEn: 'Labour migration',
      },
    ],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'रेमिट्यान्सले आय बढाए पनि परिवार छुट्टिने र बालबालिकाको हेरचाहमा असर परेको अध्ययनहरूले देखाएका छन्।',
      },
    ],
    seoDescriptionNe: 'रेमिट्यान्सले पारिवारिक जीवनमा पारेको असरको विश्लेषण।',
  },

  // -- Extra POLITICS / SOCIETY / BUSINESS ----------------------------------
  {
    id: 'art-024',
    slug: 'provincial-election-prep',
    category: { id: 'cat-politics', slug: 'politics', nameNe: 'राजनीति', nameEn: 'Politics' },
    categoryLabel: 'राजनीति',
    titleNe: 'स्थानीय निर्वाचनको तयारी सुरु',
    heroImage: unsplash('16057101963fi-6c6e2e2e2e2e', 'मतदान केन्द्र', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'श्रीजना कार्की',
    authors: [{ id: 'aut-srijana', slug: 'srijana-karki', name: 'श्रीजना कार्की' }],
    publishedAt: '2026-06-12T07:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [
      {
        id: 'tag-election',
        slug: 'local-election',
        nameNe: 'स्थानीय निर्वाचन',
        nameEn: 'Local election',
      },
    ],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'निर्वाचन आयोगले स्थानीय तहको निर्वाचनको तयारी सुरु गरेको छ। मतदाता नामावली अद्यावधिक गर्ने काम जारी छ।',
      },
    ],
    seoDescriptionNe: 'स्थानीय निर्वाचनको तयारी सुरु भएको छ।',
  },
  {
    id: 'art-025',
    slug: 'court-ruling-land',
    category: { id: 'cat-politics', slug: 'politics', nameNe: 'राजनीति', nameEn: 'Politics' },
    categoryLabel: 'राजनीति',
    titleNe: 'सर्वोच्च अदालतको जग्गा सम्बन्धी फैसला',
    heroImage: unsplash('1589829085411-6d63ee3e1c3c', 'अदालतको कक्ष', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'श्रीजना कार्की',
    authors: [{ id: 'aut-srijana', slug: 'srijana-karki', name: 'श्रीजना कार्की' }],
    publishedAt: '2026-06-10T04:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 3,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'सर्वोच्च अदालतले जग्गा स्वामित्व सम्बन्धी मुद्दामा फैसला सुनाएको छ। फैसलाले दर्ता प्रक्रियामा स्पष्टता ल्याउने अपेक्षा गरिएको छ।',
      },
    ],
    seoDescriptionNe: 'सर्वोच्च अदालतको जग्गा सम्बन्धी फैसला।',
  },
  {
    id: 'art-026',
    slug: 'monsoon-flood-alert',
    category: { id: 'cat-society', slug: 'society', nameNe: 'समाज', nameEn: 'Society' },
    categoryLabel: 'समाज',
    titleNe: 'मनसुन सक्रिय: नदी किनारमा सतर्कता जारी',
    heroImage: unsplash('1527482799tail-1a1a1a1a1a', 'बाढी प्रभावित क्षेत्र', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'अन्जना घिमिरे',
    authors: [{ id: 'aut-anjana', slug: 'anjana-ghimire', name: 'अन्जना घिमिरे' }],
    publishedAt: '2026-06-11T06:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [{ id: 'tag-climate', slug: 'climate', nameNe: 'जलवायु', nameEn: 'Climate' }],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'मनसुन सक्रिय भएसँगै नदी किनारका बस्तीमा सतर्कता अपनाइएको छ। उद्धार टोलीलाई तयार राखिएको अधिकारीहरूले जनाएका छन्।',
      },
    ],
    seoDescriptionNe: 'मनसुनमा नदी किनारमा सतर्कता जारी छ।',
  },
  {
    id: 'art-027',
    slug: 'public-transport-fare',
    category: { id: 'cat-society', slug: 'society', nameNe: 'समाज', nameEn: 'Society' },
    categoryLabel: 'समाज',
    titleNe: 'सार्वजनिक यातायातको भाडा समीक्षा',
    heroImage: unsplash('1556122071-e404eaedb77f', 'सार्वजनिक यातायात', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'अन्जना घिमिरे',
    authors: [{ id: 'aut-anjana', slug: 'anjana-ghimire', name: 'अन्जना घिमिरे' }],
    publishedAt: '2026-06-09T05:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'सार्वजनिक यातायातको भाडा समीक्षा गर्ने प्रस्ताव छलफलमा छ। यात्रु संघले विगतको तुलनामा भाडा उच्च भएको जनाएको छ।',
      },
    ],
    seoDescriptionNe: 'सार्वजनिक यातायातको भाडा समीक्षामा छ।',
  },
  {
    id: 'art-028',
    slug: 'inflation-report-quarterly',
    category: { id: 'cat-business', slug: 'business', nameNe: 'बजार', nameEn: 'Business' },
    categoryLabel: 'बजार',
    titleNe: 'महिन्यौले मुद्रास्फीति थोरै घट्यो',
    heroImage: unsplash('1611974789855-9c2a0a7cd6a9', 'बजारको सूचकांक', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'बिशाल थापा',
    authors: [{ id: 'aut-bishal', slug: 'bishal-thapa', name: 'बिशाल थापा' }],
    publishedAt: '2026-06-10T09:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 3,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'केन्द्रीय बैंकको तथ्याङ्क अनुसार महिन्यौले मुद्रास्फीति थोरै घटेको छ। खाद्य वस्तुको मूल्यमा सुधार देखिएको छ।',
      },
    ],
    seoDescriptionNe: 'महिन्यौले मुद्रास्फीति थोरै घटेको छ।',
  },
  {
    id: 'art-029',
    slug: 'startup-funding-round',
    category: { id: 'cat-business', slug: 'business', nameNe: 'बजार', nameEn: 'Business' },
    categoryLabel: 'बजार',
    titleNe: 'स्थानीय स्टार्टअपले लगानी सुरक्षित गर्‍यो',
    heroImage: unsplash('1556761175-5973dc0f32e7', 'कार्यालयको वातावरण', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'बिशाल थापा',
    authors: [{ id: 'aut-bishal', slug: 'bishal-thapa', name: 'बिशाल थापा' }],
    publishedAt: '2026-06-08T08:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 3,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'एउटा स्थानीय प्रविधि कम्पनीले नयाँ लगानी चरण बन्द गरेको छ। कम्पनीले उत्पादन विस्तारमा जोड दिने बताएको छ।',
      },
    ],
    seoDescriptionNe: 'स्थानीय स्टार्टअपले लगानी सुरक्षित गरेको छ।',
  },
  {
    id: 'art-030',
    slug: 'agriculture-export-rice',
    category: { id: 'cat-business', slug: 'business', nameNe: 'बजार', nameEn: 'Business' },
    categoryLabel: 'बजार',
    titleNe: 'कृषि निर्यातमा चामलको हिस्सा बढ्दो',
    heroImage: unsplash('1574323345412-a37c6c4f1e3a', 'धानखेत', {
      ...{ w: 1600, h: 900 },
      credit: 'Unsplash',
    }),
    heroCredit: 'Unsplash',
    byline: 'बिशाल थापा',
    authors: [{ id: 'aut-bishal', slug: 'bishal-thapa', name: 'बिशाल थापा' }],
    publishedAt: '2026-06-07T07:00:00.000Z',
    hasEnglish: false,
    isBreaking: false,
    readingMinutes: 2,
    tags: [],
    bodyNe: [
      {
        type: 'paragraph',
        text: 'कृषि निर्यातमा चामलको हिस्सा बढ्दो छ। उद्यमीहरूले गुणस्तर र प्याकेजिङमा ध्यान दिँदा बजार विस्तार सम्भव भएको बताउँछन्।',
      },
    ],
    seoDescriptionNe: 'कृषि निर्यातमा चामलको हिस्सा बढ्दो छ।',
  },
]
