import type { Category } from '@nagarikwatch/db'

/**
 * Seed categories (content-model.md §2). The final list per PRODUCT.md: Politics, Society,
 * Business, Sports, Entertainment, World, Opinion, Literature, Technology, Health, Education, Interview, Photo Story, Video, plus a catch-all Diaspora section. Slugs
 * are Latin (URL segment), labels are Devanagari-primary + English.
 */
export const categories: Category[] = [
  {
    id: 'cat-politics',
    slug: 'politics',
    nameNe: 'राजनीति',
    nameEn: 'Politics',
    descriptionNe: 'संसद्, सरकार, दल र नीतिगत विमर्शका समाचार र विश्लेषण।',
    descriptionEn: 'News and analysis from parliament, government, parties and policy.',
    navOrder: 1,
    showInNav: true,
  },
  {
    id: 'cat-society',
    slug: 'society',
    nameNe: 'समाज',
    nameEn: 'Society',
    descriptionNe: 'शिक्षा, स्वास्थ्य, समुदाय र दैनिक जीवनका समाचार।',
    descriptionEn: 'Education, health, community and the stories of everyday life.',
    navOrder: 2,
    showInNav: true,
  },
  {
    id: 'cat-business',
    slug: 'business',
    nameNe: 'बजार',
    nameEn: 'Business',
    descriptionNe: 'अर्थतन्त्र, बजार, लगानी र रोजगारीका समाचार।',
    descriptionEn: 'Economy, markets, investment and the jobs story.',
    navOrder: 3,
    showInNav: true,
  },
  {
    id: 'cat-sports',
    slug: 'sports',
    nameNe: 'खेलकुद',
    nameEn: 'Sports',
    descriptionNe: 'क्रिकेट, फुटबल र राष्ट्रिय तथा अन्तर्राष्ट्रिय खेलका समाचार।',
    descriptionEn: 'Cricket, football and national and international sport.',
    navOrder: 4,
    showInNav: true,
  },
  {
    id: 'cat-entertainment',
    slug: 'entertainment',
    nameNe: 'मनोरञ्जन',
    nameEn: 'Entertainment',
    descriptionNe: 'चलचित्र, संगीत र संस्कृतिका समाचार।',
    descriptionEn: 'Film, music and culture.',
    navOrder: 5,
    showInNav: true,
  },
  {
    id: 'cat-world',
    slug: 'world',
    nameNe: 'विश्व',
    nameEn: 'World',
    descriptionNe: 'विश्वभरका महत्त्वपूर्ण समाचार।',
    descriptionEn: 'The stories that matter from across the world.',
    navOrder: 6,
    showInNav: true,
  },
  {
    id: 'cat-opinion',
    slug: 'opinion',
    nameNe: 'विचार',
    nameEn: 'Opinion',
    descriptionNe: 'स्तम्भ, विश्लेषण र सम्पादकीय राय।',
    descriptionEn: 'Columns, analysis and editorial voices.',
    navOrder: 7,
    showInNav: true,
  },

  {
    id: 'cat-literature',
    slug: 'literature',
    nameNe: 'साहित्य',
    nameEn: 'Literature',
    descriptionNe: 'कविता, कथा, निबन्ध, पुस्तक समीक्षा र साहित्यिक विमर्श।',
    descriptionEn: 'Poetry, fiction, essays, book reviews and literary criticism.',
    navOrder: 8,
    showInNav: true,
  },
  {
    id: 'cat-technology',
    slug: 'technology',
    nameNe: 'प्रविधि',
    nameEn: 'Technology',
    descriptionNe: 'डिजिटल सेवा, एआई, साइबर सुरक्षा, स्टार्टअप र विज्ञान प्रविधि।',
    descriptionEn: 'Digital services, AI, cybersecurity, startups, science and technology.',
    navOrder: 9,
    showInNav: true,
  },
  {
    id: 'cat-health',
    slug: 'health',
    nameNe: 'स्वास्थ्य',
    nameEn: 'Health',
    descriptionNe: 'जनस्वास्थ्य, अस्पताल, औषधि, जीवनशैली र स्वास्थ्य नीति।',
    descriptionEn: 'Public health, hospitals, medicine, lifestyle and health policy.',
    navOrder: 10,
    showInNav: true,
  },
  {
    id: 'cat-education',
    slug: 'education',
    nameNe: 'शिक्षा',
    nameEn: 'Education',
    descriptionNe: 'विद्यालय, विश्वविद्यालय, परीक्षा, छात्रवृत्ति र शिक्षा नीतिका समाचार।',
    descriptionEn: 'Schools, universities, examinations, scholarships and education policy.',
    navOrder: 11,
    showInNav: true,
  },
  {
    id: 'cat-interview',
    slug: 'interview',
    nameNe: 'अन्तर्वार्ता',
    nameEn: 'Interview',
    descriptionNe: 'समाचार निर्माता, विज्ञ, लेखक र नागरिकसँगका प्रश्नोत्तर।',
    descriptionEn: 'Q&A with newsmakers, experts, writers and citizens.',
    navOrder: 12,
    showInNav: true,
  },
  {
    id: 'cat-photo-story',
    slug: 'photo-story',
    nameNe: 'फोटो फिचर',
    nameEn: 'Photo Story',
    descriptionNe: 'तस्वीरमार्फत भनिएका सार्वजनिक जीवन, संस्कृति र घटनाका कथा।',
    descriptionEn: 'Visual reporting on public life, culture and events.',
    navOrder: 13,
    showInNav: true,
  },
  {
    id: 'cat-video',
    slug: 'video',
    nameNe: 'भिडियो',
    nameEn: 'Video',
    descriptionNe: 'भिडियो रिपोर्ट, व्याख्या, अन्तर्वार्ता र मल्टिमिडिया सामग्री।',
    descriptionEn: 'Video reports, explainers, interviews and multimedia stories.',
    navOrder: 14,
    showInNav: true,
  },
  {
    id: 'cat-diaspora',
    slug: 'diaspora',
    nameNe: 'प्रवास',
    nameEn: 'Diaspora',
    descriptionNe: 'विदेशमा रहेका नेपालीहरूका समाचार र अनुभव।',
    descriptionEn: 'News and voices of Nepalis living abroad.',
    navOrder: 15,
    showInNav: false,
  },
]

/** Quick id -> category lookup used across the seed. */
export const categoryById = new Map(categories.map((c) => [c.id, c]))
export const categoryBySlug = new Map(categories.map((c) => [c.slug, c]))
