import type { Tag } from '@nagarikwatch/db'

/** Seed tags / topics (content-model.md §4). Cross-category running-story groupings. */
export const tags: Tag[] = [
  {
    id: 'tag-budget',
    slug: 'budget-2083',
    nameNe: 'बजेट २०८३',
    nameEn: 'Budget 2083',
    descriptionNe: 'आर्थिक वर्ष २०८३/८४ को संघीय बजेटको कभरेज।',
    descriptionEn: 'Coverage of the federal budget for fiscal year 2083/84.',
  },
  {
    id: 'tag-election',
    slug: 'local-election',
    nameNe: 'स्थानीय निर्वाचन',
    nameEn: 'Local election',
    descriptionNe: 'स्थानीय तहको निर्वाचनसम्बन्धी समाचार र विश्लेषण।',
    descriptionEn: 'Reporting and analysis on local-level elections.',
  },
  {
    id: 'tag-cricket',
    slug: 'nepal-cricket',
    nameNe: 'नेपाली क्रिकेट',
    nameEn: 'Nepal cricket',
    descriptionNe: 'राष्ट्रिय क्रिकेट टोलीका समाचार।',
    descriptionEn: 'News on the national cricket team.',
  },
  {
    id: 'tag-climate',
    slug: 'climate',
    nameNe: 'जलवायु',
    nameEn: 'Climate',
    descriptionNe: 'वातावरण र जलवायु परिवर्तनका समाचार।',
    descriptionEn: 'Environment and climate coverage.',
  },
  {
    id: 'tag-migration',
    slug: 'labour-migration',
    nameNe: 'श्रम प्रवास',
    nameEn: 'Labour migration',
    descriptionNe: 'विदेशी रोजगारी र प्रवासी नेपालीका समाचार।',
    descriptionEn: 'Foreign employment and migrant-worker stories.',
  },
  {
    id: 'tag-football',
    slug: 'fifa-world-cup',
    nameNe: 'फिफा विश्वकप',
    nameEn: 'FIFA World Cup',
    descriptionNe: 'फिफा विश्वकप २०२६ को कभरेज।',
    descriptionEn: 'Coverage of the 2026 FIFA World Cup.',
  },
  {
    id: 'tag-geopolitics',
    slug: 'geopolitics',
    nameNe: 'भूराजनीति',
    nameEn: 'Geopolitics',
    descriptionNe: 'विश्व भूराजनीतिक विमर्श र संघर्षका समाचार।',
    descriptionEn: 'Global geopolitical conflict and analysis.',
  },
  {
    id: 'tag-editor-pick',
    slug: 'editor-pick',
    nameNe: 'सम्पादकको रोजाइ',
    nameEn: 'Editor pick',
    descriptionNe: 'सम्पादकीय टोलीले विशेष रूपमा छानेका सामग्री।',
    descriptionEn: 'Stories explicitly selected by the editorial desk.',
  },
  {
    id: 'tag-exclusive',
    slug: 'exclusive-report',
    nameNe: 'विशेष रिपोर्ट',
    nameEn: 'Exclusive report',
    descriptionNe: 'मौलिक रिपोर्टिङ वा अनुसन्धानमा आधारित विशेष सामग्री।',
    descriptionEn: 'Exclusive or original-investigation reporting.',
  },
  {
    id: 'tag-data-story',
    slug: 'data-story',
    nameNe: 'डाटा कथा',
    nameEn: 'Data story',
    descriptionNe: 'डाटा, ग्राफ, तालिका वा पद्धतिसहितका कथा।',
    descriptionEn: 'Data-led stories with charts, tables or methodology.',
  },
  {
    id: 'tag-reader-submission',
    slug: 'reader-submission',
    nameNe: 'पाठक सामग्री',
    nameEn: 'Reader submission',
    descriptionNe: 'सम्पादकीय स्वीकृतिपछि प्रकाशित पाठक सामग्री।',
    descriptionEn: 'Reader material published after editorial review.',
  },
  {
    id: 'tag-video-report',
    slug: 'video-report',
    nameNe: 'भिडियो रिपोर्ट',
    nameEn: 'Video report',
    descriptionNe: 'भिडियो, अन्तर्वार्ता वा दृश्य व्याख्यासहितका सामग्री।',
    descriptionEn: 'Video-led reports, interviews and explainers.',
  },
  {
    id: 'tag-photo-story',
    slug: 'photo-story',
    nameNe: 'फोटो कथा',
    nameEn: 'Photo story',
    descriptionNe: 'फोटो पत्रकारिता र दृश्य कथाका सामग्री।',
    descriptionEn: 'Photojournalism and visual-story packages.',
  },
  {
    id: 'tag-exam-results',
    slug: 'exam-results',
    nameNe: 'परीक्षा नतिजा',
    nameEn: 'Exam results',
    descriptionNe: 'SEE, कक्षा १२ र सार्वजनिक परीक्षाका नतिजा र व्याख्या।',
    descriptionEn: 'SEE, Grade XII and public examination results and explainers.',
  },
  {
    id: 'tag-fact-check',
    slug: 'fact-check',
    nameNe: 'तथ्य-जाँच',
    nameEn: 'Fact check',
    descriptionNe: 'दाबी, प्रमाण र निष्कर्षसहितका तथ्य-जाँच सामग्री।',
    descriptionEn: 'Fact-check pieces with claim, evidence and verdict.',
  },
]

export const tagById = new Map(tags.map((t) => [t.id, t]))
export const tagBySlug = new Map(tags.map((t) => [t.slug, t]))
